<link href="../site.css" rel="stylesheet" type="text/css"/>
<div class="mw-page-container"><h1 class="firstHeading mw-first-heading" id="firstHeading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial II/de</span></h1><div class="mw-parser-output"><div id="itsfree" style="text-align:center; background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">
<figure class="mw-halign-left" typeof="mw:File"><span><img decoding="async" height="38" src="https://upload.wikimedia.org/wikipedia/commons/d/d5/Under_construction_icon-blue.svg" width="45"/></span><figcaption></figcaption></figure> This documentation is a work in progress. Please don't mark it as translatable since it will change in the next hours and days.
</div><div style="clear:both"></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img decoding="async" height="32" src="../File/Freecad.svg" width="32"/></span></span> Tutorium
</td></tr>
<tr>
<th class="ctOdd">Thema
</th></tr>
<tr>
<td class="ctEven">Modellierung
</td></tr>
<tr>
<th class="ctOdd">Niveau
</th></tr>
<tr>
<td class="ctEven">Erfahrene Anwender
</td></tr>
<tr>
<th class="ctOdd">Zeit zum Abschluss
</th></tr>
<tr>
<td class="ctEven"><i>Not provided</i>
</td></tr>
<tr>
<th class="ctOdd">Autoren
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">FreeCAD-Version
</th></tr>
<tr>
<td class="ctEven">0.19.23300 oder höher
</td></tr>
<tr>
<th class="ctOdd">Beispieldateien
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Siehe auch
</th></tr>
<tr>
<td class="ctEven"><i>None</i>
</td></tr>
<tr>
<td class="ctToc"><br/><div aria-labelledby="mw-toc-heading" class="toc" id="toc" role="navigation"><input class="toctogglecheckbox" id="toctogglecheckbox" role="button" style="display:none" type="checkbox"/><div class="toctitle" dir="ltr" lang="en"><h2 id="mw-toc-heading">Contents</h2><span class="toctogglespan"><label class="toctogglelabel" for="toctogglecheckbox"></label></span></div>
<ul>
<li class="toclevel-1 tocsection-1"><a href="#Kurze_Zweckbestimmung"><span class="tocnumber">1</span> <span class="toctext">Kurze Zweckbestimmung</span></a></li>
<li class="toclevel-1 tocsection-2"><a href="#Konstruktionsdaten"><span class="tocnumber">2</span> <span class="toctext">Konstruktionsdaten</span></a></li>
<li class="toclevel-1 tocsection-3"><a href="#Einrichten_der_Skelettgeometrie"><span class="tocnumber">3</span> <span class="toctext">Einrichten der Skelettgeometrie</span></a></li>
<li class="toclevel-1 tocsection-4"><a href="#Der_Hauptkörper"><span class="tocnumber">4</span> <span class="toctext">Der Hauptkörper</span></a></li>
<li class="toclevel-1 tocsection-5"><a href="#Hinzufügen_der_Körper_für_die_Schrauben"><span class="tocnumber">5</span> <span class="toctext">Hinzufügen der Körper für die Schrauben</span></a></li>
<li class="toclevel-1 tocsection-6"><a href="#Aushöhlung_des_Hauptkörpers"><span class="tocnumber">6</span> <span class="toctext">Aushöhlung des Hauptkörpers</span></a></li>
<li class="toclevel-1 tocsection-7"><a href="#Spanende_Bearbeitung"><span class="tocnumber">7</span> <span class="toctext">Spanende Bearbeitung</span></a></li>
<li class="toclevel-1 tocsection-8"><a href="#Teil_Eins"><span class="tocnumber">8</span> <span class="toctext">Teil Eins</span></a></li>
</ul>
</div>
</td></tr></tbody></table>
<div id="itsfree" style="text-align:center;color:black;background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">Dieses Tutorial wurde ursprünglich für eine inzwischen veraltete Entwicklungsversion von FreeCAD geschrieben. Seit April 2016 sind diese Funktionen in die Vorentwicklungsversion 0.17 integriert, die <a class="external text" href="https://github.com/FreeCAD/FreeCAD/releases/tag/0.17_pre" rel="nofollow">hier</a> verfügbar ist.
<p><br/>
</p>
Bitte beachte, dass sich diese Version von FreeCAD noch in einem frühen Entwicklungsstadium befindet. Außerdem muss dieses Tutorium möglicherweise aktualisiert werden. Wenn du an der Überprüfung und Aktualisierung teilnehmen möchtest, poste bitte in den Wiki Abschnitt des <a class="external text" href="http://forum.freecadweb.org" rel="nofollow">forum</a>.</div>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-19.jpg"><img decoding="async" height="263" src="../File/HolderTop2-19.jpg" srcset="/images/thumb/9/90/HolderTop2-19.jpg/600px-HolderTop2-19.jpg 1.5x, /images/thumb/9/90/HolderTop2-19.jpg/800px-HolderTop2-19.jpg 2x" width="400"/></a><figcaption>Lagergehäuse Tutorium - Fertiges Lagergehäuse (oben)</figcaption></figure>
<p><strike>
Wie der Warnhinweis oben auf der Seite bereits andeutet, funktioniert dieses <b>Tutorium NICHT, es sei denn, du kompilierst einen speziellen, sehr experimentellen Zweig aus dem FreeCAD Quellcode</b> und ist ein einführendes Tutorium zur Modellierung mit dem PartDesign Arbeitsbereich in FreeCAD <b>unter Verwendung von Datumsebenen, die in den meisten FreeCAD Versionen noch nicht vorhanden sind</b>.
</strike>
</p>
<h2><span class="mw-headline" id="Kurze_Zweckbestimmung">Kurze Zweckbestimmung</span></h2>
<p>Der Zweck des Tutoriums ist es, dich in zwei verschiedene Arbeitsabläufe zur Erstellung eines Gussteils mit Entwürfen und Verrundungen einzuführen. Je nachdem, welche anderen CAD-Programme du bisher verwendet hast, könnte dir das eine oder das andere vertraut sein. Als Arbeitsbeispiel werden wir ein einfaches Lagergehäuse modellieren.
</p><p>Dies ist der zweite Teil des Tutoriums. Es wird der so genannte "Multikörper" Arbeitsablauf verwendet, wobei der (einfachere) obere Teil des Gehäuses als Beispiel dient.
</p><p>Selbstverständlich musst du zum Durcharbeiten dieses Tutorials den PartDesign Arbeitsbereich aktivieren.
</p><p><strike> Du findest meine Version des von diesem Tutorium erstellten Teils [<a class="external text" href="http://ubuntuone.com/39PTZ3Y3LUnmZzpZQPcJT4" rel="nofollow">hier</a>].</strike> <i>Die Datei ist nicht mehr verfügbar, eine neue wird zu einem späteren Zeitpunkt bereitgestellt werden</i>.
<br clear="all"/>
</p>
<h2><span class="mw-headline" id="Konstruktionsdaten">Konstruktionsdaten</span></h2>
<p>Das Gehäuse sollte in der Lage sein, ein Lager mit einem Durchmesser von 90 mm und einer Breite von bis zu 33 mm aufzunehmen (z.B. DIN 630 Typ 2308 mit einem Innendurchmesser von 40 mm). Das Lager erfordert eine Schulterhöhe von mindestens 4,5 mm im Halter (und auf der Welle). Der obere Teil des Gehäuses wird mit zwei 12mm Schrauben an der Unterseite verschraubt. Der Kopf einer solchen Schraube benötigt einen Freiraum von mindestens 20 mm Durchmesser. Auf beiden Seiten des Lagers sollte eine Nut vorhanden sein, die einen Standard-Wellendichtring DIN 3760 aufnehmen kann: 38x55x7 oder 40x55x7 auf der einen Seite, 50x68x8 auf der anderen Seite.
</p><p>Das Gehäuse wird ein Sandguss mit einer Mindestwandstärke von 5 mm, einem Entformungswinkel von 2 Grad und einem minimalen Verrundungsradius von 3 mm sein.
</p><p><br clear="all"/>
</p>
<h2><span class="mw-headline" id="Einrichten_der_Skelettgeometrie">Einrichten der Skelettgeometrie</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-2.png"><img decoding="async" height="149" src="../File/HolderTop2-2.png" srcset="/images/thumb/1/19/HolderTop2-2.png/600px-HolderTop2-2.png 1.5x, /images/thumb/1/19/HolderTop2-2.png/800px-HolderTop2-2.png 2x" width="400"/></a><figcaption>Skizze der Skelettgeometrie</figcaption></figure>
<p>Erstelle im PartDesign Arbeitsbereich ein neues Teil. Benenne den standardmäßig erstellten Körper in Skeleton um. Dieser Körper ist wahrscheinlich bereits aktiviert, was du an der blauen Hintergrundfarbe im Formelementebaum erkennen kannst. Erstelle eine neue Skizze auf der YZ Ebene, die den Umriss der Welle, des Lagers und der Dichtungsringe enthält. Nachdem du die Skizze fertiggestellt hast, erstelle daraus ein Rotations Formelement. Dieses Skelettformelement wird später dazu verwendet, die reale Geometrie darauf zu beziehen. Das bedeutet, dass du, wenn du irgendwelche Bemaßungen ändern möchtest, nur die Bemaßungen des Skelettformelements anpassen musst, und der Rest des Teils wird entsprechend aktualisiert.
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-2-1.jpg"><img decoding="async" height="260" src="../File/HolderTop2-2-1.jpg" srcset="/images/thumb/1/14/HolderTop2-2-1.jpg/600px-HolderTop2-2-1.jpg 1.5x, /images/thumb/1/14/HolderTop2-2-1.jpg/800px-HolderTop2-2-1.jpg 2x" width="400"/></a><figcaption>Die Skelettgeometrie</figcaption></figure>
<p><br clear="all"/>
</p>
<h2><span id="Der_Hauptk.C3.B6rper"></span><span class="mw-headline" id="Der_Hauptkörper">Der Hauptkörper</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-3.jpg"><img decoding="async" height="298" src="../File/HolderTop2-3.jpg" srcset="/images/thumb/8/86/HolderTop2-3.jpg/600px-HolderTop2-3.jpg 1.5x, /images/thumb/8/86/HolderTop2-3.jpg/800px-HolderTop2-3.jpg 2x" width="400"/></a><figcaption>Skizze des ersten Polsters</figcaption></figure>
<p>Erstelle einen neuen Körper und mache ihn aktiv. Die Skizze für den ersten Block ist rechts abgebildet. Er wird auf einer Bezugsebene mit einem Versatz von 5 mm (Wandstärke) von der Skelettfläche platziert, die die Seite eines der tragenden Dichtungsringe markiert. Da alle wichtigen Maße vom Skelett abgenommen werden, gibt es nur drei Maße: Die Bearbeitungszugabe (3 mm) an der Basis als Versatz zur XY Ebene, die 5 mm Wanddicke vom Außendurchmesser des Skeletts und der Entformungswinkel von zwei Grad. Zwei erzeugen die 5mm Bemaßung, du musst zuerst den Außenkreis (Radius 45mm) der Skelettgeometrie als Außengeometrie im Skizzierer auswählen und dann eine tangential zu diesem Kreis und in einem Winkel von zwei Grad gebundene Konstruktionslinie einfügen.
</p><p>Du fragst dich wahrscheinlich, warum sich am unteren Ende jedes Bogens dieses kleine gerade Segment befindet. Dieses Segment sorgt dafür, dass auf den Bögen ein Entformungswinkel von 2 Grad entsteht. Das mag nach viel Arbeit für einen sehr kleinen Nutzen aussehen, aber viele CAD Programme (und vielleicht eines Tages auch FreeCAD) haben Werkzeuge, die ein Volumenmodell in verschiedenen Farben hervorheben und dir sofort alle Flächen anzeigt, bei denen der Entformungswinkel nicht korrekt ist. Du willst nicht, dass das mit deinem Modell passiert, besonders nachdem du viele Verrundungen angebracht hast!
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-4.jpg"><img decoding="async" height="279" src="../File/HolderTop2-4.jpg" srcset="/images/thumb/c/cd/HolderTop2-4.jpg/600px-HolderTop2-4.jpg 1.5x, /images/thumb/c/cd/HolderTop2-4.jpg/800px-HolderTop2-4.jpg 2x" width="400"/></a><figcaption>Das erste Polster</figcaption></figure>
<p>Wenn du die Skizze angefertigt hast (was wegen der 2 Grad Tangentiallinien etwas knifflig ist), erstelle daraus ein Polster, das sich bis zur anderen Seite der Skelettgeometrie erstreckt, wiederum mit einem Versatz von 5 mm zur Seitenfläche. du brauchst diesmal keine Bezugsebene zu erzeugen, der "bis zur Fläche" Modus des Polster Dialogs bietet die Eingabe eines Versatzes an.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-5.jpg"><img decoding="async" height="313" src="../File/HolderTop2-5.jpg" srcset="/images/thumb/6/6a/HolderTop2-5.jpg/600px-HolderTop2-5.jpg 1.5x, /images/thumb/6/6a/HolderTop2-5.jpg/800px-HolderTop2-5.jpg 2x" width="400"/></a><figcaption>Skizze für Polsterausschnitt</figcaption></figure>
<p>Als Nächstes werden wir an beiden Enden des Polsters etwas Material wegschneiden, da es für Gussteile immer ideal ist, eine möglichst gleichmäßige Wandstärke zu haben. Erstelle eine Skizze auf jeder der Stirnseiten des Polsters und bemaße sie um 5 mm versetzt zu dem Kreis, der den Lagerdichtring darstellt (Radius 27,5 mm auf der einen Seite und 34 mm auf der anderen). Erstelle für das untere Liniensegment der Skizze eine weitere externe Geometrie vom Polster und binde diese an das Polster. So hat die Skizze nur ein einziges Maß, die 5 mm Wandstärke (die Maße 150 mm und 75 mm sind nicht wichtig, solange sie groß genug sind, um sicherzustellen, dass alles weggeschnitten wird).
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-6.jpg"><img decoding="async" height="277" src="../File/HolderTop2-6.jpg" srcset="/images/thumb/b/bc/HolderTop2-6.jpg/600px-HolderTop2-6.jpg 1.5x, /images/thumb/b/bc/HolderTop2-6.jpg/800px-HolderTop2-6.jpg 2x" width="400"/></a><figcaption>Das Polster mit Ausschnitten zur Erzielung einer gleichmäßigen Wandstärke</figcaption></figure>
<p>Erstelle mit der von dir erstellten Skizze eine Tasche und erweitere diese auf die Fläche der Skelettgeometrie, die das Lager darstellt, minus 5 mm Versatz für die Wanddicke. Für die zweite Tasche kannst du die Option "Ausgewähltes Objekt duplizieren" aus dem Menü Bearbeiten verwenden, um die bereits erstellte Skizze zu duplizieren (wähle, dass abhängige Objekte nicht dupliziert werden sollen, wenn die Frage auftaucht). Wähle dann die Fläche aus, auf die du diese Skizze verschieben möchtest, und weise FreeCAD an, die Skizze auf diese Fläche abzubilden (dies ist ein Punkt im Menü "PartDesign"). Nachdem du die zweite Tasche erstellt hast, kannst du das Ergebnis von unten betrachten, um zu prüfen, ob du eine einheitliche Wandstärke von 5 mm um die Kontur der Skelettgeometrie herum haben.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-7.jpg"><img decoding="async" height="226" src="../File/HolderTop2-7.jpg" srcset="/images/thumb/c/cc/HolderTop2-7.jpg/600px-HolderTop2-7.jpg 1.5x, /images/thumb/c/cc/HolderTop2-7.jpg/800px-HolderTop2-7.jpg 2x" width="400"/></a><figcaption>Neutrale Ebene für die Anwendung des Entwurfs</figcaption></figure>
<p>Jetzt ist es an der Zeit, Entwurf und Verrundungen zu erstellen. Das Entwurfsformelement erfordert eine neutrale Ebene, was bedeutet, dass die Geometrie, die von dieser Ebene geschnitten wird, an ihrem Platz bleibt, während der Rest der Fläche um den Entformungswinkel geneigt wird. Die Verwendung der Unterseite des Polsters für diesen Zweck ist keine gute Idee, da die Wandstärke im oberen Teil des Halters weniger als 5 mm betragen würde. Wir erstellen also zu diesem Zweck eine Bezugsebene, die um etwa 35 mm vom XY versetzt ist. Aktiviere den Skelettkörper und erzeuge  die Ebene dort, denn wir werden sie brauchen, um den Entwurf auch auf andere Körper anzuwenden.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-8.jpg"><img decoding="async" height="233" src="../File/HolderTop2-8.jpg" srcset="/images/thumb/3/32/HolderTop2-8.jpg/600px-HolderTop2-8.jpg 1.5x, /images/thumb/3/32/HolderTop2-8.jpg/800px-HolderTop2-8.jpg 2x" width="400"/></a><figcaption>Erster Körper mit Entwurf und Verrundungen</figcaption></figure>
<p>Das Bild rechts zeigt den fertigen ersten Körper mit Entwurf und applizierten Verrundungen. Beachte, dass die äusseren (konkaven) Kanten einen grösseren Verrundungsradius von 5mm haben, wiederum mit dem Ziel, eine gleichmässigere Wandstärke zu erzeugen (mehr als 5mm ist nicht möglich, da dann nach der Bearbeitung der Innenseite des Halters die Wandstärke weniger als 5mm betragen würde).
<br clear="all"/>
</p>
<h2><span id="Hinzuf.C3.BCgen_der_K.C3.B6rper_f.C3.BCr_die_Schrauben"></span><span class="mw-headline" id="Hinzufügen_der_Körper_für_die_Schrauben">Hinzufügen der Körper für die Schrauben</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-13.jpg"><img decoding="async" height="333" src="../File/HolderTop2-13.jpg" srcset="/images/thumb/6/6b/HolderTop2-13.jpg/600px-HolderTop2-13.jpg 1.5x, /images/6/6b/HolderTop2-13.jpg 2x" width="400"/></a><figcaption>Die Skizze für den Körper für die Schrauben</figcaption></figure>
<p>Die Schrauben benötigen zwei zylindrische Körper auf beiden Seiten des Hauptkörpers. Am besten ist es, den 2 Grad Entformungswinkel in die Skizze aufzunehmen. Ich habe versucht, einen Zylinder zu drehen und später einen Entwurf anzuwenden, aber nach dem Spiegeln passierten seltsame Dinge, und ich konnte keine Verrundungen anbringen, weil die Oberfläche irgendwie verzogen war.
</p><p>Die Skizze ist so bemaßt, dass die Rotationsachse 12 mm Abstand zum Außendurchmesser des Skelettkörpers hat, 7 mm für den Radius der Bohrung plus 5 mm für die Wanddicke. Um ein vollparametrisches Teil zu erhalten, ist es eine gute Idee, dem Skelett eine Ebene etwa 25 mm über der XY Ebene hinzuzufügen, um die Oberseite der Zylinder zu markieren. Da dies bearbeitet werden soll, wird die Skizze 3mm darüber bemaßt.
</p><p><br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-14.jpg"><img decoding="async" height="244" src="../File/HolderTop2-14.jpg" srcset="/images/thumb/c/c7/HolderTop2-14.jpg/600px-HolderTop2-14.jpg 1.5x, /images/thumb/c/c7/HolderTop2-14.jpg/800px-HolderTop2-14.jpg 2x" width="400"/></a><figcaption>Der Körper für die Schrauben</figcaption></figure>
<p>Erstelle aus der Skizze eine Drehung und bringe an der Oberseite eine Verrundung von 4 mm an. Das bedeutet, dass nach dem Wegfräsen von 3 mm ein leichter Radius verbleibt, der hilft, eine scharfe Kante zu vermeiden, an der sich jemand beim Anziehen der Schraube in die Hand schneiden könnte.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-16.jpg"><img decoding="async" height="261" src="../File/HolderTop2-16.jpg" srcset="/images/thumb/6/6a/HolderTop2-16.jpg/600px-HolderTop2-16.jpg 1.5x, /images/thumb/6/6a/HolderTop2-16.jpg/800px-HolderTop2-16.jpg 2x" width="400"/></a><figcaption>Der Hauptkörper mit den beiden Körpern für die Schrauben</figcaption></figure>
<p>Erstelle ein boolesches Formelement, um den Hauptkörper und den Schraubenkörper zu verschmelzen. Erstelle dann einen neuen Körper für die andere Seite. Dupliziere die Skizze der Drehung, verschiebe sie auf diesen Körper und erstelle den zweiten Körper für die Schrauben (das Spiegeln eines Körpers wird noch nicht unterstützt, so dass Sie den größten Teil davon neu ausführen müssen). Verschmelze dann auch diesen zweiten Körper mit dem Hauptkörper. Abschließend bringe eine große Verrundung an der Kante an, die durch die boolesche Verschmelzungsoperation erzeugt wurde. Die größte Verrundung, die ich erreichen konnte, war 4 mm.
<br clear="all"/>
</p>
<h2><span id="Aush.C3.B6hlung_des_Hauptk.C3.B6rpers"></span><span class="mw-headline" id="Aushöhlung_des_Hauptkörpers">Aushöhlung des Hauptkörpers</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-9.jpg"><img decoding="async" height="347" src="../File/HolderTop2-9.jpg" srcset="/images/thumb/c/c5/HolderTop2-9.jpg/450px-HolderTop2-9.jpg 1.5x, /images/c/c5/HolderTop2-9.jpg 2x" width="300"/></a><figcaption>Das erste Polster des ausgeschnittenen Körpers im Inneren des Hauptkörpers</figcaption></figure>
<p>Wir werden nun an der Innenseite des Halters arbeiten und ihn aushöhlen, um Platz für die Lager- und Dichtungsringe zu schaffen. Dabei müssen wir natürlich die 3 mm Bearbeitungszugabe berücksichtigen. Da dieses Tutorial die Multi-körpermethode lehrt, werden wir die Innengeometrie als separaten Körper erstellen und dann mit einer boolschen Operation aus dem Hauptkörper herausschneiden.
</p><p>Erstelle einen neuen Körper und mache ihn aktiv. Zuerst benötigen wir eine um 3 mm versetzte Bezugsebene innerhalb der Skelettfläche, die die Seite des Lagers zeigt. Dann dupliziere die Skizze des ersten Polsters des Hauptkörpers. Sie wird dem Hauptkörper hinzugefügt, also klicke mit der rechten Maustaste darauf und wähle, um sie in den neu erstellten Körper zu verschieben (diese Option ist nur im Kontextmenü verfügbar, wenn der PartDesign Arbeitsbereich aktiv ist). Bilde die Skizze auf die Bezugsebene ab (wenn die Skizze nach dem Zuordnen auf den Kopf gestellt wird, verschiebe die Bezugsebene auf die andere Seite des Lagers, neben die Stelle, an der sich die duplizierte Skizze befindet). Modifiziere die Skizze nun so, dass der Durchmesser 3 mm kleiner ist als der Außendurchmesser der Skelettgeometrie, die das Lager darstellt. Du musst nur die 5 mm Bemaßung entfernen, die Skizze innerhalb des Referenzkreises ziehen und eine neue 3 mm Bemaßung erstellen.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-10.jpg"><img decoding="async" height="218" src="../File/HolderTop2-10.jpg" srcset="/images/thumb/e/e8/HolderTop2-10.jpg/600px-HolderTop2-10.jpg 1.5x, /images/thumb/e/e8/HolderTop2-10.jpg/800px-HolderTop2-10.jpg 2x" width="400"/></a><figcaption>Der ausgeschnittene Körper im Inneren des Skelettkörpers</figcaption></figure>
<p>Als nächstes wollen wir zwei weitere Polster, um den Platz für die Dichtungsringe auszuhöhlen. Dupliziere die Skizze des ersten Polsters des ausgeschnittenen Körpers und ordne es der XZ Ebene zu. Bearbeite die Skizze und ersetze die externe Referenz durch den Außendurchmesser des Lagerdichtrings. Extrudiere diese Skizze bis zu einem Versatz von 3 mm von der Seite des Dichtungsrings. Wiederhole den gesamten Vorgang für den Dichtungsring auf der anderen Seite.
</p><p>Danach wollen wir zwei weitere Polster wie die letzten beiden erzeugen, um der Welle einen Freiraum (z.B. 3mm) innerhalb des Gehäuses zu geben.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-11.jpg"><img decoding="async" height="200" src="../File/HolderTop2-11.jpg" srcset="/images/thumb/a/a9/HolderTop2-11.jpg/600px-HolderTop2-11.jpg 1.5x, /images/thumb/a/a9/HolderTop2-11.jpg/800px-HolderTop2-11.jpg 2x" width="400"/></a><figcaption>Der komplette ausgeschnittene Körper (abzüglich unmöglicher Ausrundungen)</figcaption></figure>
<p>Jetzt müssen nur noch die ebenen Seitenflächen mit der gleichen neutralen Ebene wie der Hauptkörper mit dem Entwurf versehen und verrundet werden. Wende an allen Kanten eine allgemeine Verrundung von 3 mm an. Du wirst feststellen, dass es mehrere Kanten gibt, die nicht verrundet werden können... dies ist ein Defekt des zugrunde liegenden geometrischen Kerns, den FreeCAD verwendet.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-15.jpg"><img decoding="async" height="237" src="../File/HolderTop2-15.jpg" srcset="/images/thumb/d/d9/HolderTop2-15.jpg/600px-HolderTop2-15.jpg 1.5x, /images/thumb/d/d9/HolderTop2-15.jpg/800px-HolderTop2-15.jpg 2x" width="400"/></a><figcaption>Das fertige Rohteil des Halters (ohne spanende Bearbeitung)</figcaption></figure>
<p>Wir sind bereit, den Hauptkörper auszuhöhlen. Wähle ihn aus und wähle eine neue Boolesche Operation zu erstellen. Füge den ausgeschnittenen Körper dem Listenfenster hinzu und setze die Operation auf "Ausschneiden". Lege eine Verrundung von 3 mm auf die beiden Kanten, die sich aus dem Ausschneiden ergeben (auch hier bleiben einige Kanten übrig, die "unverrundet" sind). Das Ergebnis sollte wie auf dem Bild rechts aussehen.
</p><p>Das Rohteil ist nun fertiggestellt. So wird der Halter vor der Bearbeitung aussehen. Beachte, dass die Kante zwischen diesen beiden nicht verrundet werden kann, da die Form eine obere und eine untere Hälfte haben wird. Auch wenn du dieses Modell an eine Gießerei verschenkst, musst du darauf hinweisen, dass es die Abmessungen nach dem Gießen hat. Die Gießerei muss dann einen bestimmten Prozentsatz der Schrumpfung auf das Modell anwenden (das digitale Modell, das zur Herstellung der Form verwendet wird, muss größer gemacht werden, damit das Metall nach dem Gießen beim Abkühlen und Schrumpfen die richtige Größe hat).
<br clear="all"/>
</p>
<h2><span class="mw-headline" id="Spanende_Bearbeitung">Spanende Bearbeitung</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-17.jpg"><img decoding="async" height="472" src="../File/HolderTop2-17.jpg" srcset="/images/thumb/e/e3/HolderTop2-17.jpg/600px-HolderTop2-17.jpg 1.5x, /images/e/e3/HolderTop2-17.jpg 2x" width="400"/></a><figcaption>Skizze zum "Bohren" des Lochs für die Schrauben.</figcaption></figure>
<p>Um das Material für die Bearbeitung der Innenseite des Gehäuses zu entfernen, können wir sehr bequem den Skelettkörper selbst verwenden. Wenn du das nicht willst, weil dann das Skelett irgendwo tief im Baum versteckt wird, kannst du auch die Skizze des Skelett Umdrehungsformelements duplizieren und die Umdrehung in einem anderen Körper nachbilden. Dies ist jedoch nicht vollständig parametrisch, da die duplizierte Skizze unabhängig vom Original ist, so dass du an beiden arbeiten musst, wenn du eine Bemaßung änderst. Abhängige duplizierte Formelemente könnten in der Zukunft irgendwann unterstützt werden.
</p><p>Für den Rest der soaneneden Bearbeitung erzeuge einen neuen Körper. Der Boden des Gehäuses wird mit einem auf der XY Ebene skizzierten Polster bearbeitet, das sich nach unten erstreckt. Als nächstes skizziere eine Umdrehung, um ein Loch für die Schrauben herzustellen. Du musst auf der XZ Ebene skizzieren und diese drehen, damit du den Außendurchmesser des Skelettkörpers als externe Referenz wählen kannst. Der obere Teil der Skizze dient dazu, eine flache Stelle für den Kopf der Schraube zu bearbeiten. Er ist so bemessen, dass mindestens 5 mm Wandstärke in der Halterung verbleiben. Wenn dies nicht genug Platz für den Schraubenkopf bietet, kannst du die Bezugsebene nach oben verschieben. Natürlich kannst du diese Logik in das Skelett einbauen, was dem Leser als Übung überlassen bleibt!
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-18.jpg"><img decoding="async" height="293" src="../File/HolderTop2-18.jpg" srcset="/images/thumb/b/bf/HolderTop2-18.jpg/600px-HolderTop2-18.jpg 1.5x, /images/thumb/b/bf/HolderTop2-18.jpg/800px-HolderTop2-18.jpg 2x" width="400"/></a><figcaption>Der Bearbeitungskörper</figcaption></figure>
<p>Du kannst die Umdrehung auf der YZ Achse spiegeln. Das Bild rechts zeigt den "Bearbeitungs" Körper. Natürlich sind die meisten Abmessungen der Polster und Umdrehungen nicht wichtig, solange es viele Überlappungen gibt.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-19.jpg"><img decoding="async" height="263" src="../File/HolderTop2-19.jpg" srcset="/images/thumb/9/90/HolderTop2-19.jpg/600px-HolderTop2-19.jpg 1.5x, /images/thumb/9/90/HolderTop2-19.jpg/800px-HolderTop2-19.jpg 2x" width="400"/></a><figcaption>Der fertige Halter mit Bearbeitung</figcaption></figure>
<p>Erstelle schließlich eine boolesche Operation, um den bearbeitenden Körper aus dem Hauptkörper herauszuschneiden. Wenn du einen schönen visuellen Effekt wünschst, kannst du die bearbeiteten Flächen anders einfärben als den Rest des Werkstücks. Dies ist auch eine nützliche optische Rückmeldung, die dir anzeigt, ob du irgendwo vergessen hast, zu bearbeiten.
<br clear="all"/>
</p>
<h2><span class="mw-headline" id="Teil_Eins">Teil Eins</span></h2>
<p><a href="PartDesign_Bearingholder_Tutorial_I.html" title="PartDesign Bearingholder Tutorial I/de">PartDesign Lagergehäuse Tutorium I</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20241129212657
Cache expiry: 86400
Reduced expiry: false
Complications: [show‐toc, no‐toc‐conversion]
CPU time usage: 0.132 seconds
Real time usage: 0.678 seconds
Preprocessor visited node count: 103/1000000
Post‐expand include size: 1927/2097152 bytes
Template argument size: 663/2097152 bytes
Highest expansion depth: 3/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post‐expand size: 0/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%    3.108      1 -total
 34.31%    1.066      1 Template:TutorialInfo/de
 23.13%    0.719      1 Template:Page_in_progress
 18.18%    0.565      1 Template:VeryImportantMessage
 14.38%    0.447      1 Template:Clear
-->
<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:66356-0!canonical and timestamp 20241129212656 and revision id 1131220. Rendering was triggered because: api-parse
 -->
</div></div><script src="../script.js"></script>
