<link href="../site.css" rel="stylesheet" type="text/css"/><div class="mw-page-container"><h1 id="firstHeading" class="firstHeading mw-first-heading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial II/de</span></h1><?xml encoding="UTF-8"><div class="mw-content-ltr mw-parser-output" lang="de" dir="ltr"><div class="mw-pt-languages noprint navigation-not-searchable" lang="en" dir="ltr"><div class="mw-pt-languages-label">Other languages:</div><ul class="mw-pt-languages-list"><li><a href="../index.php?title=Special;Translate&amp;group=page-PartDesign+Bearingholder+Tutorial+II&amp;language=&amp;task=view.html" class="new" title="Start translation for this language" lang="" dir="ltr"></a></li>
<li><span class="mw-pt-languages-selected mw-pt-progress mw-pt-progress--complete" lang="de" dir="ltr">Deutsch</span></li>
<li><a href="../PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-languages-ui mw-pt-progress mw-pt-progress--complete" title="PartDesign Bearingholder Tutorial II (100% translated)" lang="en" dir="ltr">English</a></li>
<li><a href="../tr/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Bearingholder Tutorial II/tr (2% translated)" lang="tr" dir="ltr">T&uuml;rk&ccedil;e</a></li>
<li><a href="../es/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--med" title="PartDesign Soporte de rodamiento Tutorial II (17% translated)" lang="es" dir="ltr">espa&ntilde;ol</a></li>
<li><a href="../fr/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--high" title="PartDesign Tutoriel pour la conception d'un support de roulement (II) (93% translated)" lang="fr" dir="ltr">fran&ccedil;ais</a></li>
<li><a href="../it/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--high" title="Tutorial per creare un supporto per cuscinetto con PartDesign. Seconda parte. (93% translated)" lang="it" dir="ltr">italiano</a></li>
<li><a href="../pl/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--complete" title="Poradnik: Projekt cz&#281;&#347;ci, uchwyt &#322;o&#380;yska cze&#347;&#263; 2 (100% translated)" lang="pl" dir="ltr">polski</a></li>
<li><a href="../pt-br/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--low" title="Tutorial de Projeto de Mancais de Apoio II (2% translated)" lang="pt-BR" dir="ltr">portugu&ecirc;s do Brasil</a></li>
<li><a href="../ro/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--high" title="PartDesign Bearingholder Tutorial II (90% translated)" lang="ro" dir="ltr">rom&acirc;n&#259;</a></li>
<li><a href="../ru/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Bearingholder Tutorial II/ru (7% translated)" lang="ru" dir="ltr">&#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;</a></li></ul></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img src="../File/Freecad.svg" decoding="async" width="32" height="32" class="mw-file-element" data-file-width="48" data-file-height="48"></span></span> Anleitung
</td></tr>
<tr>
<th class="ctOdd">Thema
</th></tr>
<tr>
<td class="ctEven">Modellierung
</td></tr>
<tr>
<th class="ctOdd">Niveau
</th></tr>
<tr>
<td class="ctEven">Erfahrene Anwender
</td></tr>
<tr>
<th class="ctOdd">Bearbeitungszeit
</th></tr>
<tr>
<td class="ctEven"><i>Not provided</i>
</td></tr>
<tr>
<th class="ctOdd">Autoren
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">FreeCAD-Version
</th></tr>
<tr>
<td class="ctEven">0.19.23300 oder h&ouml;her
</td></tr>
<tr>
<th class="ctOdd">Beispieldateien
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Siehe auch
</th></tr>
<tr>
<td class="ctEven"><i>None</i>
</td></tr>
<tr>
<td class="ctToc"><br><meta property="mw:PageProp/toc">
</td></tr></tbody></table>
<p><span id="Purpose_in_Brief"></span>
</p>
<h2><span id="Verwendungszweck_in_K.C3.BCrze"></span><span class="mw-headline" id="Verwendungszweck_in_K&uuml;rze">Verwendungszweck in K&uuml;rze</span></h2>
<p>Der Zweck der Anleitung besteht darin, zwei verschiedene Arbeitsabl&auml;ufe zur Erstellung eines Gussteils mit Formschr&auml;gen und Verrundungen vorzustellen. Je nachdem, welches andere CAD-Programm bisher verwendet wurde, k&ouml;nnte das eine oder das andere vertraut sein. Als Arbeitsbeispiel werden wir ein einfaches Lagergeh&auml;use modellieren.
</p><p>Dies ist der zweite Teil der Anleitung. Es wird der so genannte "Mehrk&ouml;rper"-Arbeitsablauf verwendet, wobei das (einfachere) Oberteil des Geh&auml;uses als Beispiel dient.
</p><p>Zum Durcharbeiten dieser Anleitung muss der Arbeitsbereich PartDesign aktiviert werden.
</p><p><span typeof="mw:File"><a href="../index.php?title=HolderTop2-19.jpg&amp;filetimestamp=20130716184057&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-19.jpg" decoding="async" width="400" height="263" class="mw-file-element" data-file-width="1037" data-file-height="683"></a></span>
</p>
<p style="text-align:left; font-style:italic; max-width:800px; box-sizing:border-box; margin-block:1em; margin-inline:clamp(1em, 6vw, 2em); padding-inline:clamp(0.75em, 4vw, 2em); word-break:normal; overflow-wrap:break-word;">Anleitung Lagergeh&auml;use - Fertiggestelltes Lagergeh&auml;use (Oberteil)</p>
<p><span id="Design_data"></span>
</p>
<h2><span class="mw-headline" id="Konstruktionsdaten">Konstruktionsdaten</span></h2>
<p>Das Geh&auml;use sollte in der Lage sein, ein Lager mit einem Durchmesser von 90 mm und einer Breite von bis zu 33 mm aufzunehmen (z.B. DIN 630 Typ 2308 mit einem Innendurchmesser von 40 mm). Das Lager erfordert eine Schulterh&ouml;he von mindestens 4,5 mm im Halter (und auf der Welle). Der obere Teil des Geh&auml;uses wird mit zwei 12mm Schrauben an der Unterseite verschraubt. Der Kopf einer solchen Schraube ben&ouml;tigt einen Freiraum von mindestens 20 mm Durchmesser. Auf beiden Seiten des Lagers sollte eine Nut vorhanden sein, die einen Standard-Wellendichtring DIN 3760 aufnehmen kann: 38x55x7 oder 40x55x7 auf der einen Seite, 50x68x8 auf der anderen Seite.
</p><p>Das Geh&auml;use wird ein Sandguss mit einer Mindestwandst&auml;rke von 5 mm, einem Entformungswinkel von 2 Grad und einem minimalen Verrundungsradius von 3 mm sein.
</p><p><br clear="all">
</p><p><span id="Setting_up_the_skeleton_geometry"></span>
</p>
<h2><span class="mw-headline" id="Einrichten_der_Skelettgeometrie">Einrichten der Skelettgeometrie</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-2.png&amp;filetimestamp=20160718193124&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-2.png" decoding="async" width="400" height="149" class="mw-file-element" data-file-width="1260" data-file-height="468"></a><figcaption>Skizze der Skelettgeometrie</figcaption></figure>
<p>Erstelle im PartDesign Arbeitsbereich ein neues Teil. Benenne den standardm&auml;&szlig;ig erstellten K&ouml;rper in Skeleton um. Dieser K&ouml;rper ist wahrscheinlich bereits aktiviert, was du an der blauen Hintergrundfarbe im Formelementebaum erkennen kannst. Erstelle eine neue Skizze auf der YZ Ebene, die den Umriss der Welle, des Lagers und der Dichtungsringe enth&auml;lt. Nachdem du die Skizze fertiggestellt hast, erstelle daraus ein Rotations Formelement. Dieses Skelettformelement wird sp&auml;ter dazu verwendet, die reale Geometrie darauf zu beziehen. Das bedeutet, dass du, wenn du irgendwelche Bema&szlig;ungen &auml;ndern m&ouml;chtest, nur die Bema&szlig;ungen des Skelettformelements anpassen musst, und der Rest des Teils wird entsprechend aktualisiert.
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-2-1.jpg&amp;filetimestamp=20130711190937&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-2-1.jpg" decoding="async" width="400" height="260" class="mw-file-element" data-file-width="1058" data-file-height="687"></a><figcaption>Die Skelettgeometrie</figcaption></figure>
<p><br clear="all">
</p><p><span id="The_main_body"></span>
</p>
<h2><span id="Der_Hauptk.C3.B6rper"></span><span class="mw-headline" id="Der_Hauptk&ouml;rper">Der Hauptk&ouml;rper</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-3.jpg&amp;filetimestamp=20130711184543&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-3.jpg" decoding="async" width="400" height="298" class="mw-file-element" data-file-width="1040" data-file-height="774"></a><figcaption>Skizze des ersten Polsters</figcaption></figure>
<p>Erstelle einen neuen K&ouml;rper und mache ihn aktiv. Die Skizze f&uuml;r den ersten Block ist rechts abgebildet. Er wird auf einer Bezugsebene mit einem Versatz von 5 mm (Wandst&auml;rke) von der Skelettfl&auml;che platziert, die die Seite eines der tragenden Dichtungsringe markiert. Da alle wichtigen Ma&szlig;e vom Skelett abgenommen werden, gibt es nur drei Ma&szlig;e: Die Bearbeitungszugabe (3 mm) an der Basis als Versatz zur XY Ebene, die 5 mm Wanddicke vom Au&szlig;endurchmesser des Skeletts und der Entformungswinkel von zwei Grad. Zwei erzeugen die 5mm Bema&szlig;ung, du musst zuerst den Au&szlig;enkreis (Radius 45mm) der Skelettgeometrie als Au&szlig;engeometrie im Skizzierer ausw&auml;hlen und dann eine tangential zu diesem Kreis und in einem Winkel von zwei Grad gebundene Konstruktionslinie einf&uuml;gen.
</p><p>Du fragst dich wahrscheinlich, warum sich am unteren Ende jedes Bogens dieses kleine gerade Segment befindet. Dieses Segment sorgt daf&uuml;r, dass auf den B&ouml;gen ein Entformungswinkel von 2 Grad entsteht. Das mag nach viel Arbeit f&uuml;r einen sehr kleinen Nutzen aussehen, aber viele CAD Programme (und vielleicht eines Tages auch FreeCAD) haben Werkzeuge, die ein Volumenmodell in verschiedenen Farben hervorheben und dir sofort alle Fl&auml;chen anzeigt, bei denen der Entformungswinkel nicht korrekt ist. Du willst nicht, dass das mit deinem Modell passiert, besonders nachdem du viele Verrundungen angebracht hast!
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-4.jpg&amp;filetimestamp=20130711185009&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-4.jpg" decoding="async" width="400" height="279" class="mw-file-element" data-file-width="1117" data-file-height="780"></a><figcaption>Das erste Polster</figcaption></figure>
<p>Wenn du die Skizze angefertigt hast (was wegen der 2 Grad Tangentiallinien etwas knifflig ist), erstelle daraus ein Polster, das sich bis zur anderen Seite der Skelettgeometrie erstreckt, wiederum mit einem Versatz von 5 mm zur Seitenfl&auml;che. du brauchst diesmal keine Bezugsebene zu erzeugen, der "bis zur Fl&auml;che" Modus des Polster Dialogs bietet die Eingabe eines Versatzes an.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-5.jpg&amp;filetimestamp=20130711190315&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-5.jpg" decoding="async" width="400" height="313" class="mw-file-element" data-file-width="899" data-file-height="703"></a><figcaption>Skizze f&uuml;r Polsterausschnitt</figcaption></figure>
<p>Als N&auml;chstes werden wir an beiden Enden des Polsters etwas Material wegschneiden, da es f&uuml;r Gussteile immer ideal ist, eine m&ouml;glichst gleichm&auml;&szlig;ige Wandst&auml;rke zu haben. Erstelle eine Skizze auf jeder der Stirnseiten des Polsters und bema&szlig;e sie um 5 mm versetzt zu dem Kreis, der den Lagerdichtring darstellt (Radius 27,5 mm auf der einen Seite und 34 mm auf der anderen). Erstelle f&uuml;r das untere Liniensegment der Skizze eine weitere externe Geometrie vom Polster und binde diese an das Polster. So hat die Skizze nur ein einziges Ma&szlig;, die 5 mm Wandst&auml;rke (die Ma&szlig;e 150 mm und 75 mm sind nicht wichtig, solange sie gro&szlig; genug sind, um sicherzustellen, dass alles weggeschnitten wird).
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-6.jpg&amp;filetimestamp=20130711190430&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-6.jpg" decoding="async" width="400" height="277" class="mw-file-element" data-file-width="1063" data-file-height="736"></a><figcaption>Das Polster mit Ausschnitten zur Erzielung einer gleichm&auml;&szlig;igen Wandst&auml;rke</figcaption></figure>
<p>Erstelle mit der von dir erstellten Skizze eine Tasche und erweitere diese auf die Fl&auml;che der Skelettgeometrie, die das Lager darstellt, minus 5 mm Versatz f&uuml;r die Wanddicke. F&uuml;r die zweite Tasche kannst du die Option "Ausgew&auml;hltes Objekt duplizieren" aus dem Men&uuml; Bearbeiten verwenden, um die bereits erstellte Skizze zu duplizieren (w&auml;hle, dass abh&auml;ngige Objekte nicht dupliziert werden sollen, wenn die Frage auftaucht). W&auml;hle dann die Fl&auml;che aus, auf die du diese Skizze verschieben m&ouml;chtest, und weise FreeCAD an, die Skizze auf diese Fl&auml;che abzubilden (dies ist ein Punkt im Men&uuml; "PartDesign"). Nachdem du die zweite Tasche erstellt hast, kannst du das Ergebnis von unten betrachten, um zu pr&uuml;fen, ob du eine einheitliche Wandst&auml;rke von 5 mm um die Kontur der Skelettgeometrie herum haben.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-7.jpg&amp;filetimestamp=20130711192218&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-7.jpg" decoding="async" width="400" height="226" class="mw-file-element" data-file-width="1085" data-file-height="614"></a><figcaption>Neutrale Ebene f&uuml;r die Anwendung des Entwurfs</figcaption></figure>
<p>Jetzt ist es an der Zeit, Entwurf und Verrundungen zu erstellen. Das Entwurfsformelement erfordert eine neutrale Ebene, was bedeutet, dass die Geometrie, die von dieser Ebene geschnitten wird, an ihrem Platz bleibt, w&auml;hrend der Rest der Fl&auml;che um den Entformungswinkel geneigt wird. Die Verwendung der Unterseite des Polsters f&uuml;r diesen Zweck ist keine gute Idee, da die Wandst&auml;rke im oberen Teil des Halters weniger als 5 mm betragen w&uuml;rde. Wir erstellen also zu diesem Zweck eine Bezugsebene, die um etwa 35 mm vom XY versetzt ist. Aktiviere den Skelettk&ouml;rper und erzeuge  die Ebene dort, denn wir werden sie brauchen, um den Entwurf auch auf andere K&ouml;rper anzuwenden.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-8.jpg&amp;filetimestamp=20130711192240&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-8.jpg" decoding="async" width="400" height="233" class="mw-file-element" data-file-width="1106" data-file-height="644"></a><figcaption>Erster K&ouml;rper mit Entwurf und Verrundungen</figcaption></figure>
<p>Das Bild rechts zeigt den fertigen ersten K&ouml;rper mit Entwurf und applizierten Verrundungen. Beachte, dass die &auml;usseren (konkaven) Kanten einen gr&ouml;sseren Verrundungsradius von 5mm haben, wiederum mit dem Ziel, eine gleichm&auml;ssigere Wandst&auml;rke zu erzeugen (mehr als 5mm ist nicht m&ouml;glich, da dann nach der Bearbeitung der Innenseite des Halters die Wandst&auml;rke weniger als 5mm betragen w&uuml;rde).
<br clear="all">
</p><p><span id="Adding_the_bodies_for_the_bolts"></span>
</p>
<h2><span id="Hinzuf.C3.BCgen_der_K.C3.B6rper_f.C3.BCr_die_Schrauben"></span><span class="mw-headline" id="Hinzuf&uuml;gen_der_K&ouml;rper_f&uuml;r_die_Schrauben">Hinzuf&uuml;gen der K&ouml;rper f&uuml;r die Schrauben</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-13.jpg&amp;filetimestamp=20130716175052&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-13.jpg" decoding="async" width="400" height="333" class="mw-file-element" data-file-width="730" data-file-height="607"></a><figcaption>Die Skizze f&uuml;r den K&ouml;rper f&uuml;r die Schrauben</figcaption></figure>
<p>Die Schrauben ben&ouml;tigen zwei zylindrische K&ouml;rper auf beiden Seiten des Hauptk&ouml;rpers. Am besten ist es, den 2 Grad Entformungswinkel in die Skizze aufzunehmen. Ich habe versucht, einen Zylinder zu drehen und sp&auml;ter einen Entwurf anzuwenden, aber nach dem Spiegeln passierten seltsame Dinge, und ich konnte keine Verrundungen anbringen, weil die Oberfl&auml;che irgendwie verzogen war.
</p><p>Die Skizze ist so bema&szlig;t, dass die Rotationsachse 12 mm Abstand zum Au&szlig;endurchmesser des Skelettk&ouml;rpers hat, 7 mm f&uuml;r den Radius der Bohrung plus 5 mm f&uuml;r die Wanddicke. Um ein vollparametrisches Teil zu erhalten, ist es eine gute Idee, dem Skelett eine Ebene etwa 25 mm &uuml;ber der XY Ebene hinzuzuf&uuml;gen, um die Oberseite der Zylinder zu markieren. Da dies bearbeitet werden soll, wird die Skizze 3mm dar&uuml;ber bema&szlig;t.
</p><p><br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-14.jpg&amp;filetimestamp=20130715192541&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-14.jpg" decoding="async" width="400" height="244" class="mw-file-element" data-file-width="987" data-file-height="601"></a><figcaption>Der K&ouml;rper f&uuml;r die Schrauben</figcaption></figure>
<p>Erstelle aus der Skizze eine Drehung und bringe an der Oberseite eine Verrundung von 4 mm an. Das bedeutet, dass nach dem Wegfr&auml;sen von 3 mm ein leichter Radius verbleibt, der hilft, eine scharfe Kante zu vermeiden, an der sich jemand beim Anziehen der Schraube in die Hand schneiden k&ouml;nnte.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-16.jpg&amp;filetimestamp=20130715192912&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-16.jpg" decoding="async" width="400" height="261" class="mw-file-element" data-file-width="868" data-file-height="566"></a><figcaption>Der Hauptk&ouml;rper mit den beiden K&ouml;rpern f&uuml;r die Schrauben</figcaption></figure>
<p>Erstelle ein boolesches Formelement, um den Hauptk&ouml;rper und den Schraubenk&ouml;rper zu verschmelzen. Erstelle dann einen neuen K&ouml;rper f&uuml;r die andere Seite. Dupliziere die Skizze der Drehung, verschiebe sie auf diesen K&ouml;rper und erstelle den zweiten K&ouml;rper f&uuml;r die Schrauben (das Spiegeln eines K&ouml;rpers wird noch nicht unterst&uuml;tzt, so dass Sie den gr&ouml;&szlig;ten Teil davon neu ausf&uuml;hren m&uuml;ssen). Verschmelze dann auch diesen zweiten K&ouml;rper mit dem Hauptk&ouml;rper. Abschlie&szlig;end bringe eine gro&szlig;e Verrundung an der Kante an, die durch die boolesche Verschmelzungsoperation erzeugt wurde. Die gr&ouml;&szlig;te Verrundung, die ich erreichen konnte, war 4 mm.
<br clear="all">
</p><p><span id="Hollowing_out_the_main_body"></span>
</p>
<h2><span id="Aush.C3.B6hlung_des_Hauptk.C3.B6rpers"></span><span class="mw-headline" id="Aush&ouml;hlung_des_Hauptk&ouml;rpers">Aush&ouml;hlung des Hauptk&ouml;rpers</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-9.jpg&amp;filetimestamp=20130714182319&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-9.jpg" decoding="async" width="300" height="347" class="mw-file-element" data-file-width="477" data-file-height="551"></a><figcaption>Das erste Polster des ausgeschnittenen K&ouml;rpers im Inneren des Hauptk&ouml;rpers</figcaption></figure>
<p>Wir werden nun an der Innenseite des Halters arbeiten und ihn aush&ouml;hlen, um Platz f&uuml;r die Lager- und Dichtungsringe zu schaffen. Dabei m&uuml;ssen wir nat&uuml;rlich die 3 mm Bearbeitungszugabe ber&uuml;cksichtigen. Da dieses Tutorial die Multi-k&ouml;rpermethode lehrt, werden wir die Innengeometrie als separaten K&ouml;rper erstellen und dann mit einer boolschen Operation aus dem Hauptk&ouml;rper herausschneiden.
</p><p>Erstelle einen neuen K&ouml;rper und mache ihn aktiv. Zuerst ben&ouml;tigen wir eine um 3 mm versetzte Bezugsebene innerhalb der Skelettfl&auml;che, die die Seite des Lagers zeigt. Dann dupliziere die Skizze des ersten Polsters des Hauptk&ouml;rpers. Sie wird dem Hauptk&ouml;rper hinzugef&uuml;gt, also klicke mit der rechten Maustaste darauf und w&auml;hle, um sie in den neu erstellten K&ouml;rper zu verschieben (diese Option ist nur im Kontextmen&uuml; verf&uuml;gbar, wenn der PartDesign Arbeitsbereich aktiv ist). Bilde die Skizze auf die Bezugsebene ab (wenn die Skizze nach dem Zuordnen auf den Kopf gestellt wird, verschiebe die Bezugsebene auf die andere Seite des Lagers, neben die Stelle, an der sich die duplizierte Skizze befindet). Modifiziere die Skizze nun so, dass der Durchmesser 3 mm kleiner ist als der Au&szlig;endurchmesser der Skelettgeometrie, die das Lager darstellt. Du musst nur die 5 mm Bema&szlig;ung entfernen, die Skizze innerhalb des Referenzkreises ziehen und eine neue 3 mm Bema&szlig;ung erstellen.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-10.jpg&amp;filetimestamp=20130714183706&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-10.jpg" decoding="async" width="400" height="218" class="mw-file-element" data-file-width="1013" data-file-height="551"></a><figcaption>Der ausgeschnittene K&ouml;rper im Inneren des Skelettk&ouml;rpers</figcaption></figure>
<p>Als n&auml;chstes wollen wir zwei weitere Polster, um den Platz f&uuml;r die Dichtungsringe auszuh&ouml;hlen. Dupliziere die Skizze des ersten Polsters des ausgeschnittenen K&ouml;rpers und ordne es der XZ Ebene zu. Bearbeite die Skizze und ersetze die externe Referenz durch den Au&szlig;endurchmesser des Lagerdichtrings. Extrudiere diese Skizze bis zu einem Versatz von 3 mm von der Seite des Dichtungsrings. Wiederhole den gesamten Vorgang f&uuml;r den Dichtungsring auf der anderen Seite.
</p><p>Danach wollen wir zwei weitere Polster wie die letzten beiden erzeugen, um der Welle einen Freiraum (z.B. 3mm) innerhalb des Geh&auml;uses zu geben.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-11.jpg&amp;filetimestamp=20130714184941&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-11.jpg" decoding="async" width="400" height="200" class="mw-file-element" data-file-width="1055" data-file-height="527"></a><figcaption>Der komplette ausgeschnittene K&ouml;rper (abz&uuml;glich unm&ouml;glicher Ausrundungen)</figcaption></figure>
<p>Jetzt m&uuml;ssen nur noch die ebenen Seitenfl&auml;chen mit der gleichen neutralen Ebene wie der Hauptk&ouml;rper mit dem Entwurf versehen und verrundet werden. Wende an allen Kanten eine allgemeine Verrundung von 3 mm an. Du wirst feststellen, dass es mehrere Kanten gibt, die nicht verrundet werden k&ouml;nnen... dies ist ein Defekt des zugrunde liegenden geometrischen Kerns, den FreeCAD verwendet.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-15.jpg&amp;filetimestamp=20130715192602&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-15.jpg" decoding="async" width="400" height="237" class="mw-file-element" data-file-width="974" data-file-height="576"></a><figcaption>Das fertige Rohteil des Halters (ohne spanende Bearbeitung)</figcaption></figure>
<p>Wir sind bereit, den Hauptk&ouml;rper auszuh&ouml;hlen. W&auml;hle ihn aus und w&auml;hle eine neue Boolesche Operation zu erstellen. F&uuml;ge den ausgeschnittenen K&ouml;rper dem Listenfenster hinzu und setze die Operation auf "Ausschneiden". Lege eine Verrundung von 3 mm auf die beiden Kanten, die sich aus dem Ausschneiden ergeben (auch hier bleiben einige Kanten &uuml;brig, die "unverrundet" sind). Das Ergebnis sollte wie auf dem Bild rechts aussehen.
</p><p>Das Rohteil ist nun fertiggestellt. So wird der Halter vor der Bearbeitung aussehen. Beachte, dass die Kante zwischen diesen beiden nicht verrundet werden kann, da die Form eine obere und eine untere H&auml;lfte haben wird. Auch wenn du dieses Modell an eine Gie&szlig;erei verschenkst, musst du darauf hinweisen, dass es die Abmessungen nach dem Gie&szlig;en hat. Die Gie&szlig;erei muss dann einen bestimmten Prozentsatz der Schrumpfung auf das Modell anwenden (das digitale Modell, das zur Herstellung der Form verwendet wird, muss gr&ouml;&szlig;er gemacht werden, damit das Metall nach dem Gie&szlig;en beim Abk&uuml;hlen und Schrumpfen die richtige Gr&ouml;&szlig;e hat).
<br clear="all">
</p><p><span id="Machining"></span>
</p>
<h2><span class="mw-headline" id="Spanende_Bearbeitung">Spanende Bearbeitung</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-17.jpg&amp;filetimestamp=20130716182636&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-17.jpg" decoding="async" width="400" height="472" class="mw-file-element" data-file-width="663" data-file-height="782"></a><figcaption>Skizze zum "Bohren" des Lochs f&uuml;r die Schrauben.</figcaption></figure>
<p>Um das Material f&uuml;r die Bearbeitung der Innenseite des Geh&auml;uses zu entfernen, k&ouml;nnen wir sehr bequem den Skelettk&ouml;rper selbst verwenden. Wenn du das nicht willst, weil dann das Skelett irgendwo tief im Baum versteckt wird, kannst du auch die Skizze des Skelett Umdrehungsformelements duplizieren und die Umdrehung in einem anderen K&ouml;rper nachbilden. Dies ist jedoch nicht vollst&auml;ndig parametrisch, da die duplizierte Skizze unabh&auml;ngig vom Original ist, so dass du an beiden arbeiten musst, wenn du eine Bema&szlig;ung &auml;nderst. Abh&auml;ngige duplizierte Formelemente k&ouml;nnten in der Zukunft irgendwann unterst&uuml;tzt werden.
</p><p>F&uuml;r den Rest der soaneneden Bearbeitung erzeuge einen neuen K&ouml;rper. Der Boden des Geh&auml;uses wird mit einem auf der XY Ebene skizzierten Polster bearbeitet, das sich nach unten erstreckt. Als n&auml;chstes skizziere eine Umdrehung, um ein Loch f&uuml;r die Schrauben herzustellen. Du musst auf der XZ Ebene skizzieren und diese drehen, damit du den Au&szlig;endurchmesser des Skelettk&ouml;rpers als externe Referenz w&auml;hlen kannst. Der obere Teil der Skizze dient dazu, eine flache Stelle f&uuml;r den Kopf der Schraube zu bearbeiten. Er ist so bemessen, dass mindestens 5 mm Wandst&auml;rke in der Halterung verbleiben. Wenn dies nicht genug Platz f&uuml;r den Schraubenkopf bietet, kannst du die Bezugsebene nach oben verschieben. Nat&uuml;rlich kannst du diese Logik in das Skelett einbauen, was dem Leser als &Uuml;bung &uuml;berlassen bleibt!
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-18.jpg&amp;filetimestamp=20130716182656&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-18.jpg" decoding="async" width="400" height="293" class="mw-file-element" data-file-width="985" data-file-height="722"></a><figcaption>Der Bearbeitungsk&ouml;rper</figcaption></figure>
<p>Du kannst die Umdrehung auf der YZ Achse spiegeln. Das Bild rechts zeigt den "Bearbeitungs" K&ouml;rper. Nat&uuml;rlich sind die meisten Abmessungen der Polster und Umdrehungen nicht wichtig, solange es viele &Uuml;berlappungen gibt.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-19.jpg&amp;filetimestamp=20130716184057&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-19.jpg" decoding="async" width="400" height="263" class="mw-file-element" data-file-width="1037" data-file-height="683"></a><figcaption>Der fertige Halter mit Bearbeitung</figcaption></figure>
<p>Erstelle schlie&szlig;lich eine boolesche Operation, um den bearbeitenden K&ouml;rper aus dem Hauptk&ouml;rper herauszuschneiden. Wenn du einen sch&ouml;nen visuellen Effekt w&uuml;nschst, kannst du die bearbeiteten Fl&auml;chen anders einf&auml;rben als den Rest des Werkst&uuml;cks. Dies ist auch eine n&uuml;tzliche optische R&uuml;ckmeldung, die dir anzeigt, ob du irgendwo vergessen hast, zu bearbeiten.
<br clear="all">
</p>
<h2><span class="mw-headline" id="Teil_Eins">Teil Eins</span></h2>
<p><a href="../de/PartDesign_Bearingholder_Tutorial_I.html" title="PartDesign Bearingholder Tutorial I/de">PartDesign Lagergeh&auml;use Tutorium I</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20251003190004
Cache expiry: 86400
Reduced expiry: false
Complications: [show&#8208;toc]
CPU time usage: 0.115 seconds
Real time usage: 0.153 seconds
Preprocessor visited node count: 108/1000000
Post&#8208;expand include size: 1558/2097152 bytes
Template argument size: 127/2097152 bytes
Highest expansion depth: 4/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post&#8208;expand size: 2468/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%    6.849      1 -total
 57.45%    3.935      1 Template:TutorialInfo/de
 22.27%    1.525      1 Template:Caption
 15.46%    1.059      1 Template:Clear
-->

<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:66356-0!canonical and timestamp 20251003190004 and revision id 1654681. Rendering was triggered because: api-parse
 -->
</div>
</div><script src="../site.js"></script>