<link href="../site.css" rel="stylesheet" type="text/css"/><div class="mw-page-container"><h1 id="firstHeading" class="firstHeading mw-first-heading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial I/es</span></h1><?xml encoding="UTF-8"><div class="mw-content-ltr mw-parser-output" lang="es" dir="ltr"><div class="mw-pt-languages noprint navigation-not-searchable" lang="en" dir="ltr"><div class="mw-pt-languages-label">Other languages:</div><ul class="mw-pt-languages-list"><li><a href="../index.php?title=Special;Translate&amp;group=page-PartDesign+Bearingholder+Tutorial+I&amp;language=&amp;task=view.html" class="new" title="Start translation for this language" lang="" dir="ltr"></a></li>
<li><a href="../de/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--complete" title="PartDesign Lagergeh&auml;use Tutorium I (100% translated)" lang="de" dir="ltr">Deutsch</a></li>
<li><a href="../PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-languages-ui mw-pt-progress mw-pt-progress--complete" title="PartDesign Bearingholder Tutorial I (100% translated)" lang="en" dir="ltr">English</a></li>
<li><a href="../tr/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Bearingholder Tutorial I/tr (2% translated)" lang="tr" dir="ltr">T&uuml;rk&ccedil;e</a></li>
<li><span class="mw-pt-languages-selected mw-pt-progress mw-pt-progress--low" lang="es" dir="ltr">espa&ntilde;ol</span></li>
<li><a href="../fr/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--complete" title="PartDesign Tutoriel pour la conception d'un support de roulement (I) (100% translated)" lang="fr" dir="ltr">fran&ccedil;ais</a></li>
<li><a href="../it/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--complete" title="Prima parte del tutorial per creare un supporto per cuscinetto con PartDesign (100% translated)" lang="it" dir="ltr">italiano</a></li>
<li><a href="../pl/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--complete" title="Poradnik: Projekt cz&#281;&#347;ci, uchwyt &#322;o&#380;yska cze&#347;&#263; 1 (100% translated)" lang="pl" dir="ltr">polski</a></li>
<li><a href="../pt-br/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--low" title="Tutorial de Projeto de Mancais de Apoio I (2% translated)" lang="pt-BR" dir="ltr">portugu&ecirc;s do Brasil</a></li>
<li><a href="../ro/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--high" title="PartDesign Bearingholder Tutorial I (92% translated)" lang="ro" dir="ltr">rom&acirc;n&#259;</a></li>
<li><a href="../ru/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Bearingholder Tutorial I/ru (2% translated)" lang="ru" dir="ltr">&#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;</a></li></ul></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img src="../File/Freecad.svg" decoding="async" width="32" height="32" class="mw-file-element" data-file-width="48" data-file-height="48"></span></span> Tutorial
</td></tr>
<tr>
<th class="ctOdd">Topic
</th></tr>
<tr>
<td class="ctEven">Modeling
</td></tr>
<tr>
<th class="ctOdd">Level
</th></tr>
<tr>
<td class="ctEven">Experienced User
</td></tr>
<tr>
<th class="ctOdd">Time to complete
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Authors
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">FreeCAD version
</th></tr>
<tr>
<td class="ctEven">0.19.23300 or higher
</td></tr>
<tr>
<th class="ctOdd">Example files
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">See also
</th></tr>
<tr>
<td class="ctEven"><i>None</i>
</td></tr>
<tr>
<td class="ctToc"><br><meta property="mw:PageProp/toc">
</td></tr></tbody></table>
<h2><span class="mw-headline" id="Purpose_in_Brief">Purpose in Brief</span></h2>
<p>The purpose of the tutorial is to introduce you to two different work flows for creating a cast part with drafts and fillets. Depending on what other CAD programs you have been using, one or the other might be familiar to you. As a working example we will be modeling a simple bearing holder.
</p><p>Esta es la primera parte del tutorial. Utilizar&aacute; lo que podr&iacute;a llamarse el flujo de trabajo de "un solo cuerpo", usando la parte superior (m&aacute;s simple) del soporte como ejemplo.
</p><p>Obviamente, para seguir este tutorial debes activar la mesa de trabajo de PartDesign.
</p><p><span typeof="mw:File"><a href="../index.php?title=HolderTop1-1.jpg&amp;filetimestamp=20130609182657&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-1.jpg" decoding="async" width="400" height="277" class="mw-file-element" data-file-width="600" data-file-height="416"></a></span>
</p>
<p style="text-align:left; font-style:italic; max-width:800px; box-sizing:border-box; margin-block:1em; margin-inline:clamp(1em, 6vw, 2em); padding-inline:clamp(0.75em, 4vw, 2em); word-break:normal; overflow-wrap:break-word;">Bearing Holder Tutorial - Finished bearing holder (top)</p>
<p><span id="Design_data"></span>
</p>
<h2><span id="Datos_de_dise.C3.B1o"></span><span class="mw-headline" id="Datos_de_dise&ntilde;o">Datos de dise&ntilde;o</span></h2>
<p>The holder should be able to hold a diameter 90mm bearing with a width of up to 33mm (e.g. DIN 630 type 2308). The bearing requires a shoulder height of at least 4.5mm in the holder (and on the shaft). The top part of the holder will be bolted to the bottom with two 12mm bolts. There should be a groove on both sides of the bearing able to hold a standard shaft sealing ring DIN 3760: 38x55x7 or 40x55x7 on one side, 50x68x8 on the other side.
</p><p>The holder will be a sand cast with a minimum wall thickness of 5mm, a draft angle of 2 degrees, and a minimum fillet radius of 3mm.
</p><p><br clear="all">
</p>
<h2><span class="mw-headline" id="Setting_up_the_skeleton_geometry">Setting up the skeleton geometry</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-2.jpg&amp;filetimestamp=20130610181806&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-2.jpg" decoding="async" width="400" height="284" class="mw-file-element" data-file-width="560" data-file-height="397"></a><figcaption>Bearing holder with the two most important skeleton planes</figcaption></figure>
<p>The idea of skeleton geometry is to capture the basic design dimensions in a single datum feature (e.g. a plane or an axis). When the design dimension changes, all that needs to be done is to change the skeleton feature. If the model is well built, then all its feature will recompute to reflect the design change. This reduces the danger that in a complex model, where the basic design dimensions are used in multiple places, you forget to change it somewhere.
</p><p>The alternative to skeleton geometry is to have a table of the basic design dimensions that assign a symbolic name to each dimension, and then use the symbolic name wherever the dimensions is required to build the model. FreeCAD does not allow this approach yet.
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-3.jpg&amp;filetimestamp=20130610183102&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-3.jpg" decoding="async" width="400" height="277" class="mw-file-element" data-file-width="700" data-file-height="485"></a><figcaption>Base planes and all datum planes</figcaption></figure>
<p>For the case of the bearing holder, the two most important design dimensions are the distance between the bolts (which limits the size of the bearing that can be used) and the height of the bolt heads. The dimensions chosen are
</p>
<ul><li>Distance between bolts: Radius of bearing (45) + wall thickness (5) plus radius of hole for bolt (7) = 57mm, so the vertical plane will be 57mm offset from the YZ-plane.  To create this datum plane, select the YZ-plane and then choose to create a new datum plane. Enter the offset in the dialog that opens up</li>
<li>Height of bolt heads: This was chosen as an offset of 28mm from the XZ-plane</li></ul>
<p>For convenience, two further datum planes can be created to reflect the amount of material that must be cut away from the sides of the bearing holder. They are offset +22 and -22 from the XY-plane.
</p><p>It is advisable to give clear names to the skeleton geometry. Most of the time, you will want to turn off visibility for datum planes because they clutter up the screen, and if the planes have self-explanatory names you can just pick them by name instead of from the screen.
<br clear="all">
</p>
<h2><span class="mw-headline" id="The_solid_geometry">The solid geometry</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-4.jpg&amp;filetimestamp=20130612185214&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-4.jpg" decoding="async" width="400" height="244" class="mw-file-element" data-file-width="1126" data-file-height="686"></a><figcaption>Sketch of the first pad</figcaption></figure>
<p>Now its time to start creating some real geometry. The sketch for the first pad is shown on the right. It is placed on the XY-plane. There are just three dimensions: The inner radius (22.5mm), the machining allowance (3mm) at the base as an offset to the XZ-plane and the distance from the datum plane representing the bolt axis (7mm). This means that if you later move the datum plane, the pad will automatically adjust its outer radius. Remember that before you can use the datum plane for dimensioning, you need to introduce it as external geometry to the sketcher.
</p><p>You are probably wondering why there is a small straight segment at the bottom of each arc. This segment ensures that there will be a draft angle of 2 degrees on the arcs. This might look like a lot of work for a very small benefit, but many CAD programs (and maybe FreeCAD one day) have tools that highlight a solid model in different colours and immediately show you all faces where the draft angle is not correct. You don't want that to happen to your model, especially after putting on a lot of fillets!
</p><p>When you have done the sketch (which is a bit tricky because of the 2 degree tangential lines), just pad it symmetrically to the sketch plane with a length of 62mm: 34mm for the bearing, 2x 9mm for the sealing rings, 2x 5mm for the wall thickness.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-5.jpg&amp;filetimestamp=20130612190636&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-5.jpg" decoding="async" width="400" height="229" class="mw-file-element" data-file-width="1048" data-file-height="601"></a><figcaption>Sketch of the cut-away at the side of the pad</figcaption></figure>
<p>Next we want to cut away some material where the sealing rings are, because their outer diameter is much less than the bearing's. The easiest way to create the sketches is to select the sketch of the pad and then choose "Duplicate selection" from the edit menu. You can then remap the sketch to the side of the pad, and modify it as shown in the picture.
</p><p>The only two important dimensions in the sketch are 3mm of machining allowance at the bottom, and a inner diameter of 78mm: 68mm for the outer diameter of the sealing ring + 2x 5mm wall thickness. Since the sealing ring on the other side will only have a diameter of 55mm, the cut-out can be 65mm here.
</p><p>After you have created the sketch, pocket it up to the datum plane marking the bearing side plus 5mm wall thickness. If you ever want to modify the holder to be able to hold wider bearings, all you have to do is to change the dimension of these datum planes, and the cut-out depth will follow along.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-6.jpg&amp;filetimestamp=20130612193209&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-6.jpg" decoding="async" width="400" height="254" class="mw-file-element" data-file-width="1106" data-file-height="703"></a><figcaption>Sketch of the cut-away inside the pad</figcaption></figure>
<p>To reduce the amount of machining required, we also want to cut away some material inside the holder. Again, duplicating the sketch of the first pad is convenient. It doesn't even have to be remapped. Again, the only important dimensions are the machining allowance (3mm) and the outer diameters: 84mm for the place where the bearing will be (90mm - 2x machining allowance), 49mm for the smaller sealing ring (55mm - 2x 3mm) and 62mm for the larger sealing ring.
</p><p>After creating the sketches, pocket them: Symetrically 28mm for the bearing cut-out (34mm - 2x machining allowance) and one-sided 23mm for the cut-outs for the sealing rings: 34mm / 2 for half the bearing width + 9mm for the sealing rings - 3mm machining allowance. 
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-7.jpg&amp;filetimestamp=20130612193845&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-7.jpg" decoding="async" width="400" height="273" class="mw-file-element" data-file-width="1050" data-file-height="717"></a><figcaption>Main geometry of the holder top</figcaption></figure>
<p>Your part should now look like the picture on the right. Note how the different cut-aways combine to create an almost uniform wall thickness, which will make the casting easier and less liable to have pores.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-8.jpg&amp;filetimestamp=20130612194752&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-8.jpg" decoding="async" width="400" height="276" class="mw-file-element" data-file-width="1123" data-file-height="774"></a><figcaption>Sketch with draft where the bolts will be</figcaption></figure>
<p>Now all that remains is to create some material for the bolts to go through. You might be tempted to sketch these as a circle and then pad them, but this will head you for trouble when you try to put the draft onto them later (I assume that is a weakness of OpenCascade). So to circumvent the problems, it is better to create a sketch with the draft angle included and then rotate it through 360 degrees.
</p><p>Here again the skeleton planes come in useful. You will need the bolt axis plane and the bolt head plane as external geometry. Then, create a straight line for the rotation axis and make sure it is constrained to the bolt axis plane reference. Toggle it to be construction geometry. Then, sketch the rest of the contour. The important dimensions are the machining allowance at the top and bottom and the radius of 12mm: 7mm for the hole radius + 5mm wall thickness.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-9.jpg&amp;filetimestamp=20130612195344&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-9.jpg" decoding="async" width="400" height="273" class="mw-file-element" data-file-width="1116" data-file-height="763"></a><figcaption>Finished geometry of the holder top (without draft and fillets)</figcaption></figure>
<p>Create a revolution feature from the sketch and then mirror it on the YZ-plane. This is all the solid geometry we need to model. The rest is draft and fillets.
<br clear="all">
</p>
<h2><span class="mw-headline" id="Applying_draft_to_the_side_faces">Applying draft to the side faces</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-10.jpg&amp;filetimestamp=20130616085052&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-10.jpg" decoding="async" width="400" height="254" class="mw-file-element" data-file-width="1104" data-file-height="700"></a><figcaption>The neutral plane for creating drafts</figcaption></figure>
<p>The next step is to apply drafts on all faces. Its important to consider the location of the neutral plane, that is, the plane which the face is "rotated" around. If we choose as neutral plane the bottom of the holder, then we will have a problem with the wall thickness in the top part of the holder. Therefore, we create a datum plane at an offset of 40mm from the XZ plane as a compromise between the top of the holder becoming to thin and the bottom becoming to wide.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-11.jpg&amp;filetimestamp=20130616085807&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-11.jpg" decoding="async" width="400" height="170" class="mw-file-element" data-file-width="1035" data-file-height="441"></a><figcaption>Applying draft to the side faces of the holder</figcaption></figure>
<p>To put draft on a face, select this face and create the draft feature. You can then select more faces to apply the draft on. If you have a large part, it is advisable to draft only one face at a time. This means that if you change the geometry and a draft fails, only this one feature will fail, whereas if you put all faces in one draft feature, then the whole feature might fail because of one face failing. For a small part like the bearing holder, its sufficient to create two draft features: One for the four outside faces, and one for the inside faces.
</p><p>The dialog will force you to select a neutral plane before completing. You can leave the pull direction empty, in this case it will be normal to the neutral plane. Don't forget to set the draft angle to 2 degrees.
<br clear="all">
</p>
<h2><span class="mw-headline" id="Filleting_the_holder">Filleting the holder</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-13.jpg&amp;filetimestamp=20130616091631&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-13.jpg" decoding="async" width="400" height="275" class="mw-file-element" data-file-width="965" data-file-height="663"></a><figcaption>Fillet where the bolts will go</figcaption></figure>
<p>We can now fillet the part. The picture shows the first set of fillets. Start with the small circular fillets and make them 4mm radius. Even though 3mm would be enough as per specification of the part, a radius of 4mm means that after machining 1mm of the fillet is left, reducing the sharp edge produced by the machining. The large fillets are 6mm radius to help spread the force from the bolts into the rest of the part. It would be nice to make this radius even larger, but unfortunately OpenCascade can't handle overlapping fillets yet.
</p><p>As with drafts, in a complex part you should fillet only one edge at a time to avoid unnecessary failures if the base geometry changes.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-12.jpg&amp;filetimestamp=20130616091416&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-12.jpg" decoding="async" width="400" height="259" class="mw-file-element" data-file-width="1036" data-file-height="671"></a><figcaption>Filleting the outside of the holder</figcaption></figure>
<p>The rest of the fillets are simply 3mm radius. Looking at the picture on the right, the two highlighted fillets could actually be filleted with 5mm to achieve a more uniform wall thickness for the casting. After machining, the minimum wall thickness of 5mm would still be maintained. But again the fact that OpenCascade can't handle overlapping fillets prevents us from doing this for the inner of the two highlighted fillets.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-14.jpg&amp;filetimestamp=20130616092602&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-14.jpg" decoding="async" width="400" height="331" class="mw-file-element" data-file-width="833" data-file-height="689"></a><figcaption>Filleting the inside of the holder - problematic edge</figcaption></figure>
<p>Filleting the inside of the part presents us with a difficulty that cannot be solved with the current tools in the PartDesign workbench. The highlighted edge cannot be filleted at all, again because the rounds would overlap. This could be worked around by creating a sweep instead of a fillet, except that sweeps are not implemented in PartDesign yet. For the time being, we are forced to leave the edge as it is.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-15.jpg&amp;filetimestamp=20130616093234&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-15.jpg" decoding="async" width="400" height="279" class="mw-file-element" data-file-width="1051" data-file-height="734"></a><figcaption>The filleted part (except for the impossible edge)</figcaption></figure>
<p>The picture on the right shows the finished part in the state it will be before machining (except for the one edge that is impossible to fillet). You will notice that one edge that runs around the whole part has been left unfilleted on purpose. This is the edge where the bottom and the top of the mould meet. Here, no fillet is possible (and none is required anyway).
<br clear="all">
</p>
<h2><span class="mw-headline" id="Machining">Machining</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-16.jpg&amp;filetimestamp=20130616094809&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-16.jpg" decoding="async" width="400" height="201" class="mw-file-element" data-file-width="1098" data-file-height="552"></a><figcaption>Machining the top and bottom of the holder</figcaption></figure>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-17.jpg&amp;filetimestamp=20130616115136&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-17.jpg" decoding="async" width="400" height="295" class="mw-file-element" data-file-width="958" data-file-height="706"></a><figcaption>Machining the inside of the bearing holder</figcaption></figure>
<p>Now we can cut away the material that will be machined off the raw cast part. This is very easy with the skeleton geometry defined. The idea is to create all machining features (Pockets and Grooves) using datum features only. This means they will be totally independent of the solid geometry of the bearing holder, which gives us some big advantages:
</p>
<ul><li>No matter how you change the solid geometry, the features for the machining can never fail.</li>
<li>You can create the machining geometry before finalizing the solid, which gives you useful visual feedback.</li>
<li>If you move the skeleton datum planes, then both the solid geometry and the machining will adapt automatically.</li>
<li>If you make a mistake in your solid geometry, the machining will still be in the correct position, and very likely the mistake will become glaringly obvious (e.g. a wall thickness becoming 2mm instead of 5mm). Whereas if you reference the machining to the solid geometry, it will adapt to the error in the solid and e.g. maintain the 5mm wall thickness, just in the same wrong location as the solid is.</li></ul>
<p>Before starting on the machining geometry, I like to place a datum point in the tree and name it something like "Machining_starts_here". This is useful if you want to switch between the raw and the machined state of the part because you can see at a glance where to move the insert point to get the raw state.
</p><p>To machine the bottom of the holder, just sketch a large rectangle on the XZ plane and pocket it. For the top, sketch a circle on the datum plane defining the bolt head location, and then mirror the pocket on the YZ plane. In the same way, create a pocket for the hole which the bolt will go through and mirror it. To machine the inside of the holder, create a sketch on the YZ plane and groove it.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-1.jpg&amp;filetimestamp=20130609182657&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-1.jpg" decoding="async" width="400" height="277" class="mw-file-element" data-file-width="600" data-file-height="416"></a><figcaption>Finished part</figcaption></figure>
<p>Once you have done the machining, you can have a nice visual effect by colouring all the machined faces so that you can see at one glance which parts are raw casting and which are machined after casting.
</p><p><br clear="all">
</p>
<h2><span class="mw-headline" id="Final_notes">Final notes</span></h2>
<p>We have modelled the bearing holder top with the dimensions it will have after casting. To create the casting mould, you need to apply shrinkage to your part because after casting, when the hot metal cools down, it will shrink by a few percent (depending on the material). Usually it is best to leave the application of shrinkage to the foundry making the part because they have the required special knowledge. They should also tell you if your part has problematic areas, e.g. very thick walls suddenly joining to very thin sections without a properly tapered section between them.
</p>
<h2><span class="mw-headline" id="Part_Two">Part Two</span></h2>
<p><a href="../PartDesign_Bearingholder_Tutorial_II.html" title="PartDesign Bearingholder Tutorial II">PartDesign Bearingholder Tutorial II</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20251220223857
Cache expiry: 86400
Reduced expiry: false
Complications: [show&#8208;toc]
CPU time usage: 0.067 seconds
Real time usage: 0.086 seconds
Preprocessor visited node count: 104/1000000
Post&#8208;expand include size: 1504/2097152 bytes
Template argument size: 107/2097152 bytes
Highest expansion depth: 4/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post&#8208;expand size: 2454/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%    7.822      1 -total
 49.66%    3.884      1 Template:Caption
 23.51%    1.839      1 Template:TutorialInfo
 22.33%    1.747      1 Template:Clear
-->

<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:53128-0!canonical and timestamp 20251220223857 and revision id 1654616. Rendering was triggered because: edit-page
 -->
</div>
</div><script src="../site.js"></script>