<link href="../site.css" rel="stylesheet" type="text/css"/><div class="mw-page-container"><h1 id="firstHeading" class="firstHeading mw-first-heading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial II/es</span></h1><?xml encoding="UTF-8"><div class="mw-parser-output"><div id="itsfree" style="text-align:center; background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">
<figure class="mw-halign-left" typeof="mw:File"><span><img src="https://upload.wikimedia.org/wikipedia/commons/d/d5/Under_construction_icon-blue.svg" decoding="async" width="45" height="38"></span><figcaption></figcaption></figure> This documentation is a work in progress. Please don't mark it as translatable since it will change in the next hours and days.
</div><div style="clear:both"></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img src="../File/Freecad.svg" decoding="async" width="32" height="32"></span></span> Tutorial
</td></tr>
<tr>
<th class="ctOdd">Topic
</th></tr>
<tr>
<td class="ctEven">Modeling
</td></tr>
<tr>
<th class="ctOdd">Level
</th></tr>
<tr>
<td class="ctEven">Experienced User
</td></tr>
<tr>
<th class="ctOdd">Time to complete
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Authors
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">FreeCAD version
</th></tr>
<tr>
<td class="ctEven">0.19.23300 or higher
</td></tr>
<tr>
<th class="ctOdd">Example files
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">See also
</th></tr>
<tr>
<td class="ctEven"><i>None</i>
</td></tr>
<tr>
<td class="ctToc"><br><meta property="mw:PageProp/toc">
</td></tr></tbody></table>
<div id="itsfree" style="text-align:center;color:black;background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">Este tutorial fue escrito originalmente para una versi&oacute;n de desarrollo ya obsoleta de FreeCAD. A partir de abril de 2016 estas caracter&iacute;sticas han sido integradas en la versi&oacute;n de pre-desarrollo 0.17 disponible <a rel="nofollow" class="external text" href="https://github.com/FreeCAD/FreeCAD/releases/tag/0.17_pre">aqu&iacute;</a>.
<p><br>
</p>
Tenga en cuenta que esta versi&oacute;n de FreeCAD est&aacute; todav&iacute;a en una fase temprana de desarrollo. Adem&aacute;s, este tutorial puede necesitar ser actualizado. Si desea participar en su revisi&oacute;n y actualizaci&oacute;n, por favor, env&iacute;e un mensaje a la secci&oacute;n Wiki del <a rel="nofollow" class="external text" href="http://forum.freecadweb.org">foro</a>.</div>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-19.jpg&amp;filetimestamp=20130716184057&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-19.jpg" decoding="async" width="400" height="263"></a><figcaption>Tutorial de soporte de rodamiento - Soporte de rodamiento terminado (arriba)</figcaption></figure>
<p><strike>
As the warning at the top of the page already indicates, this <b>tutorial will NOT WORK unless you compile a special highly experimental branch from FreeCAD source code</b> and is an introductory tutorial to modeling with the PartDesign workbench in FreeCAD <b>using Datum planes which are a feature that does not yet exist in most FreeCAD versions</b>. 
</strike>
</p>
<h2><span class="mw-headline" id="Purpose_in_Brief">Purpose in Brief</span></h2>
<p>The purpose of the tutorial is to introduce you to two different work flows for creating a cast part with drafts and fillets. Depending on what other CAD programs you have been using, one or the other might be familiar to you. As a working example we will be modeling a simple bearing holder.
</p><p>Esta es la segunda parte del tutorial. Utilizar&aacute; lo que podr&iacute;a llamarse el flujo de trabajo de "cuerpo m&uacute;ltiple", usando la parte superior (m&aacute;s simple) del soporte como ejemplo.
</p><p>Obviamente, para seguir este tutorial debes activar la mesa de trabajo de PartDesign.
</p><p><strike>Puedes encontrar mi versi&oacute;n de la parte creada en este tutorial [<a rel="nofollow" class="external text" href="http://ubuntuone.com/39PTZ3Y3LUnmZzpZQPcJT4">aqu&iacute;</a>]</strike> <i>El archivo ya no est&aacute; disponible, se proporcionar&aacute; uno nuevo en una fecha posterior</i>.
<br clear="all">
</p><p><span id="Design_data"></span>
</p>
<h2><span id="Datos_de_dise.C3.B1o"></span><span class="mw-headline" id="Datos_de_dise&ntilde;o">Datos de dise&ntilde;o</span></h2>
<p>The holder should be able to hold a diameter 90mm bearing with a width of up to 33mm (e.g. DIN 630 type 2308 which has an inside diameter of 40mm). The bearing requires a shoulder height of at least 4.5mm in the holder (and on the shaft). The top part of the holder will be bolted to the bottom with two 12mm bolts. The head of such a bolt will require at least 20mm diameter free space. There should be a groove on both sides of the bearing able to hold a standard shaft sealing ring DIN 3760: 38x55x7 or 40x55x7 on one side, 50x68x8 on the other side.
</p><p>El soporte ser&aacute; un molde de arena con un espesor m&iacute;nimo de pared de 5 mm, un &aacute;ngulo de tiro de 2 grados, y un radio m&iacute;nimo de filete de 3 mm.
</p><p><br clear="all">
</p><p><span id="Setting_up_the_skeleton_geometry"></span>
</p>
<h2><span id="Estableciendo_la_geometr.C3.ADa_del_esqueleto"></span><span class="mw-headline" id="Estableciendo_la_geometr&iacute;a_del_esqueleto">Estableciendo la geometr&iacute;a del esqueleto</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-2.png&amp;filetimestamp=20160718193124&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-2.png" decoding="async" width="400" height="149"></a><figcaption>Sketch of the skeleton geometry</figcaption></figure>
<p>Create a new part in the PartDesign workbench. Rename the Body that is created by default to Skeleton. This Body is probably activated already, which you can see by the blue background colour in the feature tree. Create a new sketch on the YZ plane containing the outline of the shaft, bearing and sealing rings. After finishing the sketch, make a revolution feature from it. This skeleton feature will later be used to reference the real geometry to it. This means that if you want to change any dimensions, all you need to do is adjust the skeleton feature's dimensions and the rest of the part will update accordingly.
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-2-1.jpg&amp;filetimestamp=20130711190937&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-2-1.jpg" decoding="async" width="400" height="260"></a><figcaption>The skeleton geometry</figcaption></figure>
<p><br clear="all">
</p>
<h2><span class="mw-headline" id="The_main_body">The main body</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-3.jpg&amp;filetimestamp=20130711184543&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-3.jpg" decoding="async" width="400" height="298"></a><figcaption>Sketch of the first Pad</figcaption></figure>
<p>Create a new body and make it active. The sketch for the first pad is shown on the right. It is placed on a datum plane with an offset of 5mm (wall thickness) from the skeleton face marking the side of one of the bearing sealing rings. Because all the important dimensions are taken from the skeleton, there are just three dimensions: The machining allowance (3mm) at the base as an offset to the XY-plane, the 5mm wall thickness from the outer diameter of the skeleton, and the two degrees draft angle. Two create the 5mm dimension, you first need to select the outer circle (radius 45mm) of the skeleton geometry as external geometry in the sketcher, and then put in a construction line constrained tangential to this circle and at an angle of two degrees.
</p><p>You are probably wondering why there is this small straight segment at the bottom of each arc. This segment ensures that there will be a draft angle of 2 degrees on the arcs. This might look like a lot of work for a very small benefit, but many CAD programs (and maybe FreeCAD one day) have tools that highlight a solid model in different colours and immediately show you all faces where the draft angle is not correct. You don't want that to happen to your model, especially after putting on a lot of fillets!
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-4.jpg&amp;filetimestamp=20130711185009&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-4.jpg" decoding="async" width="400" height="279"></a><figcaption>The first Pad</figcaption></figure>
<p>When you have done the sketch (which is a bit tricky because of the 2 degree tangential lines), create a Pad from it extending up to the other side of the skeleton geometry, again with a 5mm offset to the side face. You don't need to create a datum plane this time, the "up to face" mode of the Pad dialog offers to input an offset.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-5.jpg&amp;filetimestamp=20130711190315&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-5.jpg" decoding="async" width="400" height="313"></a><figcaption>Sketch for Pad cut-out</figcaption></figure>
<p>Next, we will cut away some material on both ends of the Pad because it is always ideal for cast parts to have as uniform a wall thickness as possible. Create a sketch on each of the end faces of the Pad and dimension it at 5mm offset from the circle representing the bearing sealing ring (radius 27.5mm on one side and 34mm on the other). For the bottom line segment of the sketch, create another external geometry from the Pad and constrain to this. Thus the sketch has only a single dimension, the 5mm wall thickness (the 150mm and 75mm dimensions are not important as long as they are large enough to ensure that everything is cut away).
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-6.jpg&amp;filetimestamp=20130711190430&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-6.jpg" decoding="async" width="400" height="277"></a><figcaption>The Pad with cut-outs to achieve uniform wall thickness</figcaption></figure>
<p>Use the sketch you created to make a Pocket and extend it to the face of the skeleton geometry that represents the bearing, minus 5mm offset for the wall thickness. For the second Pocket, you can use the option "Duplicate selected object" from the Edit menu to duplicate the sketch you already made (choose not to duplicate dependend objects if the question pops up). Then, select the face you want to move this sketch to, and tell FreeCAD to map the sketch to this face (this is an item on the PartDesign menu). After creating the second Pocket, you can look at the result from the bottom to check that you have a uniform wall thickness of 5mm around the contour of the skeleton geometry.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-7.jpg&amp;filetimestamp=20130711192218&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-7.jpg" decoding="async" width="400" height="226"></a><figcaption>Neutral plane for applying draft</figcaption></figure>
<p>Now it's time to create draft and fillets. The draft feature requires a neutral plane, meaning that the geometry that is cut by this plane will remain in its place, while the rest of the face is tilted at the draft angle. Using the bottom of the Pad for this purpose for this is not a good idea, because the wall thickness in the top part of the holder would become less than 5mm. So we create a datum plane offset about 35mm from the XY for this purpose. Activate the Skeleton body and create the plane there, because we will need it for applying draft to other bodies, too.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-8.jpg&amp;filetimestamp=20130711192240&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-8.jpg" decoding="async" width="400" height="233"></a><figcaption>First body with draft and fillets</figcaption></figure>
<p>The picture on the right shows the finished first body with draft and fillets applied. Note that the outer (concave) edges have a larger fillet radius of 5mm, again with the purpose of creating a more uniform wall thickness (more than 5mm is not possible because then after machining the inside of the holder the wall thickness would become less than 5mm).
<br clear="all">
</p>
<h2><span class="mw-headline" id="Adding_the_bodies_for_the_bolts">Adding the bodies for the bolts</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-13.jpg&amp;filetimestamp=20130716175052&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-13.jpg" decoding="async" width="400" height="333"></a><figcaption>The sketch for the body for the bolts</figcaption></figure>
<p>The bolts need two cylindrical bodies on both sides of the main Body. It is best to include the 2 degree draft angle in the sketch. I tried revolving a cylinder and later applying a draft, but weird things happened after mirroring it and I couldn't put fillets on it because the surface was warped somehow.
</p><p>The sketch is dimensioned so that the rotation axis is 12mm distance to the outer diameter of the skeleton Body, 7mm for the radius of the hole plus 5mm for the wall thickness. For the sake of having a fully parametric part, it is a good idea to add a plane to the Skeleton about 25mm above the XY-plane to mark the top of the cylinders. Since this will be machined, the sketch is dimensioned 3mm above it.
</p><p><br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-14.jpg&amp;filetimestamp=20130715192541&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-14.jpg" decoding="async" width="400" height="244"></a><figcaption>The body for the bolts</figcaption></figure>
<p>Create a revolution from the sketch and apply a fillet of 4mm to the top. This means that after machining away 3mm, a slight radius will remain which helps to avoid a sharp edge where someone could cut their hand when tightening the bolt.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-16.jpg&amp;filetimestamp=20130715192912&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-16.jpg" decoding="async" width="400" height="261"></a><figcaption>The main body with the two bodies for the bolts</figcaption></figure>
<p>Create a boolean feature to fuse the main Body and the bolt body. Then create a new body for the other side. Duplicate the sketch of the revolution, move it to this body and create the second body for the bolts (mirroring a Body is not supported yet so you need to redo most of it). Then fuse this second body into the main Body as well. Finally, apply a large fillet on the edge created by the boolean fuse operation. The largest I could get was 4mm.
<br clear="all">
</p>
<h2><span class="mw-headline" id="Hollowing_out_the_main_body">Hollowing out the main body</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-9.jpg&amp;filetimestamp=20130714182319&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-9.jpg" decoding="async" width="300" height="347"></a><figcaption>The first Pad of the cut-out body inside the main body</figcaption></figure>
<p>We will now work on the inside of the holder and hollow it out to make space for the bearing and sealing rings. When doing this of course we need to keep in mind the 3mm machining allowance. Since this tutorial teaches the multi-body method, we will create the inside geometry as a separate body and then cut it out of the main body with a boolean operation.
</p><p>Create a new body and make it active. First, we need a datum plane offset 3mm inside the skeleton face that shows the side of the bearing. Then, duplicate the sketch of the first Pad of the main body. It will be added to the main body, so right-click on it and choose to move it to the newly created body (this option is only available in the context menu if the PartDesign workbench is active). Map the sketch onto the datum plane (if the sketch turns upside-down after mapping, move the datum plane to the other side of the bearing, next to where the duplicated sketch is located). Now, modify the sketch so that the diameter is 3mm less than the outer diameter of the skeleton geometry that represents the bearing. All you need to do is remove the 5mm dimension, drag the sketch inside the reference circle, and create a new 3mm dimension.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-10.jpg&amp;filetimestamp=20130714183706&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-10.jpg" decoding="async" width="400" height="218"></a><figcaption>The cut-out body inside the skeleton body</figcaption></figure>
<p>Next we want two more Pads to hollow out the place for the sealing rings. Duplicate the sketch of the first pad of the cut-out Body and map it to the XZ-plane. Edit the sketch and replace the external reference with the outer diameter of the bearing sealing ring. Extrude this sketch to an offset of 3mm of the side of the sealing ring. Repeat the whole process for the sealing ring on the other side.
</p><p>After this we want to create two more Pads like the last two to give the shaft a clearance (e.g. 3mm) inside the holder.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-11.jpg&amp;filetimestamp=20130714184941&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-11.jpg" decoding="async" width="400" height="200"></a><figcaption>The complete cut-out body (minus impossible fillets)</figcaption></figure>
<p>Now all that remains is to apply draft to the planar side faces, using the same neutral plane as for the main body, and filleting. Apply a general fillet of 3mm to all edges. You will notice that there are several edges that cannot be filleted... this is a defect of the underlying geometric kernel which FreeCAD uses.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-15.jpg&amp;filetimestamp=20130715192602&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-15.jpg" decoding="async" width="400" height="237"></a><figcaption>The completed raw part of the holder (without machining)</figcaption></figure>
<p>We are ready to hollow out the main body. Select it and choose to create a new Boolean operation. Add the cut-out body to the list window and set the operation to "Cut". Put a 3mm fillet on the two edges resulting from the cut-out operation (again some edges remain that are "unfilletable"). The result should look like the picture on the right.
</p><p>The raw part is now completed. This is what the holder will look like before machining. Note that since the mold will have a top and bottom half, the edge between these two cannot be filleted. Also, if you give away this model to a foundry make sure to point out that it has the dimensions after casting. The foundry will then have to apply a certain percentage of shrinkage to the model (making the digital model used to manufacture the mold larger so that when the metal cools down and shrinks after casting it will have the right size).
<br clear="all">
</p>
<h2><span class="mw-headline" id="Machining">Machining</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-17.jpg&amp;filetimestamp=20130716182636&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-17.jpg" decoding="async" width="400" height="472"></a><figcaption>Sketch to "drill" the hole for the bolts</figcaption></figure>
<p>To take away the material for machining the inside of the holder, very conveniently we can use the Skeleton Body itself. If you don't want that because then the skeleton gets hidden somewhere deep in the tree, you can also duplicate the sketch of the skeleton Revolution feature and re-create the revolution in another body. This is not completely parametric, though, because the duplicated sketch is independent of the original, so you will have to work on both if you change a dimension. Dependent duplicated features might be supported in the future sometime.
</p><p>For the rest of the machining, create a new Body. The bottom of the holder will be machined by a Pad sketched on the XY-plane extending downwards. Next, sketch a revolution to make a hole for the bolts. You will need to sketch on the XZ-plane and revolve it so that you can choose the outer diameter of the skeleton Body as an external reference. The top part of the sketch will serve to machine a flat place for the head of the bolt. It is dimensioned to leave at least 5mm wall thickness in the holder. If this does not give enough space for the bolt head then you can move the datum plane upwards. Of course, you could put this logic into the Skeleton, which is left as an exercise to the reader!
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-18.jpg&amp;filetimestamp=20130716182656&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-18.jpg" decoding="async" width="400" height="293"></a><figcaption>The machining Body</figcaption></figure>
<p>You can mirror the revolution on the YZ-axis. The picture on the right shows the "machining" Body. Of course, most of the dimensions of the Pads and Revolutions are not important as long as there is plenty of overlap.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-19.jpg&amp;filetimestamp=20130716184057&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-19.jpg" decoding="async" width="400" height="263"></a><figcaption>The finished Holder with machining</figcaption></figure>
<p>Finally, create a boolean operation to cut the machining Body out of the main Body. If you want a nice visual effect, you can colour the machined surfaces differently from the rest of the part. This is also a useful optical feedback showing you whether you forgot to machine somewhere.
<br clear="all">
</p>
<h2><span class="mw-headline" id="Part_One">Part One</span></h2>
<p><a href="../PartDesign_Bearingholder_Tutorial_I.html" title="PartDesign Bearingholder Tutorial I">PartDesign Bearingholder Tutorial I</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20250622010116
Cache expiry: 86400
Reduced expiry: false
Complications: [show&#8208;toc, no&#8208;toc&#8208;conversion]
CPU time usage: 0.214 seconds
Real time usage: 0.826 seconds
Preprocessor visited node count: 107/1000000
Post&#8208;expand include size: 1873/2097152 bytes
Template argument size: 632/2097152 bytes
Highest expansion depth: 3/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post&#8208;expand size: 0/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%   18.328      1 -total
 29.96%    5.491      1 Template:Page_in_progress
 26.05%    4.775      1 Template:VeryImportantMessage
 23.07%    4.228      1 Template:TutorialInfo
 19.12%    3.504      1 Template:Clear
-->

<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:53130-0!canonical and timestamp 20250622010115 and revision id 1595271. Rendering was triggered because: api-parse
 -->
</div>
</div><script src="../site.js"></script>