<link href="../site.css" rel="stylesheet" type="text/css"/><div class="mw-page-container"><h1 id="firstHeading" class="firstHeading mw-first-heading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial I/it</span></h1><?xml encoding="UTF-8"><div class="mw-content-ltr mw-parser-output" lang="it" dir="ltr"><div class="mw-pt-languages noprint navigation-not-searchable" lang="en" dir="ltr"><div class="mw-pt-languages-label">Other languages:</div><ul class="mw-pt-languages-list"><li><a href="../index.php?title=Special;Translate&amp;group=page-PartDesign+Bearingholder+Tutorial+I&amp;language=&amp;task=view.html" class="new" title="Start translation for this language" lang="" dir="ltr"></a></li>
<li><a href="../de/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--complete" title="PartDesign Lagergeh&auml;use Tutorium I (100% translated)" lang="de" dir="ltr">Deutsch</a></li>
<li><a href="../PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-languages-ui mw-pt-progress mw-pt-progress--complete" title="PartDesign Bearingholder Tutorial I (100% translated)" lang="en" dir="ltr">English</a></li>
<li><a href="../tr/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Bearingholder Tutorial I/tr (2% translated)" lang="tr" dir="ltr">T&uuml;rk&ccedil;e</a></li>
<li><a href="../es/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Soporte de rodamiento Tutorial I (8% translated)" lang="es" dir="ltr">espa&ntilde;ol</a></li>
<li><a href="../fr/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--complete" title="PartDesign Tutoriel pour la conception d'un support de roulement (I) (100% translated)" lang="fr" dir="ltr">fran&ccedil;ais</a></li>
<li><span class="mw-pt-languages-selected mw-pt-progress mw-pt-progress--complete" lang="it" dir="ltr">italiano</span></li>
<li><a href="../pl/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--complete" title="Poradnik: Projekt cz&#281;&#347;ci, uchwyt &#322;o&#380;yska cze&#347;&#263; 1 (100% translated)" lang="pl" dir="ltr">polski</a></li>
<li><a href="../pt-br/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--low" title="Tutorial de Projeto de Mancais de Apoio I (2% translated)" lang="pt-BR" dir="ltr">portugu&ecirc;s do Brasil</a></li>
<li><a href="../ro/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--high" title="PartDesign Bearingholder Tutorial I (92% translated)" lang="ro" dir="ltr">rom&acirc;n&#259;</a></li>
<li><a href="../ru/PartDesign_Bearingholder_Tutorial_I.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Bearingholder Tutorial I/ru (2% translated)" lang="ru" dir="ltr">&#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;</a></li></ul></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img src="../File/Freecad.svg" decoding="async" width="32" height="32" class="mw-file-element" data-file-width="48" data-file-height="48"></span></span> Tutorial
</td></tr>
<tr>
<th class="ctOdd">Argomento
</th></tr>
<tr>
<td class="ctEven">Modellazione
</td></tr>
<tr>
<th class="ctOdd">Livello di difficolt&agrave;
</th></tr>
<tr>
<td class="ctEven">Utente esperto
</td></tr>
<tr>
<th class="ctOdd">Tempo di esecuzione
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Autori
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">Versione di FreeCAD
</th></tr>
<tr>
<td class="ctEven">0.19.23300 o superiore
</td></tr>
<tr>
<th class="ctOdd">Files di esempio
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Vedere anche
</th></tr>
<tr>
<td class="ctEven"><i>Nessuno</i>
</td></tr>
<tr>
<td class="ctToc"><br><meta property="mw:PageProp/toc">
</td></tr></tbody></table>
<p><span id="Purpose_in_Brief"></span>
</p>
<h2><span class="mw-headline" id="Scopo_in_breve">Scopo in breve</span></h2>
<p>Lo scopo di questo tutorial &egrave; di presentare due diversi flussi di lavoro per la creazione di un pezzo fuso con sformi e raccordi. A seconda dei programmi CAD che si &egrave; utilizzato, si potrebbe avere familiarit&agrave; con uno o con l'altro. Come esempio pratico, modelleremo un semplice supporto per cuscinetto.
</p><p>Questa &egrave; la prima parte del tutorial. Usa il flusso di lavoro che pu&ograve; essere chiamato del "corpo unico", in questo esempio si utilizza solamente la parte superiore del supporto.
</p><p>Ovviamente, per seguire questo tutorial &egrave; necessario attivare l'ambiente PartDesign.
</p><p><span typeof="mw:File"><a href="../index.php?title=HolderTop1-1.jpg&amp;filetimestamp=20130609182657&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-1.jpg" decoding="async" width="400" height="277" class="mw-file-element" data-file-width="600" data-file-height="416"></a></span>
</p>
<p style="text-align:left; font-style:italic; max-width:800px; box-sizing:border-box; margin-block:1em; margin-inline:clamp(1em, 6vw, 2em); padding-inline:clamp(0.75em, 4vw, 2em); word-break:normal; overflow-wrap:break-word;">Tutorial del supporto di un cuscinetto - Supporto del cuscinetto finito (parte superiore)</p>
<p><span id="Design_data"></span>
</p>
<h2><span class="mw-headline" id="Dati_di_progetto">Dati di progetto</span></h2>
<p>Il supporto deve essere in grado di contenere un cuscinetto di 90 mm di diametro con una larghezza fino a 33 mm (ad esempio, DIN 630 tipo 2308). Il cuscinetto richiede una spalla alta almeno 4,5 mm nel supporto (e sull'albero). La parte superiore del supporto &egrave; imbullonata al fondo con due bulloni di 12 mm. A fianco del cuscinetto ci deve essere una scanalatura su entrambi i lati capace di contenere un anello di tenuta standard sull'albero DIN 3760: 38x55x7 o 40x55x7 su un lato e 50x68x8 sull'altro lato.
</p><p>Il supporto sar&agrave; prodotto con un getto in sabbia con uno spessore minimo della parete di 5 mm, un angolo di sforno con di 2 gradi e un raggio di raccordo minimo di 3 mm .
</p>
<h2><span class="mw-headline" id="Impostazione_della_geometria_di_scheletro">Impostazione della geometria di scheletro</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-2.jpg&amp;filetimestamp=20130610181806&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-2.jpg" decoding="async" width="400" height="284" class="mw-file-element" data-file-width="560" data-file-height="397"></a><figcaption>Supporto per cuscinetto con i due pi&ugrave; importanti piani dello scheletro</figcaption></figure>
<p>La geometria scheletro serve per catturare le dimensioni su cui si basa la progettazione in una singola funzione di riferimento (ad esempio un piano o un asse). In questo modo, quando si vuole variare le dimensioni del progetto, tutto ci&ograve; che si deve fare &egrave; di cambiare le funzioni dello scheletro. Se il modello &egrave; ben costruito, allora tutte le sue funzioni sono ricalcolate e riflettono le modifiche apportate al progetto. Questo riduce il pericolo che in un modello complesso, in cui le dimensioni di base del progetto sono utilizzate in pi&ugrave; posti, si dimentichi di cambiarle da qualche parte.
</p><p>L'alternativa alla geometria scheletro &egrave; quella di avere una tabella delle dimensioni di base del progetto che assegna un nome simbolico ad ogni dimensione e poi utilizzare il nome simbolico ovunque sono richieste le dimensioni per costruire il modello. FreeCAD non permette ancora questo approccio.
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-3.jpg&amp;filetimestamp=20130610183102&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-3.jpg" decoding="async" width="400" height="277" class="mw-file-element" data-file-width="700" data-file-height="485"></a><figcaption>Piani di base e tutti i piani di Riferimento</figcaption></figure>
<p>Nel caso del supporto del cuscinetto, le due dimensioni di progettazione pi&ugrave; importanti sono la distanza tra i bulloni (che limita la grandezza del cuscinetto che pu&ograve; essere utilizzato) e l'altezza delle teste dei bulloni. Le dimensioni scelte sono
</p>
<ul><li>Distanza tra i bulloni: raggio del cuscinetto (45) + spessore parete (5) + raggio del foro per il bullone (7) = 57 mm, per cui il piano verticale sar&agrave; scostato (offset) di 57 mm dal piano YZ. Per creare questo piano di riferimento, selezionare il piano YZ e poi scegliere di creare un nuovo piano di riferimento. Inserire l'offset nella finestra di dialogo che si apre quando si crea il piano</li>
<li>Altezza delle teste dei bulloni: questo piano &egrave; stato scelto con un offset di 28 mm dal piano XZ</li></ul>
<p>Per comodit&agrave;, possono essere creati due ulteriori piani di riferimento per riflettere la quantit&agrave; di materiale che deve essere asportata dai fianchi del supporto del cuscinetto. Essi sono scostati di +22 e -22 dal piano XY.
</p><p>Si consiglia di dare dei nomi esplicativi alle geometrie dello scheletro. Spesso si vuole disattivare la visibilit&agrave; dei piani di riferimento perch&eacute; ingombrano lo schermo, e se i piani hanno nomi auto-esplicativi si possono semplicemente selezionare nell'albero tramite il nome invece che dallo schermo.
<br clear="all">
</p><p><span id="The_solid_geometry"></span>
</p>
<h2><span class="mw-headline" id="La_geometria_del_solido">La geometria del solido</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-4.jpg&amp;filetimestamp=20130612185214&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-4.jpg" decoding="async" width="400" height="244" class="mw-file-element" data-file-width="1126" data-file-height="686"></a><figcaption>Sketch del primo pad</figcaption></figure>
<p>Ora &egrave; il momento di iniziare a creare un po' di geometria reale. Lo schizzo del primo pad (estrusione) &egrave; mostrato a destra. Esso &egrave; posizionato sul piano XY. Ci sono solo tre dimensioni: il raggio interno (22,5 mm), il sovrametallo alla base con un offset di 3 mm dal piano XZ e la distanza di 7 mm dal piano di riferimento che rappresenta l'asse del bullone. In questo modo, se in seguito si sposta il piano di riferimento, il pad (l'estrusione) setta automaticamente il proprio raggio esterno. Ricordare che prima di poter utilizzare il piano di riferimento per il dimensionamento, &egrave; necessario inserirlo nello schizzo come geometria esterna.
</p><p>Probabilmente vi starete chiedendo perch&eacute; vi &egrave; un piccolo segmento rettilineo in fondo a ciascun arco. Questo segmento garantisce che sar&agrave; possibile creare sugli archi uno sformo con un angolo di 2 gradi. Questo potrebbe sembrare un lavoro eccessivo per ottenere un vantaggio minimo, ma molti programmi CAD (e forse un giorno anche FreeCAD) dispongono di strumenti che evidenziono un modello solido in diversi colori e mostrano subito tutte le facce dove l'angolo di sformo non &egrave; corretto. Certamente non si vuole che al proprio modello accada questo, soprattutto dopo avervi aggiunto un sacco di raccordi!
</p><p>Dopo aver fatto il disegno (che &egrave; un po' complicato a causa delle linee tangenziali per lo sformo di 2 gradi), basta estruderlo simmetricamente al piano dello schizzo con una lunghezza di 62 mm: 34 mm per il cuscinetto, 2x9 mm per gli anelli di tenuta, 2x5 mm per lo spessore della parete.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-5.jpg&amp;filetimestamp=20130612190636&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-5.jpg" decoding="async" width="400" height="229" class="mw-file-element" data-file-width="1048" data-file-height="601"></a><figcaption>Schizzo della parte da asportare dal fianco dell'estrusione</figcaption></figure>
<p>Ora si vuole asportare sull'esterno del materiale in corrispondenza degli anelli di tenuta in quanto il loro diametro esterno &egrave; molto inferiore a quello del cuscinetto. Il modo pi&ugrave; semplice per creare i disegni necessari per questa operazione &egrave; quello di selezionare il disegno del pad e poi scegliere "Duplica selezione" dal menu "Modifica". Dopo &egrave; possibile rimappare il disegno su un fianco del pad, e modificarlo come indicato in figura.
</p><p>Le uniche due dimensioni importanti di questo disegno sono i 3 mm di sovrametallo sul fondo e il diametro interno di 78 mm: 68 mm per il diametro esterno dell'anello di tenuta + 2x5 mm spessore. Poich&eacute; l'anello di tenuta sul lato opposto ha un diametro di 55 mm qui il diametro per l'asportazione pu&ograve; essere di 65 mm.
</p><p>Dopo aver creato il disegno, creare uno scavo fino al piano di riferimento che rappresenta il lato del cuscinetto pi&ugrave; 5 mm per lo spessore. Volendo modificare il supporto in modo che sia in grado di contenere cuscinetti pi&ugrave; larghi basta cambiare i dati di questi piani di riferimento e la profondit&agrave; dello scavo si adatta di conseguenza.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-6.jpg&amp;filetimestamp=20130612193209&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-6.jpg" decoding="async" width="400" height="254" class="mw-file-element" data-file-width="1106" data-file-height="703"></a><figcaption>Sketch dello scavo interno al pad</figcaption></figure>
<p>Per ridurre il numero di lavorazioni meccaniche richieste, vogliamo anche asportare del materiale all'interno del supporto. Anche in questo caso &egrave; conveniente duplicare lo schizzo del primo pad. Non ha neppure bisogno di essere rimappato. Anche in questo caso, le uniche dimensioni importanti sono il sovrametallo (3 mm) e il diametro esterno: 84 mm nel caso in cui il cuscinetto sia (90 mm - 2x sovrametallo), 49 mm per l'anello di tenuta pi&ugrave; piccolo (55 mm - 2x3 mm) e 62 mm per l'anello di tenuta pi&ugrave; grande.
</p><p>Dopo aver creato gli schizzi, usarli per creare uno scavo: simmetricamente di 28 mm per creare lo spazio per il cuscinetto (34 mm - 2x sovrametallo) e di 23 mm su un solo lato per alloggiare gli anelli di tenuta: 34/2 mm per la met&agrave; della larghezza del cuscinetto + 9 mm per gli anelli di tenuta -  3 mm di sovrametallo. 
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-7.jpg&amp;filetimestamp=20130612193845&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-7.jpg" decoding="async" width="400" height="273" class="mw-file-element" data-file-width="1050" data-file-height="717"></a><figcaption>Geometria principale della parte superiore del supporto</figcaption></figure>
<p>La parte dovrebbe apparire come nell'immagine a destra. Notare come i diversi scavi si combinano per produrre un spessore pressoch&eacute; uniforme, cosa che render&agrave; il getto pi&ugrave; facile e meno suscettibile ad avere dei pori.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-8.jpg&amp;filetimestamp=20130612194752&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-8.jpg" decoding="async" width="400" height="276" class="mw-file-element" data-file-width="1123" data-file-height="774"></a><figcaption>Sketch con il disegno della parte per i bulloni</figcaption></figure>
<p>Ora non rimane che creare il materiale attraverso cui far passare i bulloni. Si potrebbe essere tentati di delinearlo con un cerchio e poi di estrude il cerchio, ma questo sarebbe causa di problemi quando in seguito si tentasse di basare lo sformo su di loro (suppongo che sia una debolezza di OpenCascade). Quindi, per aggirare i problemi, &egrave; meglio creare uno schizzo con l'angolo di sformo incluso e poi ruotarlo di 360 gradi.
</p><p>Anche qui piani scheletro tornano utili. Servono il piano dell'asse del bullone e il piano della testa del bullone come geometrie esterne. Perci&ograve;, creare una linea retta per l'asse di rotazione e assicurarsi che sia vincolata al piano di riferimento dell'asse del bullone. Commutarla in geometria di costruzione. Poi, definire il resto del contorno. Le dimensioni importanti sono il sovrametallo in alto e in basso e il raggio di 12 mm: 7mm per il raggio del foro + 5 mm di spessore.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-9.jpg&amp;filetimestamp=20130612195344&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-9.jpg" decoding="async" width="400" height="273" class="mw-file-element" data-file-width="1116" data-file-height="763"></a><figcaption>Geometria finita della parte superiore del supporto (senza sformi e raccordi)</figcaption></figure>
<p>Creare una funzione di rivoluzione dal disegno e poi rifletterla sul piano YZ. Questa &egrave; tutta la geometria solida che si deve modellare. Il resto sono sformi e raccordi.
<br clear="all">
</p><p><span id="Applying_draft_to_the_side_faces"></span>
</p>
<h2><span class="mw-headline" id="Applicare_uno_sformo_alla_faccia_laterale">Applicare uno sformo alla faccia laterale</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-10.jpg&amp;filetimestamp=20130616085052&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-10.jpg" decoding="async" width="400" height="254" class="mw-file-element" data-file-width="1104" data-file-height="700"></a><figcaption>Il piano neutro per creare gli sformi</figcaption></figure>
<p>Il passo successivo &egrave; quello di applicare gli sformi su tutte le facce. &Egrave; importante considerare la posizione del piano neutro, cio&egrave; il piano intorno al quale la faccia &egrave; "ruotata". Se scegliamo come piano neutro il fondo del supporto avremo un problema con lo spessore della parete nella parte superiore del supporto. Quindi, creiamo un piano di riferimento con un offset di 40 mm dal piano XZ come compromesso tra la parte superiore del supporto che diventa pi&ugrave; sottile e il fondo che diventa pi&ugrave; spesso.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-11.jpg&amp;filetimestamp=20130616085807&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-11.jpg" decoding="async" width="400" height="170" class="mw-file-element" data-file-width="1035" data-file-height="441"></a><figcaption>Applicare uno sformo alla faccia laterale del supporto</figcaption></figure>
<p>Per applicare uno sformo su una faccia, selezionare la faccia e creare la funzione di sformo. &Egrave; anche possibile selezionare pi&ugrave; facce su cui applicare contemporaneamente lo sformo. Se si tratta una parte grande, &egrave; meglio applicare lo sformo solo su una faccia alla volta. Questo perch&egrave; se si modifica la geometria e uno sformo fallisce, fallisce solo questa funzione, mentre se si inseriscono tutte le facce in una unica funzione di sformo, pu&ograve; fallire l'intera funzione a causa del fallimento di una sola faccia. Per una parte piccola come &egrave; il supporto del cuscinetto, &egrave; sufficiente creare due funzioni di sformo: una per le quattro facce esterne, e una per le facce interne.
</p><p>La finestra di dialogo costringe a scegliere un piano neutro prima di completare l'operazione. &Egrave; possibile lasciare il campo della direzione di estrazione vuoto, in questo caso la direzione sar&agrave; normale al piano neutro. Non dimenticare di impostare l'angolo di sformo pari a 2 gradi.
<br clear="all">
</p><p><span id="Filleting_the_holder"></span>
</p>
<h2><span class="mw-headline" id="Raccordare_gli_spigoli_del_supporto">Raccordare gli spigoli del supporto</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-13.jpg&amp;filetimestamp=20130616091631&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-13.jpg" decoding="async" width="400" height="275" class="mw-file-element" data-file-width="965" data-file-height="663"></a><figcaption>Racccordo della parte che deve contenere i bulloni</figcaption></figure>
<p>Ora si possono raccordare gli spigoli della parte. L'immagine mostra la prima serie di raccordi. Iniziare con i raccordi circolari piccoli e crearli con un raggio di 4 mm. Anche se secondo le specifiche 3 mm sono sufficienti, usando un raggio di 4 mm dopo la lavorazione rimane ancora 1 mm di raccordo e il bordo prodotto dalla lavorazione risulta meno tagliente. I raccordi grandi hanno un raggio di 6 mm per contribuire a distribuire la forza dai bulloni al resto della parte. Sarebbe bene usare un raggio ancora pi&ugrave; grande, ma purtroppo OpenCascade non pu&ograve; ancora gestire i raccordi sovrapposti.
</p><p>Come per lo sformo, in una parte complessa si dovrebbe eseguire il raccordo su un solo spigolo alla volta per evitare inutili errori quando viene modificata la geometria di base.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-12.jpg&amp;filetimestamp=20130616091416&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-12.jpg" decoding="async" width="400" height="259" class="mw-file-element" data-file-width="1036" data-file-height="671"></a><figcaption>Raccordare l'esterno del supporto</figcaption></figure>
<p>Gli altri raccordi hanno semplicemente un raggio di 3 mm. Guardando l'immagine a destra, i due raccordi evidenziati potrebbero effettivamente essere raccordati con 5 mm per ottenere uno spessore pi&ugrave; uniforme per la fusione. Dopo la lavorazione, sarebbe comunque rispettato lo spessore minimo di 5 mm. Ma ancora una volta il fatto che OpenCascade non pu&ograve; gestire i raccordi sovrapposti impedisce di fare questo per il raccordo compreso tra i due raccordi evidenziati.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-14.jpg&amp;filetimestamp=20130616092602&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-14.jpg" decoding="async" width="400" height="331" class="mw-file-element" data-file-width="833" data-file-height="689"></a><figcaption>Raccordare l'interno del supporto - bordo problematico</figcaption></figure>
<p>Raccordare l'interno della parte presenta delle difficolt&agrave; che non possono essere risolte con gli attuali strumenti dell'ambiente PartDesign. Il bordo evidenziato non pu&ograve; essere raccordato, ancora una volta, perch&eacute; gli arrotondamenti si sovrappongono. Questo potrebbe essere risolto creando una operazione di sweep al posto di un raccordo, ma sweep non &egrave; ancora implementato in PartDesign. Per il momento, siamo costretti a lasciare il bordo come &egrave;.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-15.jpg&amp;filetimestamp=20130616093234&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-15.jpg" decoding="async" width="400" height="279" class="mw-file-element" data-file-width="1051" data-file-height="734"></a><figcaption>La parte con i bordi arrotondati (tranne per il bordo impossibile)</figcaption></figure>
<p>L'immagine a destra mostra il pezzo finito nello stato in cui si trova prima della lavorazione (ad eccezione di quello spigolo che &egrave; impossibile arrotondare). Notare che il bordo che gira intorno a tutta la base della parte &egrave; stato lasciato apposta non raccordato. Questo &egrave; il bordo dove il fondo e la parte superiore dello stampo si uniscono. Qui, non &egrave; possibile nessun raccordo (e comunque non &egrave; richiesto).
<br clear="all">
</p><p><span id="Machining"></span>
</p>
<h2><span class="mw-headline" id="Lavorazioni">Lavorazioni</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-16.jpg&amp;filetimestamp=20130616094809&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-16.jpg" decoding="async" width="400" height="201" class="mw-file-element" data-file-width="1098" data-file-height="552"></a><figcaption>Lavorazione della parte superiore e inferiore del supporto</figcaption></figure>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-17.jpg&amp;filetimestamp=20130616115136&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-17.jpg" decoding="async" width="400" height="295" class="mw-file-element" data-file-width="958" data-file-height="706"></a><figcaption>Lavorazione della parte interna del supporto</figcaption></figure>
<p>Ora &egrave; possibile asportare il materiale che verr&agrave; tolto dalla parte in ghisa grezza durante la lavorazione. Questo &egrave; molto facile con la geometria definita scheletro. L'idea &egrave; di creare tutte le caratteristiche della lavorazione (Tasche e Scanalature) utilizzando solo operazioni di riferimento. In questo modo esse saranno totalmente indipendenti dalla geometria solida del supporto per cuscinetto, cosa che ci d&agrave; alcuni grandi vantaggi:
</p>
<ul><li>Non importa come si cambia la geometria solida, le funzioni per la lavorazione non possono mai fallire.</li>
<li>&Egrave; possibile creare la geometria di lavorazione prima di finalizzare il solido, e questo d&agrave; utili feedback visivi.</li>
<li>Se si spostano i piani scheletro di riferimento, allora sia la geometria solida che la lavorazione si adatteranno automaticamente.</li>
<li>Se si commette un errore nella geometria solida la lavorazione &egrave; ancora nella posizione corretta e molto probabilmente l'errore diventa lampante (ad esempio lo spessore della parete che diventa di 2 mm invece che di 5 mm). Invece, se si riferisce la lavorazione alla geometria solida, ci si adatter&agrave; all'errore del solido e, ad esempio si mantiene lo spessore di 5 mm, proprio nello stesso posto sbagliato, come &egrave; nel solido.</li></ul>
<p>Prima di iniziare a lavorare sulla geometria di lavorazione, mi piace mettere un punto di riferimento nella struttura ad albero e dargli un nome simile a "La_lavorazione_inizia_qui". Questo &egrave; utile se si desidera passare dallo stato grezzo allo stato lavorato della parte perch&eacute; si pu&ograve; vedere a colpo d'occhio dove posizionarsi per essere nello stato grezzo.
</p><p>Per lavorare il fondo del supporto, disegnare semplicemente un grande rettangolo nel piano XZ e con esso eseguire uno scavo. Per la parte superiore, disegnare un cerchio sul piano di riferimento che definisce la posizione della testa del bullone, con esso eseguire uno scavo e quindi rispecchiare lo scavo sul piano YZ. Nello stesso modo, creare uno scavo per il foro attraverso cui passer&agrave; il bullone e poi rifletterlo. Per la lavorazione all'interno del supporto, creare uno schizzo sul piano YZ e con esso eseguire una scanalatura.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop1-1.jpg&amp;filetimestamp=20130609182657&amp;.html" class="mw-file-description"><img src="../File/HolderTop1-1.jpg" decoding="async" width="400" height="277" class="mw-file-element" data-file-width="600" data-file-height="416"></a><figcaption>La parte finita</figcaption></figure>
<p>Dopo aver concluso la lavorazione, si pu&ograve; ottenere un piacevole effetto visivo colorando tutte le superfici lavorate in modo che si possa vedere a colpo d'occhio quali parti sono getto grezzo e quali sono lavorate dopo la fusione.
</p><p><br clear="all">
</p><p><span id="Final_notes"></span>
</p>
<h2><span class="mw-headline" id="Note_finali">Note finali</span></h2>
<p>Abbiamo modellato la parte superiore del supporto per cuscinetto con le dimensioni che avr&agrave; dopo la fusione. Per creare lo stampo di colata, &egrave; necessario applicare il ritiro alla propria parte, perch&eacute; dopo la fusione, quando il metallo caldo si raffredda, esso si riduce di qualche punto percentuale (a seconda del materiale). Di solito &egrave; meglio lasciare l'applicazione del ritiro alla fonderia che costruisce la parte perch&eacute; essi hanno le conoscenze specifiche. Essi dovrebbero anche dirvi se la vostra parte ha aree problematiche, come ad esempio pareti molto spesse che improvvisamente si uniscono a sezioni molto sottili senza che tra di esse ci sia una sezione rastremata correttamente.
</p>
<h2><span class="mw-headline" id="Seconda_parte_del_tutorial">Seconda parte del tutorial</span></h2>
<p><a href="../it/PartDesign_Bearingholder_Tutorial_II.html" title="PartDesign Bearingholder Tutorial II/it">Tutorial di PartDesign Supporto per cuscinetto II</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20251220223851
Cache expiry: 86400
Reduced expiry: false
Complications: [show&#8208;toc]
CPU time usage: 0.068 seconds
Real time usage: 0.081 seconds
Preprocessor visited node count: 109/1000000
Post&#8208;expand include size: 1613/2097152 bytes
Template argument size: 145/2097152 bytes
Highest expansion depth: 4/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post&#8208;expand size: 2418/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%    5.614      1 -total
 38.67%    2.171      1 Template:TutorialInfo/it
 31.44%    1.765      1 Template:Caption
 24.39%    1.369      1 Template:Clear
-->

<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:10431-0!canonical and timestamp 20251220223851 and revision id 1656550. Rendering was triggered because: edit-page
 -->
</div>
</div><script src="../site.js"></script>