<link href="../site.css" rel="stylesheet" type="text/css"/>
<div class="mw-page-container"><h1 class="firstHeading mw-first-heading" id="firstHeading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial I/it</span></h1><div class="mw-parser-output"><div id="itsfree" style="text-align:center; background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">
<figure class="mw-halign-left" typeof="mw:File"><span><img decoding="async" height="38" src="https://upload.wikimedia.org/wikipedia/commons/d/d5/Under_construction_icon-blue.svg" width="45"/></span><figcaption></figcaption></figure> This documentation is a work in progress. Please don't mark it as translatable since it will change in the next hours and days.
</div><div style="clear:both"></div>
<div id="itsfree" style="text-align:center;color:black;background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">This tutorial was originally written for a now deprecated development version of FreeCAD. This tutorial requires a complete rewrite to align with the PartDesign changes that will be in the upcoming v0.17 release.</div>
<div class="mw-pt-languages noprint" dir="ltr" lang="en"><div class="mw-pt-languages-label">Other languages:</div><ul class="mw-pt-languages-list"><li><a class="mw-pt-progress mw-pt-progress--complete" dir="ltr" href="PartDesign_Bearingholder_Tutorial_I.html" lang="de" title="PartDesign Lagergehäuse Tutorium I (100% translated)">Deutsch</a></li>
<li><a class="mw-pt-languages-ui mw-pt-progress mw-pt-progress--complete" dir="ltr" href="PartDesign_Bearingholder_Tutorial_I.html" lang="en" title="PartDesign Bearingholder Tutorial I (100% translated)">English</a></li>
<li><a class="mw-pt-progress mw-pt-progress--stub" dir="ltr" href="PartDesign_Bearingholder_Tutorial_I.html" lang="tr" title="PartDesign Bearingholder Tutorial I/tr (2% translated)">Türkçe</a></li>
<li><a class="mw-pt-progress mw-pt-progress--stub" dir="ltr" href="PartDesign_Bearingholder_Tutorial_I.html" lang="es" title="PartDesign Soporte de rodamiento Tutorial I (12% translated)">español</a></li>
<li><a class="mw-pt-progress mw-pt-progress--complete" dir="ltr" href="PartDesign_Bearingholder_Tutorial_I.html" lang="fr" title="PartDesign Tutoriel pour la conception d'un support de roulement (I) (100% translated)">français</a></li>
<li><span class="mw-pt-languages-selected mw-pt-progress mw-pt-progress--complete" dir="ltr" lang="it">italiano</span></li>
<li><a class="mw-pt-progress mw-pt-progress--complete" dir="ltr" href="PartDesign_Bearingholder_Tutorial_I.html" lang="pl" title="Poradnik: Projekt części, uchwyt łożyska cześć 1 (100% translated)">polski</a></li>
<li><a class="mw-pt-progress mw-pt-progress--stub" dir="ltr" href="PartDesign_Bearingholder_Tutorial_I.html" lang="pt-BR" title="Tutorial de Projeto de Mancais de Apoio I (2% translated)">português do Brasil</a></li>
<li><a class="mw-pt-progress mw-pt-progress--complete" dir="ltr" href="PartDesign_Bearingholder_Tutorial_I.html" lang="ro" title="PartDesign Bearingholder Tutorial I (96% translated)">română</a></li>
<li><a class="mw-pt-progress mw-pt-progress--stub" dir="ltr" href="PartDesign_Bearingholder_Tutorial_I.html" lang="ru" title="PartDesign Bearingholder Tutorial I/ru (2% translated)">русский</a></li></ul></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img decoding="async" height="32" src="../File/Freecad.svg" width="32"/></span></span> Tutorial
</td></tr>
<tr>
<th class="ctOdd">Topic
</th></tr>
<tr>
<td class="ctEven">Modeling
</td></tr>
<tr>
<th class="ctOdd">Level
</th></tr>
<tr>
<td class="ctEven">Experienced User
</td></tr>
<tr>
<th class="ctOdd">Time to complete
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Authors
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">FreeCAD version
</th></tr>
<tr>
<td class="ctEven">0.19.23300 or higher
</td></tr>
<tr>
<th class="ctOdd">Example files
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">See also
</th></tr>
<tr>
<td class="ctEven"><i>None</i>
</td></tr>
<tr>
<td class="ctToc"><br/><div aria-labelledby="mw-toc-heading" class="toc" id="toc" role="navigation"><input class="toctogglecheckbox" id="toctogglecheckbox" role="button" style="display:none" type="checkbox"/><div class="toctitle" dir="ltr" lang="en"><h2 id="mw-toc-heading">Contents</h2><span class="toctogglespan"><label class="toctogglelabel" for="toctogglecheckbox"></label></span></div>
<ul>
<li class="toclevel-1 tocsection-1"><a href="#Seconda_parte_del_tutorial"><span class="tocnumber">1</span> <span class="toctext">Seconda parte del tutorial</span></a></li>
<li class="toclevel-1 tocsection-2"><a href="#Dati_di_progetto"><span class="tocnumber">2</span> <span class="toctext">Dati di progetto</span></a></li>
<li class="toclevel-1 tocsection-3"><a href="#Impostazione_della_geometria_di_scheletro"><span class="tocnumber">3</span> <span class="toctext">Impostazione della geometria di scheletro</span></a></li>
<li class="toclevel-1 tocsection-4"><a href="#La_geometria_del_solido"><span class="tocnumber">4</span> <span class="toctext">La geometria del solido</span></a></li>
<li class="toclevel-1 tocsection-5"><a href="#Applicare_uno_sformo_alla_faccia_laterale"><span class="tocnumber">5</span> <span class="toctext">Applicare uno sformo alla faccia laterale</span></a></li>
<li class="toclevel-1 tocsection-6"><a href="#Raccordare_gli_spigoli_del_supporto"><span class="tocnumber">6</span> <span class="toctext">Raccordare gli spigoli del supporto</span></a></li>
<li class="toclevel-1 tocsection-7"><a href="#Lavorazioni"><span class="tocnumber">7</span> <span class="toctext">Lavorazioni</span></a></li>
<li class="toclevel-1 tocsection-8"><a href="#Note_finali"><span class="tocnumber">8</span> <span class="toctext">Note finali</span></a></li>
<li class="toclevel-1 tocsection-9"><a href="#Seconda_parte_del_tutorial_2"><span class="tocnumber">9</span> <span class="toctext">Seconda parte del tutorial</span></a></li>
</ul>
</div>
</td></tr></tbody></table>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-1.jpg"><img decoding="async" height="277" src="../File/HolderTop1-1.jpg" srcset="/images/e/e3/HolderTop1-1.jpg 1.5x" width="400"/></a><figcaption>Bearing Holder Tutorial - Supporto per cuscinetto finito(top)</figcaption></figure>
<h2><span class="mw-headline" id="Seconda_parte_del_tutorial">Seconda parte del tutorial</span></h2>
<p><a href="PartDesign_Bearingholder_Tutorial_II.html" title="PartDesign Bearingholder Tutorial II/it">PartDesign Bearingholder Tutorial II</a>
</p><p>Questa è la prima parte del tutorial. Usa il flusso di lavoro che può essere chiamato del "corpo unico", in questo esempio si utilizza solamente la parte superiore del supporto.
</p><p>Ovviamente, per seguire questo tutorial è necessario attivare l'ambiente PartDesign.
</p><p><strike>Potete trovare la versione di Jrheinlaender (l'autore di questo articolo) della parte creata con questo tutorial a [<a class="external text" href="http://ubuntuone.com/5gok0J4dye3Fo4BKWMGWVa" rel="nofollow">questo link</a>].</strike> <i> Il file non è più disponibile, ne verrà fornito uno nuovo in un secondo momento </i>.
</p>
<h2><span class="mw-headline" id="Dati_di_progetto">Dati di progetto</span></h2>
<p>Il supporto deve essere in grado di contenere un cuscinetto di 90 mm di diametro con una larghezza fino a 33 mm (ad esempio, DIN 630 tipo 2308). Il cuscinetto richiede una spalla alta almeno 4,5 mm nel supporto (e sull'albero). La parte superiore del supporto è imbullonata al fondo con due bulloni di 12 mm. A fianco del cuscinetto ci deve essere una scanalatura su entrambi i lati capace di contenere un anello di tenuta standard sull'albero DIN 3760: 38x55x7 o 40x55x7 su un lato e 50x68x8 sull'altro lato.
</p><p>Il supporto sarà prodotto con un getto in sabbia con uno spessore minimo della parete di 5 mm, un angolo di sforno con di 2 gradi e un raggio di raccordo minimo di 3 mm .
</p>
<h2><span class="mw-headline" id="Impostazione_della_geometria_di_scheletro">Impostazione della geometria di scheletro</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-2.jpg"><img decoding="async" height="284" src="../File/HolderTop1-2.jpg" srcset="/images/8/84/HolderTop1-2.jpg 1.5x" width="400"/></a><figcaption>Supporto per cuscinetto con i due più importanti piani dello scheletro</figcaption></figure>
<p>La geometria scheletro serve per catturare le dimensioni su cui si basa la progettazione in una singola funzione di riferimento (ad esempio un piano o un asse). In questo modo, quando si vuole variare le dimensioni del progetto, tutto ciò che si deve fare è di cambiare le funzioni dello scheletro. Se il modello è ben costruito, allora tutte le sue funzioni sono ricalcolate e riflettono le modifiche apportate al progetto. Questo riduce il pericolo che in un modello complesso, in cui le dimensioni di base del progetto sono utilizzate in più posti, si dimentichi di cambiarle da qualche parte.
</p><p>L'alternativa alla geometria scheletro è quella di avere una tabella delle dimensioni di base del progetto che assegna un nome simbolico ad ogni dimensione e poi utilizzare il nome simbolico ovunque sono richieste le dimensioni per costruire il modello. FreeCAD non permette ancora questo approccio.
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-3.jpg"><img decoding="async" height="277" src="../File/HolderTop1-3.jpg" srcset="/images/thumb/c/c7/HolderTop1-3.jpg/600px-HolderTop1-3.jpg 1.5x, /images/c/c7/HolderTop1-3.jpg 2x" width="400"/></a><figcaption>Piani di base e tutti i piani di Riferimento</figcaption></figure>
<p>Nel caso del supporto del cuscinetto, le due dimensioni di progettazione più importanti sono la distanza tra i bulloni (che limita la grandezza del cuscinetto che può essere utilizzato) e l'altezza delle teste dei bulloni. Le dimensioni scelte sono
</p>
<ul><li>Distanza tra i bulloni: raggio del cuscinetto (45) + spessore parete (5) + raggio del foro per il bullone (7) = 57 mm, per cui il piano verticale sarà scostato (offset) di 57 mm dal piano YZ. Per creare questo piano di riferimento, selezionare il piano YZ e poi scegliere di creare un nuovo piano di riferimento. Inserire l'offset nella finestra di dialogo che si apre quando si crea il piano</li>
<li>Altezza delle teste dei bulloni: questo piano è stato scelto con un offset di 28 mm dal piano XZ</li></ul>
<p>Per comodità, possono essere creati due ulteriori piani di riferimento per riflettere la quantità di materiale che deve essere asportata dai fianchi del supporto del cuscinetto. Essi sono scostati di +22 e -22 dal piano XY.
</p><p>Si consiglia di dare dei nomi esplicativi alle geometrie dello scheletro. Spesso si vuole disattivare la visibilità dei piani di riferimento perché ingombrano lo schermo, e se i piani hanno nomi auto-esplicativi si possono semplicemente selezionare nell'albero tramite il nome invece che dallo schermo.
<br clear="all"/>
</p>
<h2><span class="mw-headline" id="La_geometria_del_solido">La geometria del solido</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-4.jpg"><img decoding="async" height="244" src="../File/HolderTop1-4.jpg" srcset="/images/thumb/e/e7/HolderTop1-4.jpg/600px-HolderTop1-4.jpg 1.5x, /images/thumb/e/e7/HolderTop1-4.jpg/800px-HolderTop1-4.jpg 2x" width="400"/></a><figcaption>Sketch del primo pad</figcaption></figure>
<p>Ora è il momento di iniziare a creare un po' di geometria reale. Lo schizzo del primo pad (estrusione) è mostrato a destra. Esso è posizionato sul piano XY. Ci sono solo tre dimensioni: il raggio interno (22,5 mm), il sovrametallo alla base con un offset di 3 mm dal piano XZ e la distanza di 7 mm dal piano di riferimento che rappresenta l'asse del bullone. In questo modo, se in seguito si sposta il piano di riferimento, il pad (l'estrusione) setta automaticamente il proprio raggio esterno. Ricordare che prima di poter utilizzare il piano di riferimento per il dimensionamento, è necessario inserirlo nello schizzo come geometria esterna.
</p><p>Probabilmente vi starete chiedendo perché vi è un piccolo segmento rettilineo in fondo a ciascun arco. Questo segmento garantisce che sarà possibile creare sugli archi uno sformo con un angolo di 2 gradi. Questo potrebbe sembrare un lavoro eccessivo per ottenere un vantaggio minimo, ma molti programmi CAD (e forse un giorno anche FreeCAD) dispongono di strumenti che evidenziono un modello solido in diversi colori e mostrano subito tutte le facce dove l'angolo di sformo non è corretto. Certamente non si vuole che al proprio modello accada questo, soprattutto dopo avervi aggiunto un sacco di raccordi!
</p><p>Dopo aver fatto il disegno (che è un po' complicato a causa delle linee tangenziali per lo sformo di 2 gradi), basta estruderlo simmetricamente al piano dello schizzo con una lunghezza di 62 mm: 34 mm per il cuscinetto, 2x9 mm per gli anelli di tenuta, 2x5 mm per lo spessore della parete.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-5.jpg"><img decoding="async" height="229" src="../File/HolderTop1-5.jpg" srcset="/images/thumb/7/7a/HolderTop1-5.jpg/600px-HolderTop1-5.jpg 1.5x, /images/thumb/7/7a/HolderTop1-5.jpg/800px-HolderTop1-5.jpg 2x" width="400"/></a><figcaption>Schizzo della parte da asportare dal fianco dell'estrusione</figcaption></figure>
<p>Ora si vuole asportare sull'esterno del materiale in corrispondenza degli anelli di tenuta in quanto il loro diametro esterno è molto inferiore a quello del cuscinetto. Il modo più semplice per creare i disegni necessari per questa operazione è quello di selezionare il disegno del pad e poi scegliere "Duplica selezione" dal menu "Modifica". Dopo è possibile rimappare il disegno su un fianco del pad, e modificarlo come indicato in figura.
</p><p>Le uniche due dimensioni importanti di questo disegno sono i 3 mm di sovrametallo sul fondo e il diametro interno di 78 mm: 68 mm per il diametro esterno dell'anello di tenuta + 2x5 mm spessore. Poiché l'anello di tenuta sul lato opposto ha un diametro di 55 mm qui il diametro per l'asportazione può essere di 65 mm.
</p><p>Dopo aver creato il disegno, creare uno scavo fino al piano di riferimento che rappresenta il lato del cuscinetto più 5 mm per lo spessore. Volendo modificare il supporto in modo che sia in grado di contenere cuscinetti più larghi basta cambiare i dati di questi piani di riferimento e la profondità dello scavo si adatta di conseguenza.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-6.jpg"><img decoding="async" height="254" src="../File/HolderTop1-6.jpg" srcset="/images/thumb/b/b4/HolderTop1-6.jpg/600px-HolderTop1-6.jpg 1.5x, /images/thumb/b/b4/HolderTop1-6.jpg/800px-HolderTop1-6.jpg 2x" width="400"/></a><figcaption>Sketch dello scavo interno al pad</figcaption></figure>
<p>Per ridurre il numero di lavorazioni meccaniche richieste, vogliamo anche asportare del materiale all'interno del supporto. Anche in questo caso è conveniente duplicare lo schizzo del primo pad. Non ha neppure bisogno di essere rimappato. Anche in questo caso, le uniche dimensioni importanti sono il sovrametallo (3 mm) e il diametro esterno: 84 mm nel caso in cui il cuscinetto sia (90 mm - 2x sovrametallo), 49 mm per l'anello di tenuta più piccolo (55 mm - 2x3 mm) e 62 mm per l'anello di tenuta più grande.
</p><p>Dopo aver creato gli schizzi, usarli per creare uno scavo: simmetricamente di 28 mm per creare lo spazio per il cuscinetto (34 mm - 2x sovrametallo) e di 23 mm su un solo lato per alloggiare gli anelli di tenuta: 34/2 mm per la metà della larghezza del cuscinetto + 9 mm per gli anelli di tenuta -  3 mm di sovrametallo. 
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-7.jpg"><img decoding="async" height="273" src="../File/HolderTop1-7.jpg" srcset="/images/thumb/1/1f/HolderTop1-7.jpg/600px-HolderTop1-7.jpg 1.5x, /images/thumb/1/1f/HolderTop1-7.jpg/800px-HolderTop1-7.jpg 2x" width="400"/></a><figcaption>Geometria principale della parte superiore del supporto</figcaption></figure>
<p>La parte dovrebbe apparire come nell'immagine a destra. Notare come i diversi scavi si combinano per produrre un spessore pressoché uniforme, cosa che renderà il getto più facile e meno suscettibile ad avere dei pori.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-8.jpg"><img decoding="async" height="276" src="../File/HolderTop1-8.jpg" srcset="/images/thumb/d/d5/HolderTop1-8.jpg/600px-HolderTop1-8.jpg 1.5x, /images/thumb/d/d5/HolderTop1-8.jpg/800px-HolderTop1-8.jpg 2x" width="400"/></a><figcaption>Sketch con il disegno della parte per i bulloni</figcaption></figure>
<p>Ora non rimane che creare il materiale attraverso cui far passare i bulloni. Si potrebbe essere tentati di delinearlo con un cerchio e poi di estrude il cerchio, ma questo sarebbe causa di problemi quando in seguito si tentasse di basare lo sformo su di loro (suppongo che sia una debolezza di OpenCascade). Quindi, per aggirare i problemi, è meglio creare uno schizzo con l'angolo di sformo incluso e poi ruotarlo di 360 gradi.
</p><p>Anche qui piani scheletro tornano utili. Servono il piano dell'asse del bullone e il piano della testa del bullone come geometrie esterne. Perciò, creare una linea retta per l'asse di rotazione e assicurarsi che sia vincolata al piano di riferimento dell'asse del bullone. Commutarla in geometria di costruzione. Poi, definire il resto del contorno. Le dimensioni importanti sono il sovrametallo in alto e in basso e il raggio di 12 mm: 7mm per il raggio del foro + 5 mm di spessore.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-9.jpg"><img decoding="async" height="273" src="../File/HolderTop1-9.jpg" srcset="/images/thumb/2/26/HolderTop1-9.jpg/600px-HolderTop1-9.jpg 1.5x, /images/thumb/2/26/HolderTop1-9.jpg/800px-HolderTop1-9.jpg 2x" width="400"/></a><figcaption>Geometria finita della parte superiore del supporto (senza sformi e raccordi)</figcaption></figure>
<p>Creare una funzione di rivoluzione dal disegno e poi rifletterla sul piano YZ. Questa è tutta la geometria solida che si deve modellare. Il resto sono sformi e raccordi.
<br clear="all"/>
</p>
<h2><span class="mw-headline" id="Applicare_uno_sformo_alla_faccia_laterale">Applicare uno sformo alla faccia laterale</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-10.jpg"><img decoding="async" height="254" src="../File/HolderTop1-10.jpg" srcset="/images/thumb/7/78/HolderTop1-10.jpg/600px-HolderTop1-10.jpg 1.5x, /images/thumb/7/78/HolderTop1-10.jpg/800px-HolderTop1-10.jpg 2x" width="400"/></a><figcaption>Il piano neutro per creare gli sformi</figcaption></figure>
<p>Il passo successivo è quello di applicare gli sformi su tutte le facce. È importante considerare la posizione del piano neutro, cioè il piano intorno al quale la faccia è "ruotata". Se scegliamo come piano neutro il fondo del supporto avremo un problema con lo spessore della parete nella parte superiore del supporto. Quindi, creiamo un piano di riferimento con un offset di 40 mm dal piano XZ come compromesso tra la parte superiore del supporto che diventa più sottile e il fondo che diventa più spesso.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-11.jpg"><img decoding="async" height="170" src="../File/HolderTop1-11.jpg" srcset="/images/thumb/3/3e/HolderTop1-11.jpg/600px-HolderTop1-11.jpg 1.5x, /images/thumb/3/3e/HolderTop1-11.jpg/800px-HolderTop1-11.jpg 2x" width="400"/></a><figcaption>Applicare uno sformo alla faccia laterale del supporto</figcaption></figure>
<p>Per applicare uno sformo su una faccia, selezionare la faccia e creare la funzione di sformo. È anche possibile selezionare più facce su cui applicare contemporaneamente lo sformo. Se si tratta una parte grande, è meglio applicare lo sformo solo su una faccia alla volta. Questo perchè se si modifica la geometria e uno sformo fallisce, fallisce solo questa funzione, mentre se si inseriscono tutte le facce in una unica funzione di sformo, può fallire l'intera funzione a causa del fallimento di una sola faccia. Per una parte piccola come è il supporto del cuscinetto, è sufficiente creare due funzioni di sformo: una per le quattro facce esterne, e una per le facce interne.
</p><p>La finestra di dialogo costringe a scegliere un piano neutro prima di completare l'operazione. È possibile lasciare il campo della direzione di estrazione vuoto, in questo caso la direzione sarà normale al piano neutro. Non dimenticare di impostare l'angolo di sformo pari a 2 gradi.
<br clear="all"/>
</p>
<h2><span class="mw-headline" id="Raccordare_gli_spigoli_del_supporto">Raccordare gli spigoli del supporto</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-13.jpg"><img decoding="async" height="275" src="../File/HolderTop1-13.jpg" srcset="/images/thumb/1/1e/HolderTop1-13.jpg/600px-HolderTop1-13.jpg 1.5x, /images/thumb/1/1e/HolderTop1-13.jpg/800px-HolderTop1-13.jpg 2x" width="400"/></a><figcaption>Racccordo della parte che deve contenere i bulloni</figcaption></figure>
<p>Ora si possono raccordare gli spigoli della parte. L'immagine mostra la prima serie di raccordi. Iniziare con i raccordi circolari piccoli e crearli con un raggio di 4 mm. Anche se secondo le specifiche 3 mm sono sufficienti, usando un raggio di 4 mm dopo la lavorazione rimane ancora 1 mm di raccordo e il bordo prodotto dalla lavorazione risulta meno tagliente. I raccordi grandi hanno un raggio di 6 mm per contribuire a distribuire la forza dai bulloni al resto della parte. Sarebbe bene usare un raggio ancora più grande, ma purtroppo OpenCascade non può ancora gestire i raccordi sovrapposti.
</p><p>Come per lo sformo, in una parte complessa si dovrebbe eseguire il raccordo su un solo spigolo alla volta per evitare inutili errori quando viene modificata la geometria di base.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-12.jpg"><img decoding="async" height="259" src="../File/HolderTop1-12.jpg" srcset="/images/thumb/b/bd/HolderTop1-12.jpg/600px-HolderTop1-12.jpg 1.5x, /images/thumb/b/bd/HolderTop1-12.jpg/800px-HolderTop1-12.jpg 2x" width="400"/></a><figcaption>Raccordare l'esterno del supporto</figcaption></figure>
<p>Gli altri raccordi hanno semplicemente un raggio di 3 mm. Guardando l'immagine a destra, i due raccordi evidenziati potrebbero effettivamente essere raccordati con 5 mm per ottenere uno spessore più uniforme per la fusione. Dopo la lavorazione, sarebbe comunque rispettato lo spessore minimo di 5 mm. Ma ancora una volta il fatto che OpenCascade non può gestire i raccordi sovrapposti impedisce di fare questo per il raccordo compreso tra i due raccordi evidenziati.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-14.jpg"><img decoding="async" height="331" src="../File/HolderTop1-14.jpg" srcset="/images/thumb/8/8c/HolderTop1-14.jpg/600px-HolderTop1-14.jpg 1.5x, /images/thumb/8/8c/HolderTop1-14.jpg/800px-HolderTop1-14.jpg 2x" width="400"/></a><figcaption>Raccordare l'interno del supporto - bordo problematico</figcaption></figure>
<p>Raccordare l'interno della parte presenta delle difficoltà che non possono essere risolte con gli attuali strumenti dell'ambiente PartDesign. Il bordo evidenziato non può essere raccordato, ancora una volta, perché gli arrotondamenti si sovrappongono. Questo potrebbe essere risolto creando una operazione di sweep al posto di un raccordo, ma sweep non è ancora implementato in PartDesign. Per il momento, siamo costretti a lasciare il bordo come è.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-15.jpg"><img decoding="async" height="279" src="../File/HolderTop1-15.jpg" srcset="/images/thumb/0/05/HolderTop1-15.jpg/600px-HolderTop1-15.jpg 1.5x, /images/thumb/0/05/HolderTop1-15.jpg/800px-HolderTop1-15.jpg 2x" width="400"/></a><figcaption>La parte con i bordi arrotondati (tranne per il bordo impossibile)</figcaption></figure>
<p>L'immagine a destra mostra il pezzo finito nello stato in cui si trova prima della lavorazione (ad eccezione di quello spigolo che è impossibile arrotondare). Notare che il bordo che gira intorno a tutta la base della parte è stato lasciato apposta non raccordato. Questo è il bordo dove il fondo e la parte superiore dello stampo si uniscono. Qui, non è possibile nessun raccordo (e comunque non è richiesto).
<br clear="all"/>
</p>
<h2><span class="mw-headline" id="Lavorazioni">Lavorazioni</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-16.jpg"><img decoding="async" height="201" src="../File/HolderTop1-16.jpg" srcset="/images/thumb/8/86/HolderTop1-16.jpg/600px-HolderTop1-16.jpg 1.5x, /images/thumb/8/86/HolderTop1-16.jpg/800px-HolderTop1-16.jpg 2x" width="400"/></a><figcaption>Lavorazione della parte superiore e inferiore del supporto</figcaption></figure>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-17.jpg"><img decoding="async" height="295" src="../File/HolderTop1-17.jpg" srcset="/images/thumb/d/d6/HolderTop1-17.jpg/600px-HolderTop1-17.jpg 1.5x, /images/thumb/d/d6/HolderTop1-17.jpg/800px-HolderTop1-17.jpg 2x" width="400"/></a><figcaption>Lavorazione della parte interna del supporto</figcaption></figure>
<p>Ora è possibile asportare il materiale che verrà tolto dalla parte in ghisa grezza durante la lavorazione. Questo è molto facile con la geometria definita scheletro. L'idea è di creare tutte le caratteristiche della lavorazione (Tasche e Scanalature) utilizzando solo operazioni di riferimento. In questo modo esse saranno totalmente indipendenti dalla geometria solida del supporto per cuscinetto, cosa che ci dà alcuni grandi vantaggi:
</p>
<ul><li>Non importa come si cambia la geometria solida, le funzioni per la lavorazione non possono mai fallire.</li>
<li>È possibile creare la geometria di lavorazione prima di finalizzare il solido, e questo dà utili feedback visivi.</li>
<li>Se si spostano i piani scheletro di riferimento, allora sia la geometria solida che la lavorazione si adatteranno automaticamente.</li>
<li>Se si commette un errore nella geometria solida la lavorazione è ancora nella posizione corretta e molto probabilmente l'errore diventa lampante (ad esempio lo spessore della parete che diventa di 2 mm invece che di 5 mm). Invece, se si riferisce la lavorazione alla geometria solida, ci si adatterà all'errore del solido e, ad esempio si mantiene lo spessore di 5 mm, proprio nello stesso posto sbagliato, come è nel solido.</li></ul>
<p>Prima di iniziare a lavorare sulla geometria di lavorazione, mi piace mettere un punto di riferimento nella struttura ad albero e dargli un nome simile a "La_lavorazione_inizia_qui". Questo è utile se si desidera passare dallo stato grezzo allo stato lavorato della parte perché si può vedere a colpo d'occhio dove posizionarsi per essere nello stato grezzo.
</p><p>Per lavorare il fondo del supporto, disegnare semplicemente un grande rettangolo nel piano XZ e con esso eseguire uno scavo. Per la parte superiore, disegnare un cerchio sul piano di riferimento che definisce la posizione della testa del bullone, con esso eseguire uno scavo e quindi rispecchiare lo scavo sul piano YZ. Nello stesso modo, creare uno scavo per il foro attraverso cui passerà il bullone e poi rifletterlo. Per la lavorazione all'interno del supporto, creare uno schizzo sul piano YZ e con esso eseguire una scanalatura.
<br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-1.jpg"><img decoding="async" height="277" src="../File/HolderTop1-1.jpg" srcset="/images/e/e3/HolderTop1-1.jpg 1.5x" width="400"/></a><figcaption>La parte finita</figcaption></figure>
<p>Dopo aver concluso la lavorazione, si può ottenere un piacevole effetto visivo colorando tutte le superfici lavorate in modo che si possa vedere a colpo d'occhio quali parti sono getto grezzo e quali sono lavorate dopo la fusione.
</p><p><br clear="all"/>
</p>
<h2><span class="mw-headline" id="Note_finali">Note finali</span></h2>
<p>Abbiamo modellato la parte superiore del supporto per cuscinetto con le dimensioni che avrà dopo la fusione. Per creare lo stampo di colata, è necessario applicare il ritiro alla propria parte, perché dopo la fusione, quando il metallo caldo si raffredda, esso si riduce di qualche punto percentuale (a seconda del materiale). Di solito è meglio lasciare l'applicazione del ritiro alla fonderia che costruisce la parte perché essi hanno le conoscenze specifiche. Essi dovrebbero anche dirvi se la vostra parte ha aree problematiche, come ad esempio pareti molto spesse che improvvisamente si uniscono a sezioni molto sottili senza che tra di esse ci sia una sezione rastremata correttamente.
</p>
<h2><span class="mw-headline" id="Seconda_parte_del_tutorial_2">Seconda parte del tutorial</span></h2>
<p><a href="PartDesign_Bearingholder_Tutorial_II.html" title="PartDesign Bearingholder Tutorial II/it">PartDesign Bearingholder Tutorial II</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20241129212531
Cache expiry: 86400
Reduced expiry: false
Complications: [show‐toc, no‐toc‐conversion]
CPU time usage: 0.151 seconds
Real time usage: 0.709 seconds
Preprocessor visited node count: 107/1000000
Post‐expand include size: 1505/2097152 bytes
Template argument size: 264/2097152 bytes
Highest expansion depth: 3/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post‐expand size: 2189/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%   53.448      1 -total
 12.29%    6.568      1 Template:Page_in_progress
  1.73%    0.926      1 Template:VeryImportantMessage
  1.73%    0.925      1 Template:TutorialInfo
  0.85%    0.456      1 Template:Clear
-->
<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:10431-0!canonical and timestamp 20241129212530 and revision id 1075235. Rendering was triggered because: api-parse
 -->
</div></div><script src="../script.js"></script>
