<link href="../site.css" rel="stylesheet" type="text/css"/><div class="mw-page-container"><h1 id="firstHeading" class="firstHeading mw-first-heading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial II/it</span></h1><?xml encoding="UTF-8"><div class="mw-content-ltr mw-parser-output" lang="it" dir="ltr"><div class="mw-pt-languages noprint navigation-not-searchable" lang="en" dir="ltr"><div class="mw-pt-languages-label">Other languages:</div><ul class="mw-pt-languages-list"><li><a href="../index.php?title=Special;Translate&amp;group=page-PartDesign+Bearingholder+Tutorial+II&amp;language=&amp;task=view.html" class="new" title="Start translation for this language" lang="" dir="ltr"></a></li>
<li><a href="../de/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--complete" title="PartDesign Lagergeh&auml;use Tutorium II (100% translated)" lang="de" dir="ltr">Deutsch</a></li>
<li><a href="../PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-languages-ui mw-pt-progress mw-pt-progress--complete" title="PartDesign Bearingholder Tutorial II (100% translated)" lang="en" dir="ltr">English</a></li>
<li><a href="../tr/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Bearingholder Tutorial II/tr (2% translated)" lang="tr" dir="ltr">T&uuml;rk&ccedil;e</a></li>
<li><a href="../es/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--med" title="PartDesign Soporte de rodamiento Tutorial II (17% translated)" lang="es" dir="ltr">espa&ntilde;ol</a></li>
<li><a href="../fr/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--high" title="PartDesign Tutoriel pour la conception d'un support de roulement (II) (93% translated)" lang="fr" dir="ltr">fran&ccedil;ais</a></li>
<li><span class="mw-pt-languages-selected mw-pt-progress mw-pt-progress--complete" lang="it" dir="ltr">italiano</span></li>
<li><a href="../pl/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--complete" title="Poradnik: Projekt cz&#281;&#347;ci, uchwyt &#322;o&#380;yska cze&#347;&#263; 2 (100% translated)" lang="pl" dir="ltr">polski</a></li>
<li><a href="../pt-br/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--low" title="Tutorial de Projeto de Mancais de Apoio II (2% translated)" lang="pt-BR" dir="ltr">portugu&ecirc;s do Brasil</a></li>
<li><a href="../ro/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--high" title="PartDesign Bearingholder Tutorial II (90% translated)" lang="ro" dir="ltr">rom&acirc;n&#259;</a></li>
<li><a href="../ru/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Bearingholder Tutorial II/ru (7% translated)" lang="ru" dir="ltr">&#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;</a></li></ul></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img src="../File/Freecad.svg" decoding="async" width="32" height="32" class="mw-file-element" data-file-width="48" data-file-height="48"></span></span> Tutorial
</td></tr>
<tr>
<th class="ctOdd">Argomento
</th></tr>
<tr>
<td class="ctEven">Modellazione
</td></tr>
<tr>
<th class="ctOdd">Livello di difficolt&agrave;
</th></tr>
<tr>
<td class="ctEven">Utente esperto
</td></tr>
<tr>
<th class="ctOdd">Tempo di esecuzione
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Autori
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">Versione di FreeCAD
</th></tr>
<tr>
<td class="ctEven">0.19.23300 o superiore
</td></tr>
<tr>
<th class="ctOdd">Files di esempio
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Vedere anche
</th></tr>
<tr>
<td class="ctEven"><i>Nessuno</i>
</td></tr>
<tr>
<td class="ctToc"><br><meta property="mw:PageProp/toc">
</td></tr></tbody></table>
<p><span id="Purpose_in_Brief"></span>
</p>
<h2><span class="mw-headline" id="Scopo_in_breve">Scopo in breve</span></h2>
<p>Lo scopo di questo tutorial &egrave; di presentare due diversi flussi di lavoro per la creazione di un pezzo fuso con sformi e raccordi. A seconda dei programmi CAD che si &egrave; utilizzato, si potrebbe avere familiarit&agrave; con uno o con l'altro. Come esempio pratico, modelleremo un semplice supporto per cuscinetto.
</p><p>Questa &egrave; la seconda parte del tutorial. In questo esempio si usa il flusso di lavoro che pu&ograve; essere chiamato del "corpo multiplo" e si utilizza solamente la parte superiore del supporto.
</p><p>Ovviamente, per seguire questo tutorial &egrave; necessario attivare l'ambiente PartDesign.
</p><p><span typeof="mw:File"><a href="../index.php?title=HolderTop2-19.jpg&amp;filetimestamp=20130716184057&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-19.jpg" decoding="async" width="400" height="263" class="mw-file-element" data-file-width="1037" data-file-height="683"></a></span>
</p>
<p style="text-align:left; font-style:italic; max-width:800px; box-sizing:border-box; margin-block:1em; margin-inline:clamp(1em, 6vw, 2em); padding-inline:clamp(0.75em, 4vw, 2em); word-break:normal; overflow-wrap:break-word;">Tutorial del supporto di un cuscinetto - Supporto del cuscinetto finito (parte superiore)</p>
<p><span id="Design_data"></span>
</p>
<h2><span class="mw-headline" id="Dati_di_progetto">Dati di progetto</span></h2>
<p>Il supporto deve essere in grado di contenere un cuscinetto di 90 mm di diametro con una larghezza fino a 33 mm (ad esempio, DIN 630 tipo 2308). Il cuscinetto richiede una spalla alta almeno 4,5 mm nel supporto (e sull'albero). La parte superiore del supporto &egrave; imbullonata al fondo con due bulloni di 12 mm. A fianco del cuscinetto ci deve essere una scanalatura su entrambi i lati capace di contenere un anello di tenuta standard sull'albero DIN 3760: 38x55x7 o 40x55x7 su un lato e 50x68x8 sull'altro lato.
</p><p>Il supporto sar&agrave; prodotto con un getto in sabbia con uno spessore minimo della parete di 5 mm, un angolo di sforno con di 2 gradi e un raggio di raccordo minimo di 3 mm .
</p><p><br clear="all">
</p><p><span id="Setting_up_the_skeleton_geometry"></span>
</p>
<h2><span class="mw-headline" id="Impostazione_della_geometria_di_scheletro">Impostazione della geometria di scheletro</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-2.png&amp;filetimestamp=20160718193124&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-2.png" decoding="async" width="400" height="149" class="mw-file-element" data-file-width="1260" data-file-height="468"></a><figcaption>Sketch della geometria scheletro</figcaption></figure>
<p>Creare una nuova parte nell'ambiente PartDesign. Rinominare il corpo da come  viene creato per impostazione predefinita in "Skeleton". Questo corpo probabilmente &egrave; gi&agrave; attivato, cosa che si pu&ograve; vedere dallo sfondo blu nell'albero delle propriet&agrave;. Creare un nuovo schizzo sul piano YZ contenente il contorno dell'albero, i cuscinetti e gli anelli di tenuta. Dopo aver terminato lo schizzo, eseguire con esso una operazione di rivoluzione. Questa funzione "Scheletro" sar&agrave; utilizzata successivamente come riferimento per la geometria reale. In questo modo se si desidera modificare le dimensioni, basta regolare le dimensioni della funzione scheletro e il resto della parte viene aggiornato di conseguenza.
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-2-1.jpg&amp;filetimestamp=20130711190937&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-2-1.jpg" decoding="async" width="400" height="260" class="mw-file-element" data-file-width="1058" data-file-height="687"></a><figcaption>La geometria scheletro</figcaption></figure>
<p><br clear="all">
</p><p><span id="The_main_body"></span>
</p>
<h2><span class="mw-headline" id="Il_corpo_principale">Il corpo principale</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-3.jpg&amp;filetimestamp=20130711184543&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-3.jpg" decoding="async" width="400" height="298" class="mw-file-element" data-file-width="1040" data-file-height="774"></a><figcaption>Schizzo della prima estrusione</figcaption></figure>
<p>Creare un nuovo corpo e renderlo attivo. Lo schizzo della prima estrusione &egrave; mostrato a destra. Esso &egrave; posto su un piano di riferimento, con un offset di 5 mm (lo spessore della parete) dalla faccia che nello scheletro definisce un fianco (esterno) di uno degli anelli di tenuta del cuscinetto. Poich&eacute; tutte le dimensioni importanti sono prese dallo scheletro, ci sono solo tre dimensioni: l'entit&agrave; della lavorazione (3 mm) alla base come offset per il piano XY, lo spessore della parete 5 mm dal diametro esterno dello scheletro, e i 2 gradi dell'angolo di sformo. Per creare la dimensione 5 mm, &egrave; necessario prima selezionare il cerchio esterno (raggio 45 mm) della geometria scheletro come "geometria esterna" dello schizzo, e poi aggiungere una linea di costruzione tangente e vincolata a questo cerchio con un angolo di due gradi.
</p><p>Probabilmente vi starete chiedendo perch&eacute; c'&egrave; questo piccolo segmento dritto in fondo a ciascun arco. Questo segmento assicura che sar&agrave; possibile creare uno sformo con un angolo di 2 gradi sugli archi. Questo potrebbe sembrare un lavoro eccessivo per ottenere un vantaggio minimo, ma molti programmi CAD (e forse un giorno anche FreeCAD) dispongono di strumenti che evidenziono un modello solido in diversi colori e mostrano subito tutte le facce dove l'angolo di sformo non &egrave; corretto. Certamente non si vuole che al proprio modello accada questo, soprattutto dopo avervi aggiunto un sacco di raccordi!
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-4.jpg&amp;filetimestamp=20130711185009&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-4.jpg" decoding="async" width="400" height="279" class="mw-file-element" data-file-width="1117" data-file-height="780"></a><figcaption>La prima estrusione (Pad)</figcaption></figure>
<p>Dopo aver finito il disegno (che &egrave; un po' complicato a causa delle linee tangenziali per lo sformo di 2 gradi), creare con questo schizzo una estrusione (Pad) che si estenda fino all'altro fianco della geometria dello scheletro, di nuovo con un offset dal fianco di 5 mm.  Questa volta non &egrave; necessario creare un piano di riferimento, la modalit&agrave; "fino alla faccia" della finestra di dialogo dell'estrusione permette di inserire un offset.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-5.jpg&amp;filetimestamp=20130711190315&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-5.jpg" decoding="async" width="400" height="313" class="mw-file-element" data-file-width="899" data-file-height="703"></a><figcaption>Sketch per l'estrusione con cui si asporta del materiale</figcaption></figure>
<p>Successivamente, si asporta un po' di materiale su entrambe le estremit&agrave; del Pad, perch&eacute; per i pezzi di fusione l'ideale &egrave; avere sempre uno spessore il pi&ugrave; uniforme possibile. Creare uno schizzo su ciascuno dei lati frontali del Pad e dimensionarlo con 5 mm di offset dal cerchio che rappresenta l'anello di tenuta del cuscinetto (raggio 27,5 mm su un lato e 34 mm sull'altro). Per il segmento della linea di fondo del disegno, creare un'altra geometria esterna al Pad e vincolarla a questa. In questo modo lo schizzo ha una sola dimensione, 5 mm dello spessore della parete (le dimensioni 150 mm e 75 mm non sono importanti, basta che siano abbastanza grandi in modo da garantire che tutto quello che non serve venga asportato).
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-6.jpg&amp;filetimestamp=20130711190430&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-6.jpg" decoding="async" width="400" height="277" class="mw-file-element" data-file-width="1063" data-file-height="736"></a><figcaption>Il Pad con gli scavi per ottenere uno spessore uniforme della parete</figcaption></figure>
<p>Utilizzare il disegno &egrave; stato creato per eseguire uno scavo ed estenderlo alla faccia della geometria dello scheletro che rappresenta il cuscinetto, meno 5 mm di offset per lo spessore della parete. Per il secondo scavo, &egrave; possibile utilizzare l'opzione "Duplica oggetto selezionato" dal menu Modifica per duplicare il disegno gi&agrave; fatto (scegliere di non duplicare gli oggetti dipendenti se viene posta la domanda). Quindi, selezionare la faccia su cui si desidera spostare questo schizzo, e dire a FreeCAD di mappare lo schizzo su questa faccia (questa &egrave; una voce del menu PartDesign). Dopo aver creato il secondo scavo, &egrave; possibile osservare il risultato dal basso per verificare se si dispone di una parete di spessore di 5 mm intorno al contorno della geometria dello scheletro.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-7.jpg&amp;filetimestamp=20130711192218&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-7.jpg" decoding="async" width="400" height="226" class="mw-file-element" data-file-width="1085" data-file-height="614"></a><figcaption>Piano neutro per applicare lo sformo</figcaption></figure>
<p>Ora &egrave; il momento di creare gli sformi e i raccordi. L'operazione di sformo richiede un piano neutro, questo significa che la geometria che &egrave; tagliata da questo piano rimarr&agrave; al suo posto, mentre il resto della faccia viene inclinato secondo l'angolo di sformo. Usare il piano della base del Pad come piano neutro non &egrave; una buona idea poich&eacute; lo spessore della parete nella parte superiore del supporto diventerebbe meno di 5 mm. Quindi per questa operazione creiamo un piano di Riferimento con un offset di circa 35 mm da XY. Attivare il corpo Scheletro e creare l&igrave; il piano, perch&eacute; ne avremo ancora bisogno per applicare degli sformi ad altri corpi.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-8.jpg&amp;filetimestamp=20130711192240&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-8.jpg" decoding="async" width="400" height="233" class="mw-file-element" data-file-width="1106" data-file-height="644"></a><figcaption>Primo corpo con sformi e raccordi</figcaption></figure>
<p>L'immagine a destra mostra il primo corpo finito con gli sformi e i raccordi applicati. Notare che i bordi esterni (concavo) hanno un raggio di raccordo maggiore di 5 mm, sempre con lo scopo di creare uno spessore della parete il pi&ugrave; uniforme possibile (pi&ugrave; di 5 mm non &egrave; possibile perch&eacute; altrimenti dopo la lavorazione interna del supporto lo spessore della parete diventa inferiore a 5 mm).
<br clear="all">
</p><p><span id="Adding_the_bodies_for_the_bolts"></span>
</p>
<h2><span class="mw-headline" id="Aggiungere_i_corpi_per_i_bulloni">Aggiungere i corpi per i bulloni</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-13.jpg&amp;filetimestamp=20130716175052&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-13.jpg" decoding="async" width="400" height="333" class="mw-file-element" data-file-width="730" data-file-height="607"></a><figcaption>Sketch con il disegno della parte per i bulloni</figcaption></figure>
<p>I bulloni hanno bisogno di due corpi cilindrici su entrambi i lati del corpo principale. E' meglio inserire lo sformo di 2 gradi nel disegno. Ho provato a creare un cilindro con una rotazione e applicarvi successivamente uno sformo, ma dopo il mirroring sono successe delle strane cose e non ho potuto applicarvi i raccordi, perch&eacute; la superficie era in qualche modo deformata.
</p><p>Lo schizzo &egrave; dimensionato in modo che l'asse di rotazione sia distante 12 mm dal diametro esterno del corpo scheletro, 7 mm per il raggio del foro pi&ugrave; 5 mm per lo spessore della parete. Per il gusto di avere una parte completamente parametrica &egrave; una buona idea aggiungere un piano allo scheletro a circa 25 mm sopra il piano XY per contrassegnare la faccia superiore dei cilindri. Dato che questa faccia verr&agrave; lavorata, lo schizzo &egrave; dimensionato 3 mm al di sopra di essa.
</p><p><br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-14.jpg&amp;filetimestamp=20130715192541&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-14.jpg" decoding="async" width="400" height="244" class="mw-file-element" data-file-width="987" data-file-height="601"></a><figcaption>I corpi per i bulloni</figcaption></figure>
<p>Creare una rivoluzione dallo schizzo e applicare un raccordo di 4 mm al bordo superiore. In questo modo, dopo la lavorazione in cui si asportano 3 mm, rimane ancora un lieve raccordo che permette di evitare che il bordo sia tagliente e che qualcuno possa ferirsi durante il serraggio dei bulloni.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-16.jpg&amp;filetimestamp=20130715192912&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-16.jpg" decoding="async" width="400" height="261" class="mw-file-element" data-file-width="868" data-file-height="566"></a><figcaption>Il corpo principale con i due corpi per i bulloni</figcaption></figure>
<p>Creare una funzione booleana per fondere il corpo principale con il corpo per il bullone. Quindi creare un nuovo corpo per l'altro lato. Duplicare lo schizzo della rivoluzione, spostarlo in questo corpo e creare il secondo corpo per i bulloni (il mirroring di un corpo non &egrave; ancora supportato, quindi &egrave; necessario rifarlo per la maggior parte). Poi fondere anche questo secondo corpo nel corpo principale. Infine applicare un grande raccordo sul bordo creato con l'operazione di fusione booleana, il bordo tra il corpo principale e il corpo per i bulloni. Il pi&ugrave; grande che ho potuto ottenere &egrave; di 4 mm.
<br clear="all">
</p><p><span id="Hollowing_out_the_main_body"></span>
</p>
<h2><span class="mw-headline" id="Scavare_il_corpo_principale">Scavare il corpo principale</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-9.jpg&amp;filetimestamp=20130714182319&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-9.jpg" decoding="async" width="300" height="347" class="mw-file-element" data-file-width="477" data-file-height="551"></a><figcaption>Il primo Pad del corpo dello scavo all'interno del corpo principale</figcaption></figure>
<p>Passare ora a lavorare sulla parte interna del supporto e scavare per creare lo spazio per il cuscinetto e per gli anelli di tenuta. Nel fare questo, naturalmente, bisogna tenere a mente il sovrametallo di 3 mm. Dal momento che questo tutorial insegna il metodo "multi-corpo", prima si crea la geometria interna come un corpo separato e poi la si aporta dal corpo principale con una operazione booleana.
</p><p>Creare un nuovo corpo e renderlo attivo. In primo luogo, serve un piano di riferimento con un offset di 3 mm all'interno della faccia scheletro che rappresenta il lato del cuscinetto. Poi, duplicare il disegno del primo pad del corpo principale. Sar&agrave; aggiunto al corpo principale, quindi fare clic destro su di esso e scegliere di spostarlo sul corpo appena creato (se &egrave; attivo l'ambiente PartDesign, questa opzione &egrave; disponibile solo nel menu di contesto). Mappare il disegno su piano di riferimento (se dopo la mappatura lo schizzo risulta capovolto, spostare il piano di riferimento sull'altro lato del cuscinetto, accanto a cui si trova lo schizzo duplicato). Ora, modificare il disegno in modo che il diametro sia di 3 mm inferiore al diametro esterno della geometria scheletro che rappresenta il cuscinetto. Basta rimuovere la dimensione di 5 mm, trascinare il disegno all'interno del cerchio di riferimento, e poi creare una nuova dimensione di 3 mm.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-10.jpg&amp;filetimestamp=20130714183706&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-10.jpg" decoding="async" width="400" height="218" class="mw-file-element" data-file-width="1013" data-file-height="551"></a><figcaption>Il corpo dello scavo interno al corpo scheletro</figcaption></figure>
<p>Ora servono altri due Pad per scavare lo spazio per gli anelli di tenuta. Duplicare il disegno del primo pad del "Corpo per lo scavo" e mapparlo al piano XZ. Modificare lo schizzo e sostituire il riferimento esterno con il diametro esterno dell'anello di tenuta del cuscinetto. Estrudere questo schizzo con un offset di 3 mm dal fianco dell'anello di tenuta. Ripetere l'intero processo per l'anello di tenuta del lato opposto.
</p><p>Dopo di questo creare altri due rilievi all'interno del supporto, come gli ultimi due per dare un gioco all'albero (ad esempio 3 mm).
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-11.jpg&amp;filetimestamp=20130714184941&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-11.jpg" decoding="async" width="400" height="200" class="mw-file-element" data-file-width="1055" data-file-height="527"></a><figcaption>Il corpo completo della parte da asportare (meno i raccordi impossibili)</figcaption></figure>
<p>Ora non rimane che applicare lo sformo alle facce piane laterali, utilizzando lo stesso piano neutro come si &egrave; fatto per il corpo principale, e i raccordi. Applicare un raccordo generale di 3 mm a tutti i bordi. Noterete che ci sono diversi spigoli che non possono essere raccordati ... questo &egrave; un difetto del kernel geometrico sottostante usato da FreeCAD.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-15.jpg&amp;filetimestamp=20130715192602&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-15.jpg" decoding="async" width="400" height="237" class="mw-file-element" data-file-width="974" data-file-height="576"></a><figcaption>La parte grezza completata del supporto (senza le lavorazioni)</figcaption></figure>
<p>Siamo pronti per "svuotare" il corpo principale. Selezionarlo e scegliere di creare una nuova operazione booleana. Aggiungere il corpo della parte da asportare alla lista della finestra e impostare l'operazione "Differenza". Mettere un raccordo di 3 mm sui due bordi derivanti dalla operazione di asportazione (rimangono di nuovo alcuni bordi che "non sono raccordabili"). Il risultato dovrebbe essere simile alla figura sulla destra.
</p><p>Ora la parte grezza &egrave; completata. Questo &egrave; ci&ograve; a cui il supporto somiglier&agrave; prima della lavorazione. Si noti che, poich&eacute; lo stampo avr&agrave; una met&agrave; superiore e met&agrave; una inferiore, il bordo tra queste due parti pu&ograve; non essere raccordato. Inoltre, se si cede questo modello a una fonderia ricordarsi di sottolineare che esso ha le dimensioni che deve avere dopo il getto. La fonderia dovr&agrave; poi applicare una certa percentuale di restringimento al modello (rendendo il modello digitale utilizzato per fabbricare lo stampo pi&ugrave; grande in modo che dopo la fusione, quando il metallo si raffredda e si contrae, abbia il giusto formato).
<br clear="all">
</p><p><span id="Machining"></span>
</p>
<h2><span class="mw-headline" id="Lavorazione">Lavorazione</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-17.jpg&amp;filetimestamp=20130716182636&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-17.jpg" decoding="async" width="400" height="472" class="mw-file-element" data-file-width="663" data-file-height="782"></a><figcaption>Sketch per praticare il foro per le viti</figcaption></figure>
<p>Per togliere il materiale della lavorazione dall'interno del supporto, si pu&ograve; usare molto convenientemente il Corpo Scheletro stesso. Se non si vuole fare questo perch&eacute; dopo lo scheletro viene nascosto da qualche parte nell'albero della struttura, &egrave; anche possibile duplicare lo schizzo della funzione di rivoluzione dello scheletro e ricreare la rivoluzione in un nuovo corpo. Questo, per&ograve;, non &egrave; completamente parametrico, perch&eacute; il disegno duplicato &egrave; indipendente da quello originale, in questo modo se si cambia una dimensione si deve poi lavorare su entrambi i disegni. Le funzioni duplicate dipendenti saranno supportate in futuro.
</p><p>Per il resto della lavorazione, creare un nuovo corpo. La parte inferiore del supporto viene lavorato da un pad disegnato sul piano xy e esteso verso il basso. Successivamente, disegnare una rivoluzione per fare un foro per i bulloni. E' necessario fare il disegno sul piano XZ e ruotarlo in modo da poter utilizzare il diametro esterno del corpo scheletro come riferimento esterno. La parte superiore del disegno servir&agrave; a lavorare una superficie piana per la testa del bullone. Esso &egrave; dimensionato per lasciare almeno 5 mm di spessore nella parete del supporto. Se questo non lascia abbastanza spazio per la testa del bullone allora si pu&ograve; spostare verso l'alto il piano di Riferimento. Naturalmente, si potrebbe mettere questa logica nello scheletro, ma questo viene lasciato come esercizio per il lettore!
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-18.jpg&amp;filetimestamp=20130716182656&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-18.jpg" decoding="async" width="400" height="293" class="mw-file-element" data-file-width="985" data-file-height="722"></a><figcaption>Il corpo della lavorazione</figcaption></figure>
<p>&Egrave; possibile eseguire il mirroring della rivoluzione sugli assi YZ. L'immagine a destra mostra il "Corpo lavorazione". Naturalmente, la maggior parte delle dimensioni dei Pad e delle Rivoluzioni non sono importanti finch&eacute; vi &egrave; abbondanza di sovrapposizione.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-19.jpg&amp;filetimestamp=20130716184057&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-19.jpg" decoding="async" width="400" height="263" class="mw-file-element" data-file-width="1037" data-file-height="683"></a><figcaption>Il supporto finito con le lavorazioni</figcaption></figure>
<p>Infine, creare una operazione booleana per asportare il Corpo lavorazione dal Corpo principale. Se si desidera un piacevole effetto visivo, &egrave; possibile colorare le superfici lavorate in modo diverso dal resto del pezzo. Questo costituisce anche un utile controllo visivo per individuare eventuali lavorazioni dimenticate.
<br clear="all">
</p>
<h2><span class="mw-headline" id="Parte_Uno">Parte Uno</span></h2>
<p><a href="../it/PartDesign_Bearingholder_Tutorial_I.html" title="PartDesign Bearingholder Tutorial I/it">Tutorial di PartDesign Supporto per cuscinetto I</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20251007100017
Cache expiry: 86400
Reduced expiry: false
Complications: [show&#8208;toc]
CPU time usage: 0.129 seconds
Real time usage: 0.200 seconds
Preprocessor visited node count: 110/1000000
Post&#8208;expand include size: 1613/2097152 bytes
Template argument size: 145/2097152 bytes
Highest expansion depth: 4/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post&#8208;expand size: 2432/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%    7.516      1 -total
 48.84%    3.671      1 Template:TutorialInfo/it
 27.67%    2.080      1 Template:Caption
 18.81%    1.414      1 Template:Clear
-->

<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:10731-0!canonical and timestamp 20251007100017 and revision id 1656558. Rendering was triggered because: api-parse
 -->
</div>
</div><script src="../site.js"></script>