<link href="../site.css" rel="stylesheet" type="text/css"/>
<div class="mw-page-container"><h1 class="firstHeading mw-first-heading" id="firstHeading"><span class="mw-page-title-main">Macro Guitar Nut/pl</span></h1><div class="mw-parser-output"><div class="mw-pt-languages noprint" dir="ltr" lang="en"><div class="mw-pt-languages-label">Other languages:</div><ul class="mw-pt-languages-list"><li><a class="mw-pt-languages-ui mw-pt-progress mw-pt-progress--complete" dir="ltr" href="Macro_Guitar_Nut.html" lang="en" title="Macro Guitar Nut (100% translated)">English</a></li>
<li><a class="mw-pt-progress mw-pt-progress--complete" dir="ltr" href="Macro_Guitar_Nut.html" lang="fr" title="Macro Guitar Nut (100% translated)">français</a></li>
<li><a class="mw-pt-progress mw-pt-progress--complete" dir="ltr" href="Macro_Guitar_Nut.html" lang="it" title="Macro Guitar Nut (100% translated)">italiano</a></li>
<li><span class="mw-pt-languages-selected mw-pt-progress mw-pt-progress--stub" dir="ltr" lang="pl">polski</span></li></ul></div>
<table class="fcinfobox wikitable ct" style="float: right; width: 230px; margin-left: 10px;" width="100%">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;">
<p><span typeof="mw:File"><a class="mw-file-description" href="../File/Macro_Guitar_Nut.png"><img decoding="async" height="32" src="../File/Macro_Guitar_Nut.png" srcset="/images/thumb/9/94/Macro_Guitar_Nut.png/48px-Macro_Guitar_Nut.png 1.5x, /images/thumb/9/94/Macro_Guitar_Nut.png/64px-Macro_Guitar_Nut.png 2x" width="32"/></a></span><span> </span>
Macro Guitar Nut
</p>
</td></tr>
<tr>
<th class="ctOdd">Description
</th></tr>
<tr>
<td class="ctEven left macro-description">Create <a class="external text" href="https://wikipedia.org/wiki/Guitar#Nut" rel="nofollow">guitar nuts</a>.<br/>FreeCAD macro that will create complex guitar nut shapes.<br/>Specifically it can create a nut with the bottom of the string slots at the desired height above a fretboard of the desired radius. The diameter of each string is configurable and the slots can be configured to account for the width needed to prevent binding. See the <a href="#Usage">Usage</a> section for more details.<br/><br/>Macro version: 0.1<br/>Last modified: 2020-01-27<br/>FreeCAD version: All<br/>Download: <a class="external text" href="https://wiki.freecad.org/images/9/94/Macro_Guitar_Nut.png" rel="nofollow">ToolBar Icon</a><br/>Author: jsiddall<br/>
</td></tr>
<tr>
<th class="ctOdd">Author
</th></tr>
<tr>
<td class="ctEven macro-author"><a class="new" href="index.php?title=User;Jsiddall&amp;action=edit&amp;redlink=1.html" title="User:Jsiddall (page does not exist)">jsiddall</a>
</td></tr>
<tr>
<th class="ctOdd">Download
</th></tr>
<tr>
<td class="ctEven macro-download"><a class="external text" href="https://wiki.freecad.org/images/9/94/Macro_Guitar_Nut.png" rel="nofollow">ToolBar Icon</a>
</td></tr>
<tr>
<th class="ctOdd">Links
</th></tr>
<tr>
<td class="ctEven macro-Links"><a href="Macros_recipes.html" title="Macros recipes">Macros recipes</a><br/><a href="How_to_install_macros.html" title="How to install macros">How to install macros</a><br/><a href="Customize_Toolbars.html" title="Customize Toolbars">How to customize toolbars</a>
</td></tr>
<tr>
<th class="ctOdd">Macro Version
</th></tr>
<tr>
<td class="ctEven macro-version">0.1
</td></tr>
<tr>
<th class="ctOdd">Date last modified
</th></tr>
<tr>
<td class="ctEven macro-date">2020-01-27
</td></tr>
<tr>
<th class="ctOdd">FreeCAD Version(s)
</th></tr>
<tr>
<td class="ctEven FreeCAD-version">All
</td></tr>
<tr>
<th class="ctOdd">Default shortcut
</th></tr>
<tr>
<td class="ctEven"><i>None</i>
</td></tr>
<tr>
<th class="ctOdd">See also
</th></tr>
<tr>
<td class="ctEven"><a href="Macro_Guitar_fretboard.html" title="Macro Guitar fretboard">Macro_Guitar_fretboard</a>
</td></tr>
<tr>
<th class="ctOdd">
</th></tr>
<tr>
<td class="ctToc"><br/><div aria-labelledby="mw-toc-heading" class="toc" id="toc" role="navigation"><input class="toctogglecheckbox" id="toctogglecheckbox" role="button" style="display:none" type="checkbox"/><div class="toctitle" dir="ltr" lang="en"><h2 id="mw-toc-heading">Contents</h2><span class="toctogglespan"><label class="toctogglelabel" for="toctogglecheckbox"></label></span></div>
<ul>
<li class="toclevel-1 tocsection-1"><a href="#Description"><span class="tocnumber">1</span> <span class="toctext">Description</span></a></li>
<li class="toclevel-1 tocsection-2"><a href="#Usage"><span class="tocnumber">2</span> <span class="toctext">Usage</span></a></li>
<li class="toclevel-1 tocsection-3"><a href="#Limitations"><span class="tocnumber">3</span> <span class="toctext">Limitations</span></a></li>
<li class="toclevel-1 tocsection-4"><a href="#Script"><span class="tocnumber">4</span> <span class="toctext">Script</span></a></li>
<li class="toclevel-1 tocsection-5"><a href="#Link"><span class="tocnumber">5</span> <span class="toctext">Link</span></a></li>
</ul>
</div>
</td></tr>
</tbody></table>
<h2><span class="mw-headline" id="Description">Description</span></h2>
<p>Guitar Nut Maker is a FreeCAD macro script that creates complex guitar nut shape.
</p><p>This macro creates a nut with the bottom of the string slots at the desired height above a fretboard of the desired radius.  
</p><p><br/>
Slots can be made wider at the back of the nut then the face, and the slots can be created with the desired break angle. Slots can be on equal centers or have equal space between them. 
</p><p>The diameter of each string is configurable and the slots can be made a configurable amount wider than the string to prevent binding. The top of the nut is spherical and can be configured above/below the centerpoint of the strings. The edges of the nut are not shaped, nor is the top contoured from the face to the back, but these transformations can be applied manually in FreeCAD, or indeed after the part has been milled.
</p><p><span class="mw-default-size" typeof="mw:File"><a class="mw-file-description" href="../File/Nut_macro.png"><img decoding="async" height="440" src="../File/Nut_macro.png" width="800"/></a></span>
</p>
<p style="text-align:left; font-style:italic; width:800px; margin-left:1em; margin-right:1em;">Results using the Guitar Nut Maker macro</p>
<h2><span class="mw-headline" id="Usage">Usage</span></h2>
<ol><li>Download macro from the <a href="Std_AddonMgr.html" title="Std AddonMgr">Addon Manager</a></li>
<li>Execute macro</li></ol>
<h2><span class="mw-headline" id="Limitations">Limitations</span></h2>
<ul><li>Macro file must be edited with the desired nut parameters before use.</li></ul>
<div style="clear:both"></div>
<h2><span class="mw-headline" id="Script">Script</span></h2>
<p>ToolBar icon <span typeof="mw:File"><a class="mw-file-description" href="../File/Macro_Guitar_Nut.png"><img decoding="async" height="64" src="../File/Macro_Guitar_Nut.png" srcset="/images/thumb/9/94/Macro_Guitar_Nut.png/96px-Macro_Guitar_Nut.png 1.5x, /images/thumb/9/94/Macro_Guitar_Nut.png/128px-Macro_Guitar_Nut.png 2x" width="64"/></a></span>
</p><p><b>GuitarNut.FCMacro</b>
</p>
<pre># FreeCAD Guitar Nut Macro
# This macro creates a guitar/bass nut with conical slots at the
# desired spacing and diameter to export to CAM software 

__Name__ = 'Guitar Nut'
__Comment__ = 'This macro creates a guitar/bass nut'
__Author__ = 'Jeff Siddall'
__Version__ = '0.1'
__Date__ = '2020-01-27'
__License__ = 'GPL-3.0-or-later'
__Web__ = ''
__Wiki__ = ''
__Icon__ = 'https://wiki.freecad.org/images/9/94/Macro_Guitar_Nut.png'
__Help__ = 'Macro file must be edited with the desired nut parameters before use'
__Status__ = 'Beta'
__Requires__ = ''
__Communication__ = ''
__Files__ = ''

import FreeCAD, Part, math
from FreeCAD import Base, Vector

class Nut():
    if App.ActiveDocument is None:
        # Create new document called "Nut" if there is no open document
        doc = App.newDocument("Nut")

# Enter desired values below
# Unless specified, units are mm
equalcenters = 0 # If equalcenters = 1 then the spacing of the strings is equal; if 0 then the space between the strings is equal
strings = 5 # Number of strings

# Always enter values below with a decimal point, even if that means adding ".0" on the end!
length = 49.0 # Nut length (neck width); 38.1 mm = 1.5", 41.275 = 1-5/8"
width = 6.350 # Nut width; 3.175 mm = 1/8"; 6.35 mm = 1/4"
fretboardmaxheight = 6.350 # Maximum fretboard height above the bottom of the nut slot; 6.35 mm = 1/4"
radius = 184.15 # Fretboard radius; 184.15 mm = 7.25"; 304.8 = 12"; 406.4 mm = 16"
# List of string thicknesses, starting at bottom string, separated by commas, enclosed in square brackets
# Bottom string 1.143 mm = 0.045" 
# 1.651 mm = 0.065"
# 2.159 mm = 0.085"
# Top string on a 4 string 2.667 mm = 0.105"
# Top string on a 5 string 3.175 mm = 0.125"
stringthickness = [1.143, 1.651, 2.159, 2.667, 3.175] # 5 string bass, 45-125/ 4 string bass 45-105
#stringthickness = [3.175, 2.667, 2.159, 1.651, 1.143] # Reverse string, 5 string bass, 45-125/ 4 string bass 45-105
#stringthickness = [0.254, 0.3302, 0.4318, 0.6604, 0.9144, 1.1684] # 6 string guitar, 10-46
stringheight = 1.1938 # Height of bottom of strings above fretboard; 1.1938 mm = 0.047" or the height of a typical medium/jumbo fret
slotmargin = 0.05 # extra slot width on each side of the string; 0.05 mm = 0.00197"
overhang = 3.0 # Distance from edge of each outside string to end of nut
breakangle = 14.0 # Angle of the nut slot in degrees; this should be greater than the actual string angle to ensure the string only contacts at the leading edge of the nut
slotradincrease = 0.2 # How much bigger the radius of the end of the slot is than the face
slotdepthfactor = 1.3 # Factor to control how deep the slots should be.  Values greater than 1 create deeper slots than default.
toparcoffsetfactor = 1.8 # Factor to control how far off-center the nut top arc is.  Adjust as required.
# End of user configuration variables
# Do not make any changes below this line!

stringindex = 0 # Start at the bottom string
stringspacing = 0

# Find the centers of the outside strings
# Bottom string
center1 = (length / 2) - overhang - (stringthickness[0] / 2)

# Top string
center2 = -((length / 2) - overhang - (stringthickness[strings - 1] / 2))

# Outside string values
outsidestringradiusdiff = (stringthickness[strings - 1] - stringthickness[0]) / 2
outsidestringavgradius = (stringthickness[strings - 1] + stringthickness[0]) / 2 / 2
centerspacing = center1 - center2

# Find the string spacings for both spacing models
if equalcenters:
    # Calculate the correct spacing for equal spaced strings
    stringspacing = centerspacing / (strings - 1)

else:
    # Calculate the space between strings
    totalstringwidth = 0
    stringindex1 = 0
    while (stringindex1 &lt; strings):
        totalstringwidth = totalstringwidth + stringthickness[stringindex1]
        stringindex1 = stringindex1 + 1

    stringspacing = (centerspacing - totalstringwidth + (2 * outsidestringavgradius)) / (strings - 1)

print("Creating nut blank")
# Height is much larger than needed but will be cut down with the "common" operation later
nutshape = Part.makeBox(width, length, ((fretboardmaxheight + stringheight) * 2), Vector(-width, -(length / 2), 0))

print("Creating nut top surface")
# Make a sphere to shape the top of the nut, which should pass through  each string center
# Because the thickness of the strings varies, the Y-position of the sphere needs to be compensated
# The fretboard "z" portion is:
fretboardz = radius - (((radius ** 2) - ((centerspacing / 2) ** 2)) ** 0.5)

# The formula to calculate the effective radius of the center of outside strings is:
# r^2 = z^2 + y^2
# r^2 = ((r - (outsidestringradiusdiff + fretboardz))^2) + ((centerspacing/2)^2)
# r^2 = r^2 - 2r*(outsidestringradiusdiff + fretboardz) + ((outsidestringradiusdiff + fretboardz)^2) + (centerspacing^2)
# 2r*(outsidestringradiusdiff + fretboardz) = ((outsidestringradiusdiff + fretboardz)^2) + (centerspacing^2)
# r  = ((outsidestringradiusdiff + fretboardz)/2) + ((centerspacing^2)/(2*(outsidestringradiusdiff + fretboardz)))
nutradius = ((abs(outsidestringradiusdiff / 4) + fretboardz) / 2) + (((centerspacing / 2) ** 2) / (2 * (abs(outsidestringradiusdiff / 4) + fretboardz)))

# The center of the arc of the nut radius must also be offset
# This formula was derived empirically so might nead adjusting
yoffset = -centerspacing / 2 * toparcoffsetfactor * (outsidestringradiusdiff / (2 * outsidestringavgradius)) * (1 - (nutradius / radius))

top = Part.makeSphere(nutradius, Vector(0, yoffset, (-nutradius + fretboardmaxheight + stringheight + (outsidestringavgradius * slotdepthfactor) + slotmargin)))

nutshape = nutshape.common(top)

cumulativestringwidth = 0 # Add up the amount of string thickness for equal spacing

# Build the slots
while (stringindex &lt; strings):
    print("Creating slot for string " + str(stringindex))
    ypos = 0

    if equalcenters:
        # For equal centers move each string over by the fixed amount of stringspacing
        ypos = center1 - (stringindex * stringspacing)

    else:
        # For equal spacing adjust for the thickness of each string

        # Add up the cumulative string thickness
        if stringindex == 0:
            # For the first string the thickness is already included in center1 so don't add anything
            cumulativestringwidth = 0

        else:
            # Add half the previous string and half this string
            cumulativestringwidth = cumulativestringwidth + (stringthickness[stringindex] / 2) + (stringthickness[stringindex - 1] / 2)

        ypos = center1 - (stringindex * stringspacing) - cumulativestringwidth

    zstartpos = (((radius ** 2) - (ypos ** 2)) ** 0.5) - radius + fretboardmaxheight + stringheight + (stringthickness[stringindex] / 2) + slotmargin # Cartesian coordinate formula: z = sqrt(r^2 - y^2)
    # calculate the end of the slot based on the string break angle 
    zendpos = zstartpos - (math.tan(math.radians(breakangle)) * width)

    slotstartrad = (stringthickness[stringindex] / 2) + slotmargin
    slotendrad = slotstartrad + slotradincrease

    # Make the string slot as 2 circles offset in the Z axis to create the break angle, then made into a face, then extruded up to allow the slot to protrude to the nut surface
    slotstart = Part.makeCircle(slotstartrad, Vector(0, ypos, zstartpos), Vector(1, 0, 0), 180, 360)
    slotend = Part.makeCircle(slotendrad, Vector(-width, ypos, zendpos), Vector(1, 0, 0), 180, 360)
    slotbottom = Part.makeRuledSurface(slotstart, slotend)
    slotextrude = slotbottom.extrude(Vector(0, 0, ((fretboardmaxheight + stringheight) * 2)))

    nutshape = nutshape.cut(slotextrude)
    stringindex = stringindex + 1

nut = App.ActiveDocument.addObject("Part::Feature","Nut")
nut.Shape = nutshape
print("Finished creating nut")</pre>
<h2><span class="mw-headline" id="Link">Link</span></h2>
<p>Forum discussion <a class="external text" href="https://forum.freecadweb.org/viewtopic.php?f=24&amp;t=5827&amp;" rel="nofollow">Guitar fretboard macro / guitar body</a>
</p>
<!-- 
NewPP limit report
Cached time: 20241129212903
Cache expiry: 86400
Reduced expiry: false
Complications: [show‐toc, no‐toc‐conversion]
CPU time usage: 0.047 seconds
Real time usage: 0.091 seconds
Preprocessor visited node count: 113/1000000
Post‐expand include size: 2635/2097152 bytes
Template argument size: 8650/2097152 bytes
Highest expansion depth: 5/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post‐expand size: 8573/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%    9.300      1 -total
 42.44%    3.947      1 Template:Macro
 24.46%    2.275      1 Template:MacroCode
 16.69%    1.552      1 Template:Caption
 13.74%    1.278      1 Template:Clear
-->
<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:290067-0!canonical and timestamp 20241129212903 and revision id 1344608. Rendering was triggered because: api-parse
 -->
</div></div><script src="../script.js"></script>
