<link href="../site.css" rel="stylesheet" type="text/css"/><div class="mw-page-container"><h1 id="firstHeading" class="firstHeading mw-first-heading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial II/pl</span></h1><?xml encoding="UTF-8"><div class="mw-content-ltr mw-parser-output" lang="pl" dir="ltr"><div id="itsfree" style="text-align:center; background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">
<figure class="mw-halign-left" typeof="mw:File"><span><img src="https://upload.wikimedia.org/wikipedia/commons/d/d5/Under_construction_icon-blue.svg" decoding="async" width="45" height="38" class="mw-file-element" data-file-width="600" data-file-height="500"></span><figcaption></figcaption></figure> This documentation is a work in progress. Please don't mark it as translatable since it will change in the next hours and days.
</div><div style="clear:both"></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img src="../File/Freecad.svg" decoding="async" width="32" height="32" class="mw-file-element" data-file-width="48" data-file-height="48"></span></span> &#262;wiczenie
</td></tr>
<tr>
<th class="ctOdd">Temat
</th></tr>
<tr>
<td class="ctEven">Modelowanie
</td></tr>
<tr>
<th class="ctOdd">Poziom trudno&#347;ci
</th></tr>
<tr>
<td class="ctEven">U&#380;ytkownik zaawansowany
</td></tr>
<tr>
<th class="ctOdd">Czas wykonania
</th></tr>
<tr>
<td class="ctEven">nieokre&#347;lony
</td></tr>
<tr>
<th class="ctOdd">Autorzy
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">Wersja FreeCAD
</th></tr>
<tr>
<td class="ctEven">0.19.23300 lub nowszy
</td></tr>
<tr>
<th class="ctOdd">Pliki z przyk&#322;adami
</th></tr>
<tr>
<td class="ctEven">brak
</td></tr>
<tr>
<th class="ctOdd">Zobacz r&oacute;wnie&#380;
</th></tr>
<tr>
<td class="ctEven"><i>-</i>
</td></tr>
<tr>
<td class="ctToc"><br><meta property="mw:PageProp/toc">
</td></tr></tbody></table>
<div id="itsfree" class="warning-box">{{{1}}}</div>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-19.jpg&amp;filetimestamp=20130716184057&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-19.jpg" decoding="async" width="400" height="263" class="mw-file-element" data-file-width="1037" data-file-height="683"></a><figcaption>Poradnik dotycz&#261;cy oprawki &#322;o&#380;yska - Gotowa oprawka &#322;o&#380;yska <i>(g&oacute;ra)</i></figcaption></figure>
<p><strike>  
Jak wskazuje ostrze&#380;enie na g&oacute;rze strony, ten <b>samouczek NIE ZADZIA&#321;A, chyba &#380;e skompilujesz specjaln&#261;, wysoce eksperymentaln&#261; ga&#322;&#261;&#378; kodu &#378;r&oacute;d&#322;owego FreeCAD</b> i jest to wprowadzaj&#261;cy samouczek do modelowania w &#347;rodowisku pracy Projekt Cz&#281;&#347;ci w FreeCAD <b>z u&#380;yciem p&#322;aszczyzn konstrukcyjnych, kt&oacute;re s&#261; funkcj&#261; jeszcze niedost&#281;pn&#261; w wi&#281;kszo&#347;ci wersji FreeCAD</b>.  
</strike>
</p>
<h2><span id="Cel_w_skr.C3.B3cie"></span><span class="mw-headline" id="Cel_w_skr&oacute;cie">Cel w skr&oacute;cie</span></h2>
<p>Celem tego samouczka jest wprowadzenie Ci&#281; do dw&oacute;ch r&oacute;&#380;nych sposob&oacute;w pracy przy tworzeniu odlewanego elementu z pochyleniami i zaokr&#261;gleniami. W zale&#380;no&#347;ci od tego, z jakimi innymi programami CAD mia&#322;e&#347; do czynienia, jeden z tych sposob&oacute;w mo&#380;e by&#263; Ci ju&#380; znany. Jako przyk&#322;ad praktyczny b&#281;dziemy modelowa&#263; prosty uchwyt &#322;o&#380;yska.
</p><p>To jest druga cz&#281;&#347;&#263; samouczka. B&#281;dzie ona wykorzystywa&#263; to, co mo&#380;na nazwa&#263; podej&#347;ciem 'wielobry&#322;owym' na przyk&#322;adzie (prostszej) g&oacute;rnej cz&#281;&#347;ci uchwytu.
</p><p>Oczywi&#347;cie, aby przej&#347;&#263; przez ten poradnik nale&#380;y aktywowa&#263; &#347;rodowisko pracy Projekt Cz&#281;&#347;ci.
</p><p><strike>Mo&#380;esz znale&#378;&#263; moj&#261; wersj&#281; elementu stworzonego w tym samouczku [<a rel="nofollow" class="external text" href="http://ubuntuone.com/39PTZ3Y3LUnmZzpZQPcJT4">tutaj</a>]</strike> <i>Plik nie jest ju&#380; dost&#281;pny, nowy zostanie udost&#281;pniony w p&oacute;&#378;niejszym terminie</i>. <br clear="all">
</p><p><span id="Design_data"></span>
</p>
<h2><span class="mw-headline" id="Dane_projektowe">Dane projektowe</span></h2>
<p>Uchwyt powinien by&#263; w stanie pomie&#347;ci&#263; &#322;o&#380;ysko o &#347;rednicy 90 mm i szeroko&#347;ci do 33 mm (np. typ DIN 630 2308, kt&oacute;re ma &#347;rednic&#281; wewn&#281;trzn&#261; 40 mm). &#321;o&#380;ysko wymaga w uchwycie (i na wale) ko&#322;nierza o wysoko&#347;ci co najmniej 4,5 mm. G&oacute;rna cz&#281;&#347;&#263; uchwytu b&#281;dzie przykr&#281;cona do dolnej dwoma &#347;rubami M12. G&#322;owa takiej &#347;ruby wymaga co najmniej 20 mm wolnej przestrzeni. Po obu stronach &#322;o&#380;yska powinna znajdowa&#263; si&#281; rowek umo&#380;liwiaj&#261;cy zamocowanie standardowego pier&#347;cienia uszczelniaj&#261;cego wa&#322; DIN 3760: 38x55x7 lub 40x55x7 po jednej stronie, 50x68x8 po drugiej stronie.
</p><p>Uchwyt b&#281;dzie odlewem piaskowym o minimalnej grubo&#347;ci &#347;cianki 5 mm, k&#261;cie pochylenia 2 stopni oraz minimalnym promieniu zaokr&#261;glenia 3 mm.
</p><p><br clear="all">
</p><p><span id="Setting_up_the_skeleton_geometry"></span>
</p>
<h2><span class="mw-headline" id="Ustawienie_szkieletu_geometrii">Ustawienie szkieletu geometrii</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-2.png&amp;filetimestamp=20160718193124&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-2.png" decoding="async" width="400" height="149" class="mw-file-element" data-file-width="1260" data-file-height="468"></a><figcaption>Szkic szkieletu geometrii</figcaption></figure>
<p>Utw&oacute;rz nowy element w &#347;rodowisku pracy Projekt Cz&#281;&#347;ci. Zmie&#324; nazw&#281; domy&#347;lnie tworzonej Zawarto&#347;ci na Szkielet. Ta Zawarto&#347;&#263; prawdopodobnie jest ju&#380; aktywowana, co mo&#380;na zobaczy&#263; po niebieskim tle w drzewku funkcji. Utw&oacute;rz nowy szkic na p&#322;aszczy&#378;nie YZ, zawieraj&#261;cy zarys wa&#322;u, &#322;o&#380;yska i pier&#347;cieni uszczelniaj&#261;cych. Po zako&#324;czeniu szkicu utw&oacute;rz z niego cech&#281; obr&oacute;cenia. Ta funkcja szkieletu b&#281;dzie p&oacute;&#378;niej u&#380;ywana jako odniesienie dla rzeczywistej geometrii. Oznacza to, &#380;e je&#347;li b&#281;dziesz chcia&#322; zmieni&#263; jakiekolwiek wymiary, wystarczy dostosowa&#263; wymiary funkcji szkieletu, a reszta elementu zostanie odpowiednio zaktualizowana.
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-2-1.jpg&amp;filetimestamp=20130711190937&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-2-1.jpg" decoding="async" width="400" height="260" class="mw-file-element" data-file-width="1058" data-file-height="687"></a><figcaption>Szkielet geometrii</figcaption></figure>
<p><br clear="all">
</p><p><span id="The_main_body"></span>
</p>
<h2><span id="G.C5.82.C3.B3wna_Zawarto.C5.9B.C4.87"></span><span class="mw-headline" id="G&#322;&oacute;wna_Zawarto&#347;&#263;">G&#322;&oacute;wna Zawarto&#347;&#263;</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-3.jpg&amp;filetimestamp=20130711184543&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-3.jpg" decoding="async" width="400" height="298" class="mw-file-element" data-file-width="1040" data-file-height="774"></a><figcaption>Szkic pierwszego wyci&#261;gni&#281;cia</figcaption></figure>
<p>Utw&oacute;rz now&#261; Zawarto&#347;&#263; i aktywuj j&#261;. Szkic pierwszego wyci&#261;gni&#281;cia pokazano po prawej stronie. Zosta&#322; on umieszczony na p&#322;aszczy&#378;nie datum z odsuni&#281;ciem 5 mm (grubo&#347;&#263; &#347;cianki) od powierzchni szkieletu wyznaczaj&#261;cej stron&#281; jednego z pier&#347;cieni uszczelniaj&#261;cych &#322;o&#380;yska. Poniewa&#380; wszystkie wa&#380;ne wymiary s&#261; pobierane ze szkieletu, s&#261; tylko trzy wymiary: zapas obr&oacute;bkowy (3 mm) u podstawy jako odsuni&#281;cie od p&#322;aszczyzny XY, 5 mm grubo&#347;ci &#347;cianki od &#347;rednicy zewn&#281;trznej szkieletu oraz k&#261;t nachylenia (draft) 2 stopnie. Aby utworzy&#263; wymiar 5 mm, nale&#380;y najpierw wybra&#263; zewn&#281;trzny okr&#261;g (promie&#324; 45 mm) szkieletu geometrii jako geometri&#281; zewn&#281;trzn&#261; w szkicowniku, a nast&#281;pnie wstawi&#263; lini&#281; konstrukcyjn&#261; ograniczon&#261; stycznie do tego okr&#281;gu i pod k&#261;tem dw&oacute;ch stopni.
</p><p>Pewnie zastanawiasz si&#281;, dlaczego na dole ka&#380;dego &#322;uku znajduje si&#281; ten ma&#322;y prosty odcinek. Odcinek ten zapewnia, &#380;e na &#322;ukach b&#281;dzie zachowany k&#261;t pochylenia 2 stopnie. Mo&#380;e si&#281; to wydawa&#263; du&#380;o pracy dla niewielkiej korzy&#347;ci, ale wiele program&oacute;w CAD (a by&#263; mo&#380;e kiedy&#347; r&oacute;wnie&#380; FreeCAD) posiada narz&#281;dzia, kt&oacute;re pod&#347;wietlaj&#261; model bry&#322;owy r&oacute;&#380;nymi kolorami i od razu pokazuj&#261; wszystkie powierzchnie, na kt&oacute;rych k&#261;t nachylenia nie jest prawid&#322;owy. Nie chcesz, aby co&#347; takiego sta&#322;o si&#281; z Twoim modelem, zw&#322;aszcza po dodaniu wielu zaokr&#261;gle&#324;!
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-4.jpg&amp;filetimestamp=20130711185009&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-4.jpg" decoding="async" width="400" height="279" class="mw-file-element" data-file-width="1117" data-file-height="780"></a><figcaption>Pierwsze wyci&#261;gni&#281;cie</figcaption></figure>
<p>Po uko&#324;czeniu szkicu (co mo&#380;e by&#263; nieco trudne z powodu stycznych linii pod k&#261;tem 2 stopni) utw&oacute;rz z niego wyci&#261;gni&#281;cie rozci&#261;gaj&#261;ce si&#281; do drugiej strony szkieletu geometrii, ponownie z odsuni&#281;ciem 5 mm od powierzchni bocznej. Tym razem nie trzeba tworzy&#263; p&#322;aszczyzny konstrukcyjnej &mdash; tryb "do powierzchni" w oknie dialogowym wyci&#261;gni&#281;cia pozwala wprowadzi&#263; odsuni&#281;cie.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-5.jpg&amp;filetimestamp=20130711190315&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-5.jpg" decoding="async" width="400" height="313" class="mw-file-element" data-file-width="899" data-file-height="703"></a><figcaption>Szkic do wyci&#281;cia przez wyci&#261;gni&#281;cie</figcaption></figure>
<p>Nast&#281;pnie usuniemy troch&#281; materia&#322;u na obu ko&#324;cach wyci&#261;gni&#281;cia, poniewa&#380; w przypadku odlew&oacute;w zawsze najlepiej jest, gdy grubo&#347;&#263; &#347;cianki jest mo&#380;liwie jak najbardziej jednolita. Utw&oacute;rz szkic na ka&#380;dej z ko&#324;cowych powierzchni wyci&#261;gni&#281;cia i wymiaruj go z odsuni&#281;ciem 5 mm od ko&#322;a reprezentuj&#261;cego pier&#347;cie&#324; uszczelniaj&#261;cy &#322;o&#380;yska (promie&#324; 27,5 mm po jednej stronie i 34 mm po drugiej). Dla dolnego odcinka linii szkicu utw&oacute;rz kolejn&#261; geometri&#281; zewn&#281;trzn&#261; z wyci&#261;gni&#281;cia i ogranicz do niej szkic. W ten spos&oacute;b szkic ma tylko jeden wymiar, czyli grubo&#347;&#263; &#347;cianki 5 mm (wymiary 150 mm i 75 mm nie s&#261; istotne, dop&oacute;ki s&#261; wystarczaj&#261;co du&#380;e, aby zapewni&#263; wyci&#281;cie ca&#322;ego materia&#322;u). 
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-6.jpg&amp;filetimestamp=20130711190430&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-6.jpg" decoding="async" width="400" height="277" class="mw-file-element" data-file-width="1063" data-file-height="736"></a><figcaption>Wyci&#261;gni&#281;cie z wyci&#281;ciami w celu uzyskania jednolitej grubo&#347;ci &#347;cianki</figcaption></figure>
<p>U&#380;yj utworzonego szkicu, aby wykona&#263; Kiesze&#324; i przed&#322;u&#380; j&#261; do powierzchni geometrii szkieletu reprezentuj&#261;cej &#322;o&#380;ysko, z odj&#281;ciem 5 mm na grubo&#347;&#263; &#347;cianki. W przypadku drugiej Kieszeni mo&#380;esz skorzysta&#263; z opcji "Duplikuj wybrany obiekt" w menu Edycja, aby skopiowa&#263; ju&#380; wykonany szkic (je&#347;li pojawi si&#281; pytanie, wybierz nie duplikowa&#263; obiekt&oacute;w zale&#380;nych). Nast&#281;pnie wybierz powierzchni&#281;, na kt&oacute;r&#261; chcesz przenie&#347;&#263; szkic, i naka&#380; FreeCAD, aby przypisa&#322; szkic do tej powierzchni (jest to opcja w menu &#347;rodowiska Projekt Cz&#281;&#347;ci). Po utworzeniu drugiej Kieszeni mo&#380;esz obejrze&#263; wynik od spodu, aby sprawdzi&#263;, czy grubo&#347;&#263; &#347;cianki wok&oacute;&#322; konturu geometrii szkieletu wynosi jednolite 5 mm. 
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-7.jpg&amp;filetimestamp=20130711192218&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-7.jpg" decoding="async" width="400" height="226" class="mw-file-element" data-file-width="1085" data-file-height="614"></a><figcaption>P&#322;aszczyzna neutralna do zastosowania pochylenia</figcaption></figure>
<p>Teraz nadszed&#322; czas na utworzenie pochyle&#324; i zaokr&#261;gle&#324;. Funkcja pochylenia wymaga p&#322;aszczyzny neutralnej, co oznacza, &#380;e geometria przeci&#281;ta przez t&#281; p&#322;aszczyzn&#281; pozostanie na swoim miejscu, podczas gdy reszta powierzchni zostanie pochylona pod zadanym k&#261;tem. U&#380;ycie do tego celu dolnej powierzchni wyci&#261;gni&#281;cia nie jest dobrym pomys&#322;em, poniewa&#380; grubo&#347;&#263; &#347;cianki w g&oacute;rnej cz&#281;&#347;ci uchwytu sta&#322;aby si&#281; mniejsza ni&#380; 5 mm. Dlatego tworzymy p&#322;aszczyzn&#281; datum odsuni&#281;t&#261; o oko&#322;o 35 mm od p&#322;aszczyzny XY. Aktywuj Zawarto&#347;&#263; ze szkieletem i utw&oacute;rz tam p&#322;aszczyzn&#281;, poniewa&#380; b&#281;dziemy jej potrzebowa&#263; tak&#380;e do zastosowania pochylenia do innych obiekt&oacute;w. 
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-8.jpg&amp;filetimestamp=20130711192240&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-8.jpg" decoding="async" width="400" height="233" class="mw-file-element" data-file-width="1106" data-file-height="644"></a><figcaption>Pierwsza Zawarto&#347;&#263; z zastosowanym pochyleniem i zaokr&#261;gleniami</figcaption></figure>
<p>Obrazek po prawej stronie pokazuje uko&#324;czon&#261; pierwsz&#261; Zawarto&#347;&#263; z zastosowanym pochyleniem i zaokr&#261;gleniami. Zauwa&#380;, &#380;e zewn&#281;trzne (wkl&#281;s&#322;e) kraw&#281;dzie maj&#261; wi&#281;kszy promie&#324; zaokr&#261;glenia wynosz&#261;cy 5 mm, ponownie w celu uzyskania bardziej jednolitej grubo&#347;ci &#347;cianki (wi&#281;cej ni&#380; 5 mm nie jest mo&#380;liwe, poniewa&#380; po obr&oacute;bce wn&#281;trza uchwytu grubo&#347;&#263; &#347;cianki sta&#322;aby si&#281; mniejsza ni&#380; 5 mm). <br clear="all">
</p><p><span id="Adding_the_bodies_for_the_bolts"></span>
</p>
<h2><span id="Dodawanie_zawarto.C5.9Bci_dla_.C5.9Brub"></span><span class="mw-headline" id="Dodawanie_zawarto&#347;ci_dla_&#347;rub">Dodawanie zawarto&#347;ci dla &#347;rub</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-13.jpg&amp;filetimestamp=20130716175052&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-13.jpg" decoding="async" width="400" height="333" class="mw-file-element" data-file-width="730" data-file-height="607"></a><figcaption>Szkic dla Zawarto&#347;ci dla &#347;rub</figcaption></figure>
<p>&#346;ruby wymagaj&#261; dw&oacute;ch cylindrycznych Zawarto&#347;ci po obu stronach g&#322;&oacute;wnej Zawarto&#347;ci. Najlepiej uwzgl&#281;dni&#263; k&#261;t pochylenia 2 stopni ju&#380; w szkicu. Pr&oacute;bowa&#322;em obr&oacute;ci&#263; cylinder, a potem zastosowa&#263; pochylenie, ale po odbiciu lustrzanym dzia&#322;y si&#281; dziwne rzeczy i nie mog&#322;em doda&#263; zaokr&#261;gle&#324;, poniewa&#380; powierzchnia w jaki&#347; spos&oacute;b si&#281; zniekszta&#322;ci&#322;a.
</p><p>The sketch is dimensioned so that the rotation axis is 12mm distance to the outer diameter of the skeleton Body, 7mm for the radius of the hole plus 5mm for the wall thickness. For the sake of having a fully parametric part, it is a good idea to add a plane to the Skeleton about 25mm above the XY-plane to mark the top of the cylinders. Since this will be machined, the sketch is dimensioned 3mm above it.
</p><p><br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-14.jpg&amp;filetimestamp=20130715192541&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-14.jpg" decoding="async" width="400" height="244" class="mw-file-element" data-file-width="987" data-file-height="601"></a><figcaption>The body for the bolts</figcaption></figure>
<p>Create a revolution from the sketch and apply a fillet of 4mm to the top. This means that after machining away 3mm, a slight radius will remain which helps to avoid a sharp edge where someone could cut their hand when tightening the bolt.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-16.jpg&amp;filetimestamp=20130715192912&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-16.jpg" decoding="async" width="400" height="261" class="mw-file-element" data-file-width="868" data-file-height="566"></a><figcaption>The main body with the two bodies for the bolts</figcaption></figure>
<p>Create a boolean feature to fuse the main Body and the bolt body. Then create a new body for the other side. Duplicate the sketch of the revolution, move it to this body and create the second body for the bolts (mirroring a Body is not supported yet so you need to redo most of it). Then fuse this second body into the main Body as well. Finally, apply a large fillet on the edge created by the boolean fuse operation. The largest I could get was 4mm.
<br clear="all">
</p>
<h2><span class="mw-headline" id="Hollowing_out_the_main_body">Hollowing out the main body</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-9.jpg&amp;filetimestamp=20130714182319&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-9.jpg" decoding="async" width="300" height="347" class="mw-file-element" data-file-width="477" data-file-height="551"></a><figcaption>The first Pad of the cut-out body inside the main body</figcaption></figure>
<p>We will now work on the inside of the holder and hollow it out to make space for the bearing and sealing rings. When doing this of course we need to keep in mind the 3mm machining allowance. Since this tutorial teaches the multi-body method, we will create the inside geometry as a separate body and then cut it out of the main body with a boolean operation.
</p><p>Create a new body and make it active. First, we need a datum plane offset 3mm inside the skeleton face that shows the side of the bearing. Then, duplicate the sketch of the first Pad of the main body. It will be added to the main body, so right-click on it and choose to move it to the newly created body (this option is only available in the context menu if the PartDesign workbench is active). Map the sketch onto the datum plane (if the sketch turns upside-down after mapping, move the datum plane to the other side of the bearing, next to where the duplicated sketch is located). Now, modify the sketch so that the diameter is 3mm less than the outer diameter of the skeleton geometry that represents the bearing. All you need to do is remove the 5mm dimension, drag the sketch inside the reference circle, and create a new 3mm dimension.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-10.jpg&amp;filetimestamp=20130714183706&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-10.jpg" decoding="async" width="400" height="218" class="mw-file-element" data-file-width="1013" data-file-height="551"></a><figcaption>The cut-out body inside the skeleton body</figcaption></figure>
<p>Next we want two more Pads to hollow out the place for the sealing rings. Duplicate the sketch of the first pad of the cut-out Body and map it to the XZ-plane. Edit the sketch and replace the external reference with the outer diameter of the bearing sealing ring. Extrude this sketch to an offset of 3mm of the side of the sealing ring. Repeat the whole process for the sealing ring on the other side.
</p><p>After this we want to create two more Pads like the last two to give the shaft a clearance (e.g. 3mm) inside the holder.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-11.jpg&amp;filetimestamp=20130714184941&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-11.jpg" decoding="async" width="400" height="200" class="mw-file-element" data-file-width="1055" data-file-height="527"></a><figcaption>The complete cut-out body (minus impossible fillets)</figcaption></figure>
<p>Now all that remains is to apply draft to the planar side faces, using the same neutral plane as for the main body, and filleting. Apply a general fillet of 3mm to all edges. You will notice that there are several edges that cannot be filleted... this is a defect of the underlying geometric kernel which FreeCAD uses.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-15.jpg&amp;filetimestamp=20130715192602&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-15.jpg" decoding="async" width="400" height="237" class="mw-file-element" data-file-width="974" data-file-height="576"></a><figcaption>The completed raw part of the holder (without machining)</figcaption></figure>
<p>We are ready to hollow out the main body. Select it and choose to create a new Boolean operation. Add the cut-out body to the list window and set the operation to "Cut". Put a 3mm fillet on the two edges resulting from the cut-out operation (again some edges remain that are "unfilletable"). The result should look like the picture on the right.
</p><p>The raw part is now completed. This is what the holder will look like before machining. Note that since the mold will have a top and bottom half, the edge between these two cannot be filleted. Also, if you give away this model to a foundry make sure to point out that it has the dimensions after casting. The foundry will then have to apply a certain percentage of shrinkage to the model (making the digital model used to manufacture the mold larger so that when the metal cools down and shrinks after casting it will have the right size).
<br clear="all">
</p>
<h2><span class="mw-headline" id="Machining">Machining</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-17.jpg&amp;filetimestamp=20130716182636&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-17.jpg" decoding="async" width="400" height="472" class="mw-file-element" data-file-width="663" data-file-height="782"></a><figcaption>Sketch to "drill" the hole for the bolts</figcaption></figure>
<p>To take away the material for machining the inside of the holder, very conveniently we can use the Skeleton Body itself. If you don't want that because then the skeleton gets hidden somewhere deep in the tree, you can also duplicate the sketch of the skeleton Revolution feature and re-create the revolution in another body. This is not completely parametric, though, because the duplicated sketch is independent of the original, so you will have to work on both if you change a dimension. Dependent duplicated features might be supported in the future sometime.
</p><p>For the rest of the machining, create a new Body. The bottom of the holder will be machined by a Pad sketched on the XY-plane extending downwards. Next, sketch a revolution to make a hole for the bolts. You will need to sketch on the XZ-plane and revolve it so that you can choose the outer diameter of the skeleton Body as an external reference. The top part of the sketch will serve to machine a flat place for the head of the bolt. It is dimensioned to leave at least 5mm wall thickness in the holder. If this does not give enough space for the bolt head then you can move the datum plane upwards. Of course, you could put this logic into the Skeleton, which is left as an exercise to the reader!
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-18.jpg&amp;filetimestamp=20130716182656&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-18.jpg" decoding="async" width="400" height="293" class="mw-file-element" data-file-width="985" data-file-height="722"></a><figcaption>The machining Body</figcaption></figure>
<p>You can mirror the revolution on the YZ-axis. The picture on the right shows the "machining" Body. Of course, most of the dimensions of the Pads and Revolutions are not important as long as there is plenty of overlap.
<br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-19.jpg&amp;filetimestamp=20130716184057&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-19.jpg" decoding="async" width="400" height="263" class="mw-file-element" data-file-width="1037" data-file-height="683"></a><figcaption>The finished Holder with machining</figcaption></figure>
<p>Finally, create a boolean operation to cut the machining Body out of the main Body. If you want a nice visual effect, you can colour the machined surfaces differently from the rest of the part. This is also a useful optical feedback showing you whether you forgot to machine somewhere.
<br clear="all">
</p>
<h2><span id="Cz.C4.99.C5.9B.C4.87_pierwsza"></span><span class="mw-headline" id="Cz&#281;&#347;&#263;_pierwsza">Cz&#281;&#347;&#263; pierwsza</span></h2>
<p><a href="../pl/PartDesign_Bearingholder_Tutorial_I.html" title="PartDesign Bearingholder Tutorial I/pl">Poradnik: Projekt cz&#281;&#347;ci, uchwyt &#322;o&#380;yska cze&#347;&#263; 1</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20251002115956
Cache expiry: 86400
Reduced expiry: false
Complications: [show&#8208;toc]
CPU time usage: 0.059 seconds
Real time usage: 0.092 seconds
Preprocessor visited node count: 108/1000000
Post&#8208;expand include size: 1256/2097152 bytes
Template argument size: 81/2097152 bytes
Highest expansion depth: 3/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post&#8208;expand size: 0/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%   12.650      1 -total
 39.19%    4.958      1 Template:TutorialInfo/pl
 32.20%    4.073      1 Template:Page_in_progress
 13.12%    1.660      1 Template:VeryImportantMessage
 12.04%    1.523      1 Template:Clear
-->

<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:182939-0!canonical and timestamp 20251002115956 and revision id 1654248. Rendering was triggered because: edit-page
 -->
</div>
</div><script src="../site.js"></script>