<link href="../site.css" rel="stylesheet" type="text/css"/>
<div class="mw-page-container"><h1 class="firstHeading mw-first-heading" id="firstHeading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial II/fr</span></h1><div class="mw-parser-output"><div id="itsfree" style="text-align:center; background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">
<figure class="mw-halign-left" typeof="mw:File"><span><img decoding="async" height="38" src="https://upload.wikimedia.org/wikipedia/commons/d/d5/Under_construction_icon-blue.svg" width="45"/></span><figcaption></figcaption></figure> This documentation is a work in progress. Please don't mark it as translatable since it will change in the next hours and days.
</div><div style="clear:both"></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img decoding="async" height="32" src="../File/Freecad.svg" width="32"/></span></span> Tutorial
</td></tr>
<tr>
<th class="ctOdd">Topic
</th></tr>
<tr>
<td class="ctEven">Modélisation
</td></tr>
<tr>
<th class="ctOdd">Level
</th></tr>
<tr>
<td class="ctEven">Utilisateur expérimenté
</td></tr>
<tr>
<th class="ctOdd">Time to complete
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Authors
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">FreeCAD version
</th></tr>
<tr>
<td class="ctEven">≥ 0.19.23300
</td></tr>
<tr>
<th class="ctOdd">Example files
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">See also
</th></tr>
<tr>
<td class="ctEven"><i>None</i>
</td></tr>
<tr>
<td class="ctToc"><br/><div aria-labelledby="mw-toc-heading" class="toc" id="toc" role="navigation"><input class="toctogglecheckbox" id="toctogglecheckbox" role="button" style="display:none" type="checkbox"/><div class="toctitle" dir="ltr" lang="en"><h2 id="mw-toc-heading">Contents</h2><span class="toctogglespan"><label class="toctogglelabel" for="toctogglecheckbox"></label></span></div>
<ul>
<li class="toclevel-1 tocsection-1"><a href="#L'objectif_en_deux_mots"><span class="tocnumber">1</span> <span class="toctext">L'objectif en deux mots</span></a></li>
<li class="toclevel-1 tocsection-2"><a href="#==_Les_Données_de_Conception_=="><span class="tocnumber">2</span> <span class="toctext">== Les Données de Conception ==</span></a></li>
<li class="toclevel-1 tocsection-3"><a href="#Configuration_de_la_géométrie_de_l'ossature"><span class="tocnumber">3</span> <span class="toctext">Configuration de la géométrie de l'ossature</span></a></li>
<li class="toclevel-1 tocsection-4"><a href="#Le_corps_principal"><span class="tocnumber">4</span> <span class="toctext">Le corps principal</span></a></li>
<li class="toclevel-1 tocsection-5"><a href="#Ajouter_des_organes_pour_les_boulons"><span class="tocnumber">5</span> <span class="toctext">Ajouter des organes pour les boulons</span></a></li>
<li class="toclevel-1 tocsection-6"><a href="#Vider_le_corps_principal"><span class="tocnumber">6</span> <span class="toctext">Vider le corps principal</span></a></li>
<li class="toclevel-1 tocsection-7"><a href="#Usinage"><span class="tocnumber">7</span> <span class="toctext">Usinage</span></a></li>
<li class="toclevel-1 tocsection-8"><a href="#Partie_Une"><span class="tocnumber">8</span> <span class="toctext">Partie Une</span></a></li>
</ul>
</div>
</td></tr></tbody></table>
<div id="itsfree" style="text-align:center;color:black;background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">Ce tutoriel a été écrit à l'origine pour une version de développement maintenant obsolète de FreeCAD. Depuis avril 2016, ces fonctionnalités ont été intégrées à la version 0.17 de pré-développement disponible <a class="external text" href="https://github.com/FreeCAD/FreeCAD/releases/tag/0.17_pre" rel="nofollow">ici</a>.
<p><br/>
</p>
Veuillez noter que cette version de FreeCAD en est encore à ses débuts. De plus, ce tutoriel peut nécessiter une mise à jour. Si vous souhaitez participer à sa révision et à sa mise à jour, publiez-le dans la section Wiki du <a class="external text" href="http://forum.freecadweb.org" rel="nofollow">forum</a>.</div>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-19.jpg"><img decoding="async" height="263" src="../File/HolderTop2-19.jpg" srcset="/images/thumb/9/90/HolderTop2-19.jpg/600px-HolderTop2-19.jpg 1.5x, /images/thumb/9/90/HolderTop2-19.jpg/800px-HolderTop2-19.jpg 2x" width="400"/></a><figcaption>Tutoriel Support de Roulement - support de roulement terminé(en haut)</figcaption></figure>
<p><strike>
Comme l'indique l'avertissement en haut de la page , ce <b>tutoriel ne fonctionnera que si vous compilez une branche spéciale hautement expérimentale du code source FreeCAD</b> et est un tutoriel d'introduction à la modélisation avec l'atelier PartDesign dans FreeCAD <b>utilisant des plans de référence qui sont une caractéristique qui n'existe pas encore dans la plupart des versions de FreeCAD</b>.
</strike>
</p>
<h2><span id="L.27objectif_en_deux_mots"></span><span class="mw-headline" id="L'objectif_en_deux_mots">L'objectif en deux mots</span></h2>
<p>Le but de ce tutoriel est de vous présenter deux flux de travail différents pour créer une pièce moulée avec des ébauches et des congés. Selon les autres programmes de CAO que vous avez utilisés, l'un ou l'autre peut vous être familier. Comme exemple de travail, nous allons modéliser un simple support de roulement.
</p><p>C'est la deuxième partie du tutoriel. Il utilisera ce qu'on pourrait appeler le flux de travail 'de corps multiples », en utilisant la (simple) partie supérieure du support comme exemple.
</p><p>Évidemment, pour suivre ce tutoriel, vous devez activer l'Atelier Conception de Pièce.
</p><p><strike> Vous pouvez trouver ma version de la pièce créée dans ce tutoriel [<a class="external text" href="http://ubuntuone.com/39PTZ3Y3LUnmZzpZQPcJT4" rel="nofollow">ici</a>] </strike> <i>Le fichier n'est plus disponible, un nouveau fichier sera fourni à certains date ultérieure</i>.
<br clear="all"/>
</p><p><span id="Design_data"></span>
</p>
<h2><span id=".3D.3D_Les_Donn.C3.A9es_de_Conception_.3D.3D"></span><span class="mw-headline" id="==_Les_Données_de_Conception_==">== Les Données de Conception ==</span></h2>
<p>Le support doit être en mesure de tenir un Roulement d'un diamètre de 90mm avec une largeur allant jusqu'à 33mm (par exemple DIN 630 Type 2308, qui a un diamètre intérieur de 40 mm). Le palier nécessite une hauteur d'épaulement d'au moins 4,5 mm dans le support (et sur l'arbre). La partie supérieure du support sera boulonné sur le fond avec deux boulons de 12mm. Pour la tête d'un tel boulon, il faudra au moins 20 mm de diamètre d'espace libre. Il devrait y avoir une rainure sur les deux côtés du roulement capables de tenir un arbre standard bague d'étanchéité DIN 3760: 38x55x7 40x55x7 ou sur un côté, 50x68x8 de l'autre côté.
</p><p>Le support sera réalisé dans un moule en sable avec une épaisseur minimale de paroi de 5 mm, un angle de dépouille de 2 degrés, et un rayon de congé minimum de 3mm.
</p><p><br clear="all"/>
</p><p><span id="Setting_up_the_skeleton_geometry"></span>
</p>
<h2><span id="Configuration_de_la_g.C3.A9om.C3.A9trie_de_l.27ossature"></span><span class="mw-headline" id="Configuration_de_la_géométrie_de_l'ossature">Configuration de la géométrie de l'ossature</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-2.png"><img decoding="async" height="149" src="../File/HolderTop2-2.png" srcset="/images/thumb/1/19/HolderTop2-2.png/600px-HolderTop2-2.png 1.5x, /images/thumb/1/19/HolderTop2-2.png/800px-HolderTop2-2.png 2x" width="400"/></a><figcaption>Croquis de la géométrie du squelette</figcaption></figure><p> Créer une nouvelle pièce dans l'atelier de Conception de Pièce. Renommez le Corps qui est créé par défaut pour  l'Ossature. Cet organe est probablement déjà activé,  vous pouvez voir par la couleur de fond bleu dans l'arborescence. Créer une nouvelle esquisse sur le plan YZ contenant le contour de l'arbre, du roulements et bagues d'étanchéité. Après avoir terminé l'esquisse, faites une fonction de révolution de celle-ci. Cette fonction squelette sera ensuite utilisé pour référencer la géométrie réelle à celle-ci. Cela signifie que si vous souhaitez modifier les dimensions, tout ce que vous devez faire est d'ajuster les dimensions de la fonction  squelette et le reste de la pièce se mettra à jour en conséquence. </p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-2-1.jpg"><img decoding="async" height="260" src="../File/HolderTop2-2-1.jpg" srcset="/images/thumb/1/14/HolderTop2-2-1.jpg/600px-HolderTop2-2-1.jpg 1.5x, /images/thumb/1/14/HolderTop2-2-1.jpg/800px-HolderTop2-2-1.jpg 2x" width="400"/></a><figcaption>La géométrie de l'ossature</figcaption></figure>
<p><br clear="all"/>
</p><p><span id="The_main_body"></span>
</p>
<h2><span class="mw-headline" id="Le_corps_principal">Le corps principal</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-3.jpg"><img decoding="async" height="298" src="../File/HolderTop2-3.jpg" srcset="/images/thumb/8/86/HolderTop2-3.jpg/600px-HolderTop2-3.jpg 1.5x, /images/thumb/8/86/HolderTop2-3.jpg/800px-HolderTop2-3.jpg 2x" width="400"/></a><figcaption>Esquisse de la première Protusion</figcaption></figure><p> Créer un nouveau corps et le rendre actif. L'esquisse pour la première protusion est affichée sur la droite. Elle est placée sur un plan de référence avec un décalage de 5 mm (épaisseur de paroi) de la face de l'ossature marquant le côté de l'une des bagues d'étanchéité du proulement. Parce que toutes les dimensions importantes sont prises à partir du squelette, il y a seulement trois dimensions: La surépaisseur d'usinage (3mm) à la base comme un décalage du plan XY, l'épaisseur de paroi de 5 mm de diamètre extérieur du squelette, et les deux angle de dépouille. Pour créer la dimension 5mm, vous devez d'abord sélectionner le cercle extérieur (rayon 45mm) de la géométrie de l'ossature comme la géométrie externe dans l'esquisse, puis mettez une ligne de construction contrainte tangentiellement à ce cercle et avec un angle de deux degrés.
</p><p>Vous vous demandez probablement pourquoi il y a ce petit segment de droite au bas de chaque arc. Ce segment indique qu'il y aura un angle de deux degrés sur les arcs. Cela pourrait ressembler à beaucoup de travail pour un très petit avantage, mais de nombreux programmes de CAO (et peut-être un jour FreeCAD) disposent d'outils qui mettent en évidence un modèle solide en différentes couleurs immédiatement et vous présentent toutes les faces où l'angle de dépouille n'est pas correct. Vous ne voulez pas que cela arrive à votre modèle, en particulier après la mise en place d'un grand nombre de congés! <br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-4.jpg"><img decoding="async" height="279" src="../File/HolderTop2-4.jpg" srcset="/images/thumb/c/cd/HolderTop2-4.jpg/600px-HolderTop2-4.jpg 1.5x, /images/thumb/c/cd/HolderTop2-4.jpg/800px-HolderTop2-4.jpg 2x" width="400"/></a><figcaption>La première Protusion</figcaption></figure><p> Quand vous avez fait le croquis (qui est un peu difficile à cause des deux degrés des lignes tangentielles), créer une Protusion de celui-ci s'étendant jusqu'à l'autre côté de la géométrie de l'ossature, à nouveau avec un décalage de 5 mm à la face latérale. Vous n'avez pas besoin de créer un plan de référence cette fois, le mode "jusqu'à la face " du dialogue de Protusion propose d'entrée un décalage. <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-5.jpg"><img decoding="async" height="313" src="../File/HolderTop2-5.jpg" srcset="/images/thumb/6/6a/HolderTop2-5.jpg/600px-HolderTop2-5.jpg 1.5x, /images/thumb/6/6a/HolderTop2-5.jpg/800px-HolderTop2-5.jpg 2x" width="400"/></a><figcaption>Esquisse pour Pad coupé-out</figcaption></figure><p> Ensuite, nous allons réduire la matière sur les deux extrémités de la Protusion car il est toujours idéal pour les pièces en fonte d'avoir une épaisseur de paroi aussi uniforme que possible. Créez une esquisse sur chacune des faces d'extrémité de la Protusion et  dimensionner à 5 mm le décalage du cercle représentant la bague d'étanchéité du roulement (rayon de 27,5 mm d'un côté et 34mm sur l'autre). Pour le segment de la ligne de fond de l'esquisse , créer une autre géométrie externe de Protusion  et  la contraindre. Ainsi l'esquisse n'a qu'une seule dimension, l'épaisseur de paroi de 5 mm (les dimensions de 150mm et 75mm ne sont pas importants tant qu'ils sont assez grands pour s' assurer que tout est coupé). <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-6.jpg"><img decoding="async" height="277" src="../File/HolderTop2-6.jpg" srcset="/images/thumb/b/bc/HolderTop2-6.jpg/600px-HolderTop2-6.jpg 1.5x, /images/thumb/b/bc/HolderTop2-6.jpg/800px-HolderTop2-6.jpg 2x" width="400"/></a><figcaption>La Protusion avec des découpes pour obtenir une épaisseur de paroi uniforme</figcaption></figure><p> Utilisez le croquis que vous avez créé pour faire une Cavité et l'étendre jusqu'à la face de la géométrie du squelette qui représente le palier, moins  5 mm pour compenser l'épaisseur de paroi. Pour la deuxième cavité, vous pouvez utiliser l'option «Dupliquer objet sélectionné" dans le menu PartDesign pour reproduire le croquis que vous avez déjà fait (choisissez de ne pas reproduire les objets dépendants si la question apparaît). Ensuite, sélectionnez la face sur laquelle vous souhaitez déplacer cette esquisse , et de dire à FreeCAD de dessiner l'esquisse sur cette face (c'est un élément du menu PartDesign). Après la création de la deuxième Cavité, vous pouvez regarder le résultat du fond pour vérifier que vous avez une épaisseur de paroi uniforme de 5 mm sur le contour de la géométrie du squelette. <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-7.jpg"><img decoding="async" height="226" src="../File/HolderTop2-7.jpg" srcset="/images/thumb/c/cc/HolderTop2-7.jpg/600px-HolderTop2-7.jpg 1.5x, /images/thumb/c/cc/HolderTop2-7.jpg/800px-HolderTop2-7.jpg 2x" width="400"/></a><figcaption>Plan neutre pour appliquer le projet</figcaption></figure><p> Maintenant, il est temps de créer le projet et  les congés. Le projet nécessite un plan neutre, ce qui signifie que la géométrie qui est coupée par ce plan restera à sa place, tandis que le reste de la face  est incliné de l'angle de dépouille. L'utilisation du fond de la Protusion  à cette fin n'est pas une bonne idée, parce que l'épaisseur de la paroi dans la partie supérieure du support deviendrait inférieure à 5 mm. Donc nous créons un plan de référence décalé environ 35mm de  XY à cet effet. Activez le squelette et créer le plan, parce que nous en aurons besoin pour appliquer le projet à d'autres organes, aussi. <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-8.jpg"><img decoding="async" height="233" src="../File/HolderTop2-8.jpg" srcset="/images/thumb/3/32/HolderTop2-8.jpg/600px-HolderTop2-8.jpg 1.5x, /images/thumb/3/32/HolderTop2-8.jpg/800px-HolderTop2-8.jpg 2x" width="400"/></a><figcaption>Première corps avec le projet et les flancs de raccordement</figcaption></figure><p> L'image de droite montre le premier corps fini avec le projet et les congés appliqués. On notera que les bords (concaves) extérieurs ont un rayon de de raccordement plus large de 5 mm, de nouveau avec le but de créer une épaisseur de paroi plus uniforme (plus de 5 mm n'est pas possible, car alors, après usinage de l'intérieur du support l'épaisseur de paroi deviendrait inférieure à 5 mm). <br clear="all"/>
</p><p><span id="Adding_the_bodies_for_the_bolts"></span>
</p>
<h2><span class="mw-headline" id="Ajouter_des_organes_pour_les_boulons">Ajouter des organes pour les boulons</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-13.jpg"><img decoding="async" height="333" src="../File/HolderTop2-13.jpg" srcset="/images/thumb/6/6b/HolderTop2-13.jpg/600px-HolderTop2-13.jpg 1.5x, /images/6/6b/HolderTop2-13.jpg 2x" width="400"/></a><figcaption>Le croquis pour le corps des boulons</figcaption></figure><p> Les boulons ont besoin de deux corps cylindriques des deux côtés du corps principal. Il est préférable d'inclure l'angle de dépouille de 2 degrés dans l'esquisse. J'ai essayé de tourner un cylindre et d'appliquer plus tard un projet, mais des choses étranges se sont passées après la symétrie et je ne pouvais pas mettre les congés sur elle parce que la surface a été déformée en quelque sorte.
</p><p>Le dessin est dimensionné pour que l'axe de rotation soit à distance de 12mm du diamètre externe de l'ossature du corps, 7 mm pour le rayon du trou, plus de 5 mm pour l'épaisseur de paroi. Pour le plaisir d'avoir une partie entièrement paramétrique, c'est une bonne idée d'ajouter un plan au squelette environ 25 mm au-dessus du plan XY pour marquer le sommet des cylindres. Comme ce sera usinée, l'esquisse est dimensionné 3mm au-dessus.
</p><p><br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-14.jpg"><img decoding="async" height="244" src="../File/HolderTop2-14.jpg" srcset="/images/thumb/c/c7/HolderTop2-14.jpg/600px-HolderTop2-14.jpg 1.5x, /images/thumb/c/c7/HolderTop2-14.jpg/800px-HolderTop2-14.jpg 2x" width="400"/></a><figcaption>Le corps des boulons</figcaption></figure><p> Créez une révolution de l'esquisse et appliquer un congé de 4mm vers le haut. Cela signifie que, après usinage et enlèvement de 3mm, un léger rayon restera qui permet d'éviter une arête vive où quelqu'un pourrait se couper la main pour serrer la vis. <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-16.jpg"><img decoding="async" height="261" src="../File/HolderTop2-16.jpg" srcset="/images/thumb/6/6a/HolderTop2-16.jpg/600px-HolderTop2-16.jpg 1.5x, /images/thumb/6/6a/HolderTop2-16.jpg/800px-HolderTop2-16.jpg 2x" width="400"/></a><figcaption>Le corps principal avec les deux organes pour les boulons</figcaption></figure><p> Créer une fonction booléenne pour fusionner le corps principal et le corps du boulon. Puis créer un nouvel organe pour l'autre côté. Dupliquer le croquis de la révolution, le déplacer à cet organe et créez le deuxième corps pour les boulons (Symétriser un corps n'est pas encore pris en charge si vous avez besoin de refaire la plus grande partie). Puis fusionner ce deuxième corps dans le corps principal . Enfin, appliquez un grand congé sur le bord créé par l'opération de fusion booléenne. Le plus grand que je pouvais obtenir était 4mm. <br clear="all"/>
</p><p><span id="Hollowing_out_the_main_body"></span>
</p>
<h2><span class="mw-headline" id="Vider_le_corps_principal">Vider le corps principal</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-9.jpg"><img decoding="async" height="347" src="../File/HolderTop2-9.jpg" srcset="/images/thumb/c/c5/HolderTop2-9.jpg/450px-HolderTop2-9.jpg 1.5x, /images/c/c5/HolderTop2-9.jpg 2x" width="300"/></a><figcaption>La première Protusion du corps  découpe  l'intérieur du corps principal</figcaption></figure><p> Nous allons maintenant travailler à l'intérieur du support et évider pour faire place aux roulements et bagues d'étanchéité. En faisant cela bien sûr, nous devons garder à l'esprit la surépaisseur de 3mm. Puisque ce tutoriel enseigne la méthode multi-corps, nous allons créer la géométrie à l'intérieur comme un corps séparé, puis le couper sur le corps principal par une opération booléenne.
</p><p>Créer un nouveau corps et le rendre actif. Premièrement, nous avons besoin d'un plan de référence de 3 mm de décalage intérieur de la face du squelette qui montre le côté du roulement. Puis, dupliquer l'esquisse de la première Protusion du corps principal. Il sera ajouté au corps principal, donc faites un clic droit dessus et choisissez le pour le déplacer vers le corps nouvellement créé (cette option n' est disponible que dans le menu contextuel si l' atelier PartDesign est actif). Dessiner le croquis sur le plan de référence (si l'esquisse s'inverse après le dessin, déplacer le plan de référence de l'autre côté du palier, à côté de l'endroit où l'esquisse dupliqué est située). Maintenant, modifier l'esquisse de sorte que le diamètre est de 3 mm inférieur au diamètre externe de la géométrie de l'ossature qui représente le palier. Tout ce que vous devez faire est de retirer lpaliera dimension 5mm, faites glisser l'esquisse à l'intérieur du cercle de référence, et créez une nouvelle dimension de 3 mm.
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-10.jpg"><img decoding="async" height="218" src="../File/HolderTop2-10.jpg" srcset="/images/thumb/e/e8/HolderTop2-10.jpg/600px-HolderTop2-10.jpg 1.5x, /images/thumb/e/e8/HolderTop2-10.jpg/800px-HolderTop2-10.jpg 2x" width="400"/></a><figcaption>Le corps de découpe à l'intérieur du corps du squelette</figcaption></figure><p> Ensuite, nous voulons deux autres protusions pour creuser l'emplacement des bagues d'étanchéité. Dupliquer le croquis de la première plage de l'Organe de découpe et de dessiner au plan XZ. Modifier l'esquisse et remplacer la référence externe avec le diamètre extérieur de la bague d'étanchéité du roulement. Extruder cette esquisse avec un décalage de 3 mm du côté de la bague d'étanchéité. Répétez l'ensemble du processus pour la bague d'étanchéité de l'autre côté.
</p><p>Après cela, nous voulons créer deux autres Protusions comme les deux derniers pour donner à l'arbre un dégagement (par exemple 3 mm) à l'intérieur du support. <br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-11.jpg"><img decoding="async" height="200" src="../File/HolderTop2-11.jpg" srcset="/images/thumb/a/a9/HolderTop2-11.jpg/600px-HolderTop2-11.jpg 1.5x, /images/thumb/a/a9/HolderTop2-11.jpg/800px-HolderTop2-11.jpg 2x" width="400"/></a><figcaption>Le corps de découpe complet (congés minimum  impossibles)</figcaption></figure><p> Maintenant tout ce qui reste est d'appliquer le projet sur les faces latérales planes, en utilisant le même plan neutre que pour le corps principal, et le congé. Appliquer un congé général de 3mm à tous les bords. Vous remarquerez qu'il y a plusieurs bords qui ne peuvent pas avoir de congé... c'est un défaut du noyau géométrique sous-jacent qui utilise FreeCAD. <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-15.jpg"><img decoding="async" height="237" src="../File/HolderTop2-15.jpg" srcset="/images/thumb/d/d9/HolderTop2-15.jpg/600px-HolderTop2-15.jpg 1.5x, /images/thumb/d/d9/HolderTop2-15.jpg/800px-HolderTop2-15.jpg 2x" width="400"/></a><figcaption>La pièce brute complète du support (sans usinage)</figcaption></figure><p> Nous sommes prêts à creuser le corps principal. Sélectionnez-le et choisissez de créer une nouvelle opération booléenne. Ajouter le corps de découpe à la liste de la fenêtre et régler l'opération pour "Couper". Mettre un congé de 3 mm sur les deux bords résultant de l'opération de découpe (encore certains bords restent qui sont "non congéable»). Le résultat devrait ressembler à l'image sur la droite.
</p><p>La pièce brute est maintenant terminée. C'est ce à quoi le support va ressembler avant l'usinage. A noter que puisque le moule aura une moitié supérieure et inférieure, le bord entre les deux n'a pas de congé. Aussi, si vous donnez ce modèle à une fonderie assurez-vous de souligner qu'il a les dimensions après la coulée. La fonderie devra ensuite appliquer un certain pourcentage de retrait au modèle (faire le modèle numérique utilisé pour fabriquer le moule plus grand de sorte que lorsque le métal se refroidit et se contracte après la coulée, il aura la bonne taille). <br clear="all"/>
</p><p><span id="Machining"></span>
</p>
<h2><span class="mw-headline" id="Usinage">Usinage</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-17.jpg"><img decoding="async" height="472" src="../File/HolderTop2-17.jpg" srcset="/images/thumb/e/e3/HolderTop2-17.jpg/600px-HolderTop2-17.jpg 1.5x, /images/e/e3/HolderTop2-17.jpg 2x" width="400"/></a><figcaption>Esquisse pour percer le trou pour les boulons</figcaption></figure><p> Pour enlever la matièrie pour l'usinage de l'intérieur du support,  nous pouvons utiliser le Squelette du corps . Si vous ne voulez pas parce qu'alors le squelette se cache quelque part au fond de l'arborescence, vous pouvez également dupliquer l'esquisse de la fonction de révolution du squelette et recréer la révolution dans un autre corps. Ce ne est pas complètement paramétrique, cependant, parce que l'esquisse dupliquée est indépendante de l'original, ainsi vous aurez à travailler sur les deux si vous changez une dimension. Les entités dupliquées dépendantes pourront être prises en charge dans l'avenir.
</p><p>Pour le reste de l'usinage, créer un nouveau corps. Le fond du support sera usinée par une Protusion esquissée sur le plan XY s' étendant vers le bas. Ensuite, esquisser une révolution pour faire un trou pour les boulons. Vous aurez besoin d'esquisser sur le plan XZ et tourner de sorte que vous pouvez choisir le diamètre extérieur du squelette du Corps comme une référence externe. La partie supérieure de l'esquisse servira à usiner un endroit plat pour la tête du boulon. Elle est dimensionnée pour laisser une épaisseur de paroi d'au moins 5 mm dans le support. Si cela ne donne pas suffisamment d'espace pour la tête de boulon, vous pouvez déplacer le plan de référence vers le haut. Bien sûr, vous pourriez mettre cette logique dans le squelette, qui est laissé comme exercice pour le lecteur! <br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-18.jpg"><img decoding="async" height="293" src="../File/HolderTop2-18.jpg" srcset="/images/thumb/b/bf/HolderTop2-18.jpg/600px-HolderTop2-18.jpg 1.5x, /images/thumb/b/bf/HolderTop2-18.jpg/800px-HolderTop2-18.jpg 2x" width="400"/></a><figcaption>L'usinage du corps</figcaption></figure><p> Vous pouvez symétriser la révolution sur l'axe YZ. L'image de droite montre l'«usinage» du corps. Bien sûr, la plupart des dimensions des Protusions et révolutions ne sont pas importantes aussi longtemps qu' il ya beaucoup de chevauchement. <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop2-19.jpg"><img decoding="async" height="263" src="../File/HolderTop2-19.jpg" srcset="/images/thumb/9/90/HolderTop2-19.jpg/600px-HolderTop2-19.jpg 1.5x, /images/thumb/9/90/HolderTop2-19.jpg/800px-HolderTop2-19.jpg 2x" width="400"/></a><figcaption>Le support fini avec l'usinage</figcaption></figure><p> Enfin, créer une opération booléenne pour couper le Corps de usiné par le Corps principal. Si vous voulez un bel effet visuel, vous pouvez colorer les surfaces usinées différemment du reste de la pièce. C'est aussi une rétroaction optique utile, vous indiquant si vous avez oublié d'usiner quelque part. <br clear="all"/>
</p><h2><span class="mw-headline" id="Partie_Une">Partie Une</span></h2>
<p><a href="PartDesign_Bearingholder_Tutorial_I.html" title="PartDesign Bearingholder Tutorial I/fr"> Tutoriel de Conception Support de Roulement I</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20241129212946
Cache expiry: 86400
Reduced expiry: false
Complications: [show‐toc, no‐toc‐conversion]
CPU time usage: 0.145 seconds
Real time usage: 0.634 seconds
Preprocessor visited node count: 110/1000000
Post‐expand include size: 1864/2097152 bytes
Template argument size: 623/2097152 bytes
Highest expansion depth: 3/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post‐expand size: 0/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%    5.898      1 -total
 32.01%    1.888      1 Template:VeryImportantMessage
 29.11%    1.717      1 Template:Page_in_progress
 18.64%    1.099      1 Template:TutorialInfo
 14.85%    0.876      1 Template:Clear
-->
<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:54982-0!canonical and timestamp 20241129212945 and revision id 1471513. Rendering was triggered because: api-parse
 -->
</div></div><script src="../script.js"></script>
