<link href="../site.css" rel="stylesheet" type="text/css"/><div class="mw-page-container"><h1 id="firstHeading" class="firstHeading mw-first-heading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial II/fr</span></h1><?xml encoding="UTF-8"><div class="mw-content-ltr mw-parser-output" lang="fr" dir="ltr"><div class="mw-pt-languages noprint navigation-not-searchable" lang="en" dir="ltr"><div class="mw-pt-languages-label">Other languages:</div><ul class="mw-pt-languages-list"><li><a href="../index.php?title=Special;Translate&amp;group=page-PartDesign+Bearingholder+Tutorial+II&amp;language=&amp;task=view.html" class="new" title="Start translation for this language" lang="" dir="ltr"></a></li>
<li><a href="../de/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--complete" title="PartDesign Lagergeh&auml;use Tutorium II (100% translated)" lang="de" dir="ltr">Deutsch</a></li>
<li><a href="../PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-languages-ui mw-pt-progress mw-pt-progress--complete" title="PartDesign Bearingholder Tutorial II (100% translated)" lang="en" dir="ltr">English</a></li>
<li><a href="../tr/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Bearingholder Tutorial II/tr (2% translated)" lang="tr" dir="ltr">T&uuml;rk&ccedil;e</a></li>
<li><a href="../es/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--med" title="PartDesign Soporte de rodamiento Tutorial II (17% translated)" lang="es" dir="ltr">espa&ntilde;ol</a></li>
<li><span class="mw-pt-languages-selected mw-pt-progress mw-pt-progress--complete" lang="fr" dir="ltr">fran&ccedil;ais</span></li>
<li><a href="../it/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--complete" title="Tutorial per creare un supporto per cuscinetto con PartDesign. Seconda parte. (100% translated)" lang="it" dir="ltr">italiano</a></li>
<li><a href="../pl/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--complete" title="Poradnik: Projekt cz&#281;&#347;ci, uchwyt &#322;o&#380;yska cze&#347;&#263; 2 (100% translated)" lang="pl" dir="ltr">polski</a></li>
<li><a href="../pt-br/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--low" title="Tutorial de Projeto de Mancais de Apoio II (2% translated)" lang="pt-BR" dir="ltr">portugu&ecirc;s do Brasil</a></li>
<li><a href="../ro/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--high" title="PartDesign Bearingholder Tutorial II (90% translated)" lang="ro" dir="ltr">rom&acirc;n&#259;</a></li>
<li><a href="../ru/PartDesign_Bearingholder_Tutorial_II.html" class="mw-pt-progress mw-pt-progress--low" title="PartDesign Bearingholder Tutorial II/ru (7% translated)" lang="ru" dir="ltr">&#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;</a></li></ul></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img src="../File/Freecad.svg" decoding="async" width="32" height="32" class="mw-file-element" data-file-width="48" data-file-height="48"></span></span> Tutorial
</td></tr>
<tr>
<th class="ctOdd">Topic
</th></tr>
<tr>
<td class="ctEven">Mod&eacute;lisation
</td></tr>
<tr>
<th class="ctOdd">Level
</th></tr>
<tr>
<td class="ctEven">Utilisateur exp&eacute;riment&eacute;
</td></tr>
<tr>
<th class="ctOdd">Time to complete
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Authors
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">FreeCAD version
</th></tr>
<tr>
<td class="ctEven">&ge; 0.19.23300
</td></tr>
<tr>
<th class="ctOdd">Example files
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">See also
</th></tr>
<tr>
<td class="ctEven"><i>None</i>
</td></tr>
<tr>
<td class="ctToc"><br><meta property="mw:PageProp/toc">
</td></tr></tbody></table>
<p><span id="Purpose_in_Brief"></span>
</p>
<h2><span id="L.27objectif_en_deux_mots"></span><span class="mw-headline" id="L'objectif_en_deux_mots">L'objectif en deux mots</span></h2>
<p>Le but de ce tutoriel est de vous pr&eacute;senter deux flux de travail diff&eacute;rents pour cr&eacute;er une pi&egrave;ce moul&eacute;e avec des &eacute;bauches et des cong&eacute;s. Selon les autres programmes de CAO que vous avez utilis&eacute;s, l'un ou l'autre peut vous &ecirc;tre familier. Comme exemple de travail, nous allons mod&eacute;liser un simple support de roulement.
</p><p>C'est la deuxi&egrave;me partie du tutoriel. Il utilisera ce qu'on pourrait appeler le flux de travail 'de corps multiples&nbsp;&raquo;, en utilisant la (simple) partie sup&eacute;rieure du support comme exemple.
</p><p>&Eacute;videmment, pour suivre ce tutoriel, vous devez activer l'Atelier Conception de Pi&egrave;ce.
</p><p><span typeof="mw:File"><a href="../index.php?title=HolderTop2-19.jpg&amp;filetimestamp=20130716184057&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-19.jpg" decoding="async" width="400" height="263" class="mw-file-element" data-file-width="1037" data-file-height="683"></a></span>
</p>
<p style="text-align:left; font-style:italic; max-width:800px; box-sizing:border-box; margin-block:1em; margin-inline:clamp(1em, 6vw, 2em); padding-inline:clamp(0.75em, 4vw, 2em); word-break:normal; overflow-wrap:break-word;">Tutoriel sur les supports de roulement. Support de roulement termin&eacute; (partie haute)</p>
<p><span id="Design_data"></span>
</p>
<h2><span id=".3D.3D_Les_Donn.C3.A9es_de_Conception_.3D.3D"></span><span class="mw-headline" id="==_Les_Donn&eacute;es_de_Conception_==">== Les Donn&eacute;es de Conception ==</span></h2>
<p>Le support doit &ecirc;tre en mesure de tenir un Roulement d'un diam&egrave;tre de 90mm avec une largeur allant jusqu'&agrave; 33mm (par exemple DIN 630 Type 2308, qui a un diam&egrave;tre int&eacute;rieur de 40 mm). Le palier n&eacute;cessite une hauteur d'&eacute;paulement d'au moins 4,5 mm dans le support (et sur l'arbre). La partie sup&eacute;rieure du support sera boulonn&eacute; sur le fond avec deux boulons de 12mm. Pour la t&ecirc;te d'un tel boulon, il faudra au moins 20 mm de diam&egrave;tre d'espace libre. Il devrait y avoir une rainure sur les deux c&ocirc;t&eacute;s du roulement capables de tenir un arbre standard bague d'&eacute;tanch&eacute;it&eacute; DIN 3760: 38x55x7 40x55x7 ou sur un c&ocirc;t&eacute;, 50x68x8 de l'autre c&ocirc;t&eacute;.
</p><p>Le support sera r&eacute;alis&eacute; dans un moule en sable avec une &eacute;paisseur minimale de paroi de 5 mm, un angle de d&eacute;pouille de 2 degr&eacute;s, et un rayon de cong&eacute; minimum de 3mm.
</p><p><br clear="all">
</p><p><span id="Setting_up_the_skeleton_geometry"></span>
</p>
<h2><span id="Configuration_de_la_g.C3.A9om.C3.A9trie_de_l.27ossature"></span><span class="mw-headline" id="Configuration_de_la_g&eacute;om&eacute;trie_de_l'ossature">Configuration de la g&eacute;om&eacute;trie de l'ossature</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-2.png&amp;filetimestamp=20160718193124&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-2.png" decoding="async" width="400" height="149" class="mw-file-element" data-file-width="1260" data-file-height="468"></a><figcaption> Croquis de la g&eacute;om&eacute;trie du squelette </figcaption></figure><p> Cr&eacute;er une nouvelle pi&egrave;ce dans l'atelier de Conception de Pi&egrave;ce. Renommez le Corps qui est cr&eacute;&eacute; par d&eacute;faut pour  l'Ossature. Cet organe est probablement d&eacute;j&agrave; activ&eacute;,  vous pouvez voir par la couleur de fond bleu dans l'arborescence. Cr&eacute;er une nouvelle esquisse sur le plan YZ contenant le contour de l'arbre, du roulements et bagues d'&eacute;tanch&eacute;it&eacute;. Apr&egrave;s avoir termin&eacute; l'esquisse, faites une fonction de r&eacute;volution de celle-ci. Cette fonction squelette sera ensuite utilis&eacute; pour r&eacute;f&eacute;rencer la g&eacute;om&eacute;trie r&eacute;elle &agrave; celle-ci. Cela signifie que si vous souhaitez modifier les dimensions, tout ce que vous devez faire est d'ajuster les dimensions de la fonction  squelette et le reste de la pi&egrave;ce se mettra &agrave; jour en cons&eacute;quence. </p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-2-1.jpg&amp;filetimestamp=20130711190937&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-2-1.jpg" decoding="async" width="400" height="260" class="mw-file-element" data-file-width="1058" data-file-height="687"></a><figcaption> La g&eacute;om&eacute;trie de l'ossature </figcaption></figure>
<p><br clear="all">
</p><p><span id="The_main_body"></span>
</p>
<h2><span class="mw-headline" id="Le_corps_principal">Le corps principal</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-3.jpg&amp;filetimestamp=20130711184543&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-3.jpg" decoding="async" width="400" height="298" class="mw-file-element" data-file-width="1040" data-file-height="774"></a><figcaption> Esquisse de la premi&egrave;re Protusion </figcaption></figure><p> Cr&eacute;er un nouveau corps et le rendre actif. L'esquisse pour la premi&egrave;re protusion est affich&eacute;e sur la droite. Elle est plac&eacute;e sur un plan de r&eacute;f&eacute;rence avec un d&eacute;calage de 5 mm (&eacute;paisseur de paroi) de la face de l'ossature marquant le c&ocirc;t&eacute; de l'une des bagues d'&eacute;tanch&eacute;it&eacute; du proulement. Parce que toutes les dimensions importantes sont prises &agrave; partir du squelette, il y a seulement trois dimensions: La sur&eacute;paisseur d'usinage (3mm) &agrave; la base comme un d&eacute;calage du plan XY, l'&eacute;paisseur de paroi de 5 mm de diam&egrave;tre ext&eacute;rieur du squelette, et les deux angle de d&eacute;pouille. Pour cr&eacute;er la dimension 5mm, vous devez d'abord s&eacute;lectionner le cercle ext&eacute;rieur (rayon 45mm) de la g&eacute;om&eacute;trie de l'ossature comme la g&eacute;om&eacute;trie externe dans l'esquisse, puis mettez une ligne de construction contrainte tangentiellement &agrave; ce cercle et avec un angle de deux degr&eacute;s.
</p><p>Vous vous demandez probablement pourquoi il y a ce petit segment de droite au bas de chaque arc. Ce segment indique qu'il y aura un angle de deux degr&eacute;s sur les arcs. Cela pourrait ressembler &agrave; beaucoup de travail pour un tr&egrave;s petit avantage, mais de nombreux programmes de CAO (et peut-&ecirc;tre un jour FreeCAD) disposent d'outils qui mettent en &eacute;vidence un mod&egrave;le solide en diff&eacute;rentes couleurs imm&eacute;diatement et vous pr&eacute;sentent toutes les faces o&ugrave; l'angle de d&eacute;pouille n'est pas correct. Vous ne voulez pas que cela arrive &agrave; votre mod&egrave;le, en particulier apr&egrave;s la mise en place d'un grand nombre de cong&eacute;s! <br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-4.jpg&amp;filetimestamp=20130711185009&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-4.jpg" decoding="async" width="400" height="279" class="mw-file-element" data-file-width="1117" data-file-height="780"></a><figcaption> La premi&egrave;re Protusion </figcaption></figure><p> Quand vous avez fait le croquis (qui est un peu difficile &agrave; cause des deux degr&eacute;s des lignes tangentielles), cr&eacute;er une Protusion de celui-ci s'&eacute;tendant jusqu'&agrave; l'autre c&ocirc;t&eacute; de la g&eacute;om&eacute;trie de l'ossature, &agrave; nouveau avec un d&eacute;calage de 5 mm &agrave; la face lat&eacute;rale. Vous n'avez pas besoin de cr&eacute;er un plan de r&eacute;f&eacute;rence cette fois, le mode "jusqu'&agrave; la face " du dialogue de Protusion propose d'entr&eacute;e un d&eacute;calage. <br clear="all">
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-5.jpg&amp;filetimestamp=20130711190315&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-5.jpg" decoding="async" width="400" height="313" class="mw-file-element" data-file-width="899" data-file-height="703"></a><figcaption> Esquisse pour Pad coup&eacute;-out </figcaption></figure><p> Ensuite, nous allons r&eacute;duire la mati&egrave;re sur les deux extr&eacute;mit&eacute;s de la Protusion car il est toujours id&eacute;al pour les pi&egrave;ces en fonte d'avoir une &eacute;paisseur de paroi aussi uniforme que possible. Cr&eacute;ez une esquisse sur chacune des faces d'extr&eacute;mit&eacute; de la Protusion et  dimensionner &agrave; 5 mm le d&eacute;calage du cercle repr&eacute;sentant la bague d'&eacute;tanch&eacute;it&eacute; du roulement (rayon de 27,5 mm d'un c&ocirc;t&eacute; et 34mm sur l'autre). Pour le segment de la ligne de fond de l'esquisse , cr&eacute;er une autre g&eacute;om&eacute;trie externe de Protusion  et  la contraindre. Ainsi l'esquisse n'a qu'une seule dimension, l'&eacute;paisseur de paroi de 5 mm (les dimensions de 150mm et 75mm ne sont pas importants tant qu'ils sont assez grands pour s' assurer que tout est coup&eacute;). <br clear="all">
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-6.jpg&amp;filetimestamp=20130711190430&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-6.jpg" decoding="async" width="400" height="277" class="mw-file-element" data-file-width="1063" data-file-height="736"></a><figcaption> La Protusion avec des d&eacute;coupes pour obtenir une &eacute;paisseur de paroi uniforme </figcaption></figure><p> Utilisez le croquis que vous avez cr&eacute;&eacute; pour faire une Cavit&eacute; et l'&eacute;tendre jusqu'&agrave; la face de la g&eacute;om&eacute;trie du squelette qui repr&eacute;sente le palier, moins  5 mm pour compenser l'&eacute;paisseur de paroi. Pour la deuxi&egrave;me cavit&eacute;, vous pouvez utiliser l'option &laquo;Dupliquer objet s&eacute;lectionn&eacute;" dans le menu PartDesign pour reproduire le croquis que vous avez d&eacute;j&agrave; fait (choisissez de ne pas reproduire les objets d&eacute;pendants si la question appara&icirc;t). Ensuite, s&eacute;lectionnez la face sur laquelle vous souhaitez d&eacute;placer cette esquisse , et de dire &agrave; FreeCAD de dessiner l'esquisse sur cette face (c'est un &eacute;l&eacute;ment du menu PartDesign). Apr&egrave;s la cr&eacute;ation de la deuxi&egrave;me Cavit&eacute;, vous pouvez regarder le r&eacute;sultat du fond pour v&eacute;rifier que vous avez une &eacute;paisseur de paroi uniforme de 5 mm sur le contour de la g&eacute;om&eacute;trie du squelette. <br clear="all">
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-7.jpg&amp;filetimestamp=20130711192218&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-7.jpg" decoding="async" width="400" height="226" class="mw-file-element" data-file-width="1085" data-file-height="614"></a><figcaption> Plan neutre pour appliquer le projet </figcaption></figure><p> Maintenant, il est temps de cr&eacute;er le projet et  les cong&eacute;s. Le projet n&eacute;cessite un plan neutre, ce qui signifie que la g&eacute;om&eacute;trie qui est coup&eacute;e par ce plan restera &agrave; sa place, tandis que le reste de la face  est inclin&eacute; de l'angle de d&eacute;pouille. L'utilisation du fond de la Protusion  &agrave; cette fin n'est pas une bonne id&eacute;e, parce que l'&eacute;paisseur de la paroi dans la partie sup&eacute;rieure du support deviendrait inf&eacute;rieure &agrave; 5 mm. Donc nous cr&eacute;ons un plan de r&eacute;f&eacute;rence d&eacute;cal&eacute; environ 35mm de  XY &agrave; cet effet. Activez le squelette et cr&eacute;er le plan, parce que nous en aurons besoin pour appliquer le projet &agrave; d'autres organes, aussi. <br clear="all">
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-8.jpg&amp;filetimestamp=20130711192240&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-8.jpg" decoding="async" width="400" height="233" class="mw-file-element" data-file-width="1106" data-file-height="644"></a><figcaption> Premi&egrave;re corps avec le projet et les flancs de raccordement </figcaption></figure><p> L'image de droite montre le premier corps fini avec le projet et les cong&eacute;s appliqu&eacute;s. On notera que les bords (concaves) ext&eacute;rieurs ont un rayon de de raccordement plus large de 5 mm, de nouveau avec le but de cr&eacute;er une &eacute;paisseur de paroi plus uniforme (plus de 5 mm n'est pas possible, car alors, apr&egrave;s usinage de l'int&eacute;rieur du support l'&eacute;paisseur de paroi deviendrait inf&eacute;rieure &agrave; 5 mm). <br clear="all">
</p><p><span id="Adding_the_bodies_for_the_bolts"></span>
</p>
<h2><span class="mw-headline" id="Ajouter_des_organes_pour_les_boulons">Ajouter des organes pour les boulons</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-13.jpg&amp;filetimestamp=20130716175052&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-13.jpg" decoding="async" width="400" height="333" class="mw-file-element" data-file-width="730" data-file-height="607"></a><figcaption> Le croquis pour le corps des boulons </figcaption></figure><p> Les boulons ont besoin de deux corps cylindriques des deux c&ocirc;t&eacute;s du corps principal. Il est pr&eacute;f&eacute;rable d'inclure l'angle de d&eacute;pouille de 2 degr&eacute;s dans l'esquisse. J'ai essay&eacute; de tourner un cylindre et d'appliquer plus tard un projet, mais des choses &eacute;tranges se sont pass&eacute;es apr&egrave;s la sym&eacute;trie et je ne pouvais pas mettre les cong&eacute;s sur elle parce que la surface a &eacute;t&eacute; d&eacute;form&eacute;e en quelque sorte.
</p><p>Le dessin est dimensionn&eacute; pour que l'axe de rotation soit &agrave; distance de 12mm du diam&egrave;tre externe de l'ossature du corps, 7 mm pour le rayon du trou, plus de 5 mm pour l'&eacute;paisseur de paroi. Pour le plaisir d'avoir une partie enti&egrave;rement param&eacute;trique, c'est une bonne id&eacute;e d'ajouter un plan au squelette environ 25 mm au-dessus du plan XY pour marquer le sommet des cylindres. Comme ce sera usin&eacute;e, l'esquisse est dimensionn&eacute; 3mm au-dessus.
</p><p><br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-14.jpg&amp;filetimestamp=20130715192541&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-14.jpg" decoding="async" width="400" height="244" class="mw-file-element" data-file-width="987" data-file-height="601"></a><figcaption> Le corps des boulons </figcaption></figure><p> Cr&eacute;ez une r&eacute;volution de l'esquisse et appliquer un cong&eacute; de 4mm vers le haut. Cela signifie que, apr&egrave;s usinage et enl&egrave;vement de 3mm, un l&eacute;ger rayon restera qui permet d'&eacute;viter une ar&ecirc;te vive o&ugrave; quelqu'un pourrait se couper la main pour serrer la vis. <br clear="all">
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-16.jpg&amp;filetimestamp=20130715192912&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-16.jpg" decoding="async" width="400" height="261" class="mw-file-element" data-file-width="868" data-file-height="566"></a><figcaption> Le corps principal avec les deux organes pour les boulons </figcaption></figure><p> Cr&eacute;er une fonction bool&eacute;enne pour fusionner le corps principal et le corps du boulon. Puis cr&eacute;er un nouvel organe pour l'autre c&ocirc;t&eacute;. Dupliquer le croquis de la r&eacute;volution, le d&eacute;placer &agrave; cet organe et cr&eacute;ez le deuxi&egrave;me corps pour les boulons (Sym&eacute;triser un corps n'est pas encore pris en charge si vous avez besoin de refaire la plus grande partie). Puis fusionner ce deuxi&egrave;me corps dans le corps principal . Enfin, appliquez un grand cong&eacute; sur le bord cr&eacute;&eacute; par l'op&eacute;ration de fusion bool&eacute;enne. Le plus grand que je pouvais obtenir &eacute;tait 4mm. <br clear="all">
</p><p><span id="Hollowing_out_the_main_body"></span>
</p>
<h2><span class="mw-headline" id="Vider_le_corps_principal">Vider le corps principal</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-9.jpg&amp;filetimestamp=20130714182319&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-9.jpg" decoding="async" width="300" height="347" class="mw-file-element" data-file-width="477" data-file-height="551"></a><figcaption> La premi&egrave;re Protusion du corps  d&eacute;coupe  l'int&eacute;rieur du corps principal </figcaption></figure><p> Nous allons maintenant travailler &agrave; l'int&eacute;rieur du support et &eacute;vider pour faire place aux roulements et bagues d'&eacute;tanch&eacute;it&eacute;. En faisant cela bien s&ucirc;r, nous devons garder &agrave; l'esprit la sur&eacute;paisseur de 3mm. Puisque ce tutoriel enseigne la m&eacute;thode multi-corps, nous allons cr&eacute;er la g&eacute;om&eacute;trie &agrave; l'int&eacute;rieur comme un corps s&eacute;par&eacute;, puis le couper sur le corps principal par une op&eacute;ration bool&eacute;enne.
</p><p>Cr&eacute;er un nouveau corps et le rendre actif. Premi&egrave;rement, nous avons besoin d'un plan de r&eacute;f&eacute;rence de 3 mm de d&eacute;calage int&eacute;rieur de la face du squelette qui montre le c&ocirc;t&eacute; du roulement. Puis, dupliquer l'esquisse de la premi&egrave;re Protusion du corps principal. Il sera ajout&eacute; au corps principal, donc faites un clic droit dessus et choisissez le pour le d&eacute;placer vers le corps nouvellement cr&eacute;&eacute; (cette option n' est disponible que dans le menu contextuel si l' atelier PartDesign est actif). Dessiner le croquis sur le plan de r&eacute;f&eacute;rence (si l'esquisse s'inverse apr&egrave;s le dessin, d&eacute;placer le plan de r&eacute;f&eacute;rence de l'autre c&ocirc;t&eacute; du palier, &agrave; c&ocirc;t&eacute; de l'endroit o&ugrave; l'esquisse dupliqu&eacute; est situ&eacute;e). Maintenant, modifier l'esquisse de sorte que le diam&egrave;tre est de 3 mm inf&eacute;rieur au diam&egrave;tre externe de la g&eacute;om&eacute;trie de l'ossature qui repr&eacute;sente le palier. Tout ce que vous devez faire est de retirer lpaliera dimension 5mm, faites glisser l'esquisse &agrave; l'int&eacute;rieur du cercle de r&eacute;f&eacute;rence, et cr&eacute;ez une nouvelle dimension de 3 mm.
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-10.jpg&amp;filetimestamp=20130714183706&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-10.jpg" decoding="async" width="400" height="218" class="mw-file-element" data-file-width="1013" data-file-height="551"></a><figcaption> Le corps de d&eacute;coupe &agrave; l'int&eacute;rieur du corps du squelette </figcaption></figure><p> Ensuite, nous voulons deux autres protusions pour creuser l'emplacement des bagues d'&eacute;tanch&eacute;it&eacute;. Dupliquer le croquis de la premi&egrave;re plage de l'Organe de d&eacute;coupe et de dessiner au plan XZ. Modifier l'esquisse et remplacer la r&eacute;f&eacute;rence externe avec le diam&egrave;tre ext&eacute;rieur de la bague d'&eacute;tanch&eacute;it&eacute; du roulement. Extruder cette esquisse avec un d&eacute;calage de 3 mm du c&ocirc;t&eacute; de la bague d'&eacute;tanch&eacute;it&eacute;. R&eacute;p&eacute;tez l'ensemble du processus pour la bague d'&eacute;tanch&eacute;it&eacute; de l'autre c&ocirc;t&eacute;.
</p><p>Apr&egrave;s cela, nous voulons cr&eacute;er deux autres Protusions comme les deux derniers pour donner &agrave; l'arbre un d&eacute;gagement (par exemple 3 mm) &agrave; l'int&eacute;rieur du support. <br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-11.jpg&amp;filetimestamp=20130714184941&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-11.jpg" decoding="async" width="400" height="200" class="mw-file-element" data-file-width="1055" data-file-height="527"></a><figcaption> Le corps de d&eacute;coupe complet (cong&eacute;s minimum  impossibles) </figcaption></figure><p> Maintenant tout ce qui reste est d'appliquer le projet sur les faces lat&eacute;rales planes, en utilisant le m&ecirc;me plan neutre que pour le corps principal, et le cong&eacute;. Appliquer un cong&eacute; g&eacute;n&eacute;ral de 3mm &agrave; tous les bords. Vous remarquerez qu'il y a plusieurs bords qui ne peuvent pas avoir de cong&eacute;... c'est un d&eacute;faut du noyau g&eacute;om&eacute;trique sous-jacent qui utilise FreeCAD. <br clear="all">
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-15.jpg&amp;filetimestamp=20130715192602&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-15.jpg" decoding="async" width="400" height="237" class="mw-file-element" data-file-width="974" data-file-height="576"></a><figcaption> La pi&egrave;ce brute compl&egrave;te du support (sans usinage) </figcaption></figure><p> Nous sommes pr&ecirc;ts &agrave; creuser le corps principal. S&eacute;lectionnez-le et choisissez de cr&eacute;er une nouvelle op&eacute;ration bool&eacute;enne. Ajouter le corps de d&eacute;coupe &agrave; la liste de la fen&ecirc;tre et r&eacute;gler l'op&eacute;ration pour "Couper". Mettre un cong&eacute; de 3 mm sur les deux bords r&eacute;sultant de l'op&eacute;ration de d&eacute;coupe (encore certains bords restent qui sont "non cong&eacute;able&raquo;). Le r&eacute;sultat devrait ressembler &agrave; l'image sur la droite.
</p><p>La pi&egrave;ce brute est maintenant termin&eacute;e. C'est ce &agrave; quoi le support va ressembler avant l'usinage. A noter que puisque le moule aura une moiti&eacute; sup&eacute;rieure et inf&eacute;rieure, le bord entre les deux n'a pas de cong&eacute;. Aussi, si vous donnez ce mod&egrave;le &agrave; une fonderie assurez-vous de souligner qu'il a les dimensions apr&egrave;s la coul&eacute;e. La fonderie devra ensuite appliquer un certain pourcentage de retrait au mod&egrave;le (faire le mod&egrave;le num&eacute;rique utilis&eacute; pour fabriquer le moule plus grand de sorte que lorsque le m&eacute;tal se refroidit et se contracte apr&egrave;s la coul&eacute;e, il aura la bonne taille). <br clear="all">
</p><p><span id="Machining"></span>
</p>
<h2><span class="mw-headline" id="Usinage">Usinage</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-17.jpg&amp;filetimestamp=20130716182636&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-17.jpg" decoding="async" width="400" height="472" class="mw-file-element" data-file-width="663" data-file-height="782"></a><figcaption> Esquisse pour percer le trou pour les boulons </figcaption></figure><p> Pour enlever la mati&egrave;rie pour l'usinage de l'int&eacute;rieur du support,  nous pouvons utiliser le Squelette du corps . Si vous ne voulez pas parce qu'alors le squelette se cache quelque part au fond de l'arborescence, vous pouvez &eacute;galement dupliquer l'esquisse de la fonction de r&eacute;volution du squelette et recr&eacute;er la r&eacute;volution dans un autre corps. Ce ne est pas compl&egrave;tement param&eacute;trique, cependant, parce que l'esquisse dupliqu&eacute;e est ind&eacute;pendante de l'original, ainsi vous aurez &agrave; travailler sur les deux si vous changez une dimension. Les entit&eacute;s dupliqu&eacute;es d&eacute;pendantes pourront &ecirc;tre prises en charge dans l'avenir.
</p><p>Pour le reste de l'usinage, cr&eacute;er un nouveau corps. Le fond du support sera usin&eacute;e par une Protusion esquiss&eacute;e sur le plan XY s' &eacute;tendant vers le bas. Ensuite, esquisser une r&eacute;volution pour faire un trou pour les boulons. Vous aurez besoin d'esquisser sur le plan XZ et tourner de sorte que vous pouvez choisir le diam&egrave;tre ext&eacute;rieur du squelette du Corps comme une r&eacute;f&eacute;rence externe. La partie sup&eacute;rieure de l'esquisse servira &agrave; usiner un endroit plat pour la t&ecirc;te du boulon. Elle est dimensionn&eacute;e pour laisser une &eacute;paisseur de paroi d'au moins 5 mm dans le support. Si cela ne donne pas suffisamment d'espace pour la t&ecirc;te de boulon, vous pouvez d&eacute;placer le plan de r&eacute;f&eacute;rence vers le haut. Bien s&ucirc;r, vous pourriez mettre cette logique dans le squelette, qui est laiss&eacute; comme exercice pour le lecteur! <br clear="all">
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-18.jpg&amp;filetimestamp=20130716182656&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-18.jpg" decoding="async" width="400" height="293" class="mw-file-element" data-file-width="985" data-file-height="722"></a><figcaption> L'usinage du corps  </figcaption></figure><p> Vous pouvez sym&eacute;triser la r&eacute;volution sur l'axe YZ. L'image de droite montre l'&laquo;usinage&raquo; du corps. Bien s&ucirc;r, la plupart des dimensions des Protusions et r&eacute;volutions ne sont pas importantes aussi longtemps qu' il ya beaucoup de chevauchement. <br clear="all">
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a href="../index.php?title=HolderTop2-19.jpg&amp;filetimestamp=20130716184057&amp;.html" class="mw-file-description"><img src="../File/HolderTop2-19.jpg" decoding="async" width="400" height="263" class="mw-file-element" data-file-width="1037" data-file-height="683"></a><figcaption> Le support fini avec l'usinage </figcaption></figure><p> Enfin, cr&eacute;er une op&eacute;ration bool&eacute;enne pour couper le Corps de usin&eacute; par le Corps principal. Si vous voulez un bel effet visuel, vous pouvez colorer les surfaces usin&eacute;es diff&eacute;remment du reste de la pi&egrave;ce. C'est aussi une r&eacute;troaction optique utile, vous indiquant si vous avez oubli&eacute; d'usiner quelque part. <br clear="all">
</p><h2><span class="mw-headline" id="Partie_Une">Partie Une</span></h2>
<p><a href="../fr/PartDesign_Bearingholder_Tutorial_I.html" title="PartDesign Bearingholder Tutorial I/fr"> Tutoriel de Conception Support de Roulement I</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20251220223848
Cache expiry: 86400
Reduced expiry: false
Complications: [show&#8208;toc]
CPU time usage: 0.072 seconds
Real time usage: 0.191 seconds
Preprocessor visited node count: 109/1000000
Post&#8208;expand include size: 1570/2097152 bytes
Template argument size: 144/2097152 bytes
Highest expansion depth: 4/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post&#8208;expand size: 2440/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%   11.203      1 -total
 39.07%    4.377      1 Template:Clear
 30.21%    3.384      1 Template:Caption
 28.58%    3.202      1 Template:TutorialInfo
-->

<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:54982-0!canonical and timestamp 20251220223848 and revision id 1687162. Rendering was triggered because: edit-page
 -->
</div>
</div><script src="../site.js"></script>