<link href="../site.css" rel="stylesheet" type="text/css"/>
<div class="mw-page-container"><h1 class="firstHeading mw-first-heading" id="firstHeading"><span class="mw-page-title-main">PartDesign Bearingholder Tutorial I/fr</span></h1><div class="mw-parser-output"><div id="itsfree" style="text-align:center; background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">
<figure class="mw-halign-left" typeof="mw:File"><span><img decoding="async" height="38" src="https://upload.wikimedia.org/wikipedia/commons/d/d5/Under_construction_icon-blue.svg" width="45"/></span><figcaption></figcaption></figure> This documentation is a work in progress. Please don't mark it as translatable since it will change in the next hours and days.
</div><div style="clear:both"></div>
<div id="itsfree" style="text-align:center;color:black;background:#FDE0A8;margin:1em 7em;padding:0.5em 2em;border:2px solid #FF5706;">This tutorial was originally written for a now deprecated development version of FreeCAD. This tutorial requires a complete rewrite to align with the PartDesign changes that will be in the upcoming v0.17 release.</div>
<div class="mw-pt-languages noprint" dir="ltr" lang="en"><div class="mw-pt-languages-label">Other languages:</div><ul class="mw-pt-languages-list"><li><a class="mw-pt-progress mw-pt-progress--complete" dir="ltr" href="../de\PartDesign_Bearingholder_Tutorial_I.html" lang="de" title="PartDesign Lagergehäuse Tutorium I (100% translated)">Deutsch</a></li>
<li><a class="mw-pt-languages-ui mw-pt-progress mw-pt-progress--complete" dir="ltr" href="../PartDesign_Bearingholder_Tutorial_I.html" lang="en" title="PartDesign Bearingholder Tutorial I (100% translated)">English</a></li>
<li><a class="mw-pt-progress mw-pt-progress--stub" dir="ltr" href="../tr\PartDesign_Bearingholder_Tutorial_I.html" lang="tr" title="PartDesign Bearingholder Tutorial I/tr (2% translated)">Türkçe</a></li>
<li><a class="mw-pt-progress mw-pt-progress--stub" dir="ltr" href="../es\PartDesign_Bearingholder_Tutorial_I.html" lang="es" title="PartDesign Soporte de rodamiento Tutorial I (12% translated)">español</a></li>
<li><span class="mw-pt-languages-selected mw-pt-progress mw-pt-progress--complete" dir="ltr" lang="fr">français</span></li>
<li><a class="mw-pt-progress mw-pt-progress--complete" dir="ltr" href="../it\PartDesign_Bearingholder_Tutorial_I.html" lang="it" title="Prima parte del tutorial per creare un supporto per cuscinetto con PartDesign (100% translated)">italiano</a></li>
<li><a class="mw-pt-progress mw-pt-progress--complete" dir="ltr" href="../pl\PartDesign_Bearingholder_Tutorial_I.html" lang="pl" title="Poradnik: Projekt części, uchwyt łożyska cześć 1 (100% translated)">polski</a></li>
<li><a class="mw-pt-progress mw-pt-progress--stub" dir="ltr" href="../pt-br\PartDesign_Bearingholder_Tutorial_I.html" lang="pt-BR" title="Tutorial de Projeto de Mancais de Apoio I (2% translated)">português do Brasil</a></li>
<li><a class="mw-pt-progress mw-pt-progress--complete" dir="ltr" href="../ro\PartDesign_Bearingholder_Tutorial_I.html" lang="ro" title="PartDesign Bearingholder Tutorial I (96% translated)">română</a></li>
<li><a class="mw-pt-progress mw-pt-progress--stub" dir="ltr" href="../ru\PartDesign_Bearingholder_Tutorial_I.html" lang="ru" title="PartDesign Bearingholder Tutorial I/ru (2% translated)">русский</a></li></ul></div>
<table class="fcinfobox wikitable ct" style="width: 230px; float: right; margin-left: 1em">
<tbody><tr>
<td class="ctTitle" style="font-weight: bold; font-size: 125%;"><span typeof="mw:File"><span><img decoding="async" height="32" src="../File/Freecad.svg" width="32"/></span></span> Tutorial
</td></tr>
<tr>
<th class="ctOdd">Topic
</th></tr>
<tr>
<td class="ctEven">Modélisation
</td></tr>
<tr>
<th class="ctOdd">Level
</th></tr>
<tr>
<td class="ctEven">Utilisateur expérimenté
</td></tr>
<tr>
<th class="ctOdd">Time to complete
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">Authors
</th></tr>
<tr>
<td class="ctEven">NormandC
</td></tr>
<tr>
<th class="ctOdd">FreeCAD version
</th></tr>
<tr>
<td class="ctEven">≥ 0.19.23300
</td></tr>
<tr>
<th class="ctOdd">Example files
</th></tr>
<tr>
<td class="ctEven">
</td></tr>
<tr>
<th class="ctOdd">See also
</th></tr>
<tr>
<td class="ctEven"><i>None</i>
</td></tr>
<tr>
<td class="ctToc"><br/><div aria-labelledby="mw-toc-heading" class="toc" id="toc" role="navigation"><input class="toctogglecheckbox" id="toctogglecheckbox" role="button" style="display:none" type="checkbox"/><div class="toctitle" dir="ltr" lang="en"><h2 id="mw-toc-heading">Contents</h2><span class="toctogglespan"><label class="toctogglelabel" for="toctogglecheckbox"></label></span></div>
<ul>
<li class="toclevel-1 tocsection-1"><a href="#L'objectif_en_deux_mots"><span class="tocnumber">1</span> <span class="toctext">L'objectif en deux mots</span></a></li>
<li class="toclevel-1 tocsection-2"><a href="#Les_Données_de_Conception"><span class="tocnumber">2</span> <span class="toctext">Les Données de Conception</span></a></li>
<li class="toclevel-1 tocsection-3"><a href="#Mise_en_place_de_la_géométrie_de_l'ossature"><span class="tocnumber">3</span> <span class="toctext">Mise en place de la géométrie de l'ossature</span></a></li>
<li class="toclevel-1 tocsection-4"><a href="#Le_solide_géométrique"><span class="tocnumber">4</span> <span class="toctext">Le solide géométrique</span></a></li>
<li class="toclevel-1 tocsection-5"><a href="#Application_de_dépouille_sur_les_faces_latérales"><span class="tocnumber">5</span> <span class="toctext">Application de dépouille sur les faces latérales</span></a></li>
<li class="toclevel-1 tocsection-6"><a href="#Congés_sur_le_support"><span class="tocnumber">6</span> <span class="toctext">Congés sur le support</span></a></li>
<li class="toclevel-1 tocsection-7"><a href="#Usinage"><span class="tocnumber">7</span> <span class="toctext">Usinage</span></a></li>
<li class="toclevel-1 tocsection-8"><a href="#Notes_Finales"><span class="tocnumber">8</span> <span class="toctext">Notes Finales</span></a></li>
<li class="toclevel-1 tocsection-9"><a href="#Partie_Deux"><span class="tocnumber">9</span> <span class="toctext">Partie Deux</span></a></li>
</ul>
</div>
</td></tr></tbody></table>
<p>Tutoriel Support de Roulement - Support de roulement terminé
</p>
<h2><span id="L.27objectif_en_deux_mots"></span><span class="mw-headline" id="L'objectif_en_deux_mots">L'objectif en deux mots</span></h2>
<p>Le but de ce tutoriel est de vous présenter deux flux de travail différents pour créer une pièce moulée avec des ébauches et des congés. Selon les autres programmes de CAO que vous avez utilisés, l'un ou l'autre peut vous être familier. Comme exemple de travail, nous allons modéliser un simple support de roulement.
</p><p>Ceci est la première partie du tutoriel. Elle utilisera ce qu'on pourrait appeler la méthode «corps unique» , en utilisant la partie (simple) supérieure du support comme un exemple
</p><p>Évidemment, pour suivre ce tutoriel, vous devez activer l'Atelier Conception de Pièce.
</p><p><strike>Vous pouvez trouver ma version de la pièce créée dans ce tutoriel [<a class="external text" href="http://ubuntuone.com/39PTZ3Y3LUnmZzpZQPcJT4" rel="nofollow">ici</a>]. </strike> <i>Ce fichier n'est plus disponible, un nouveau fichier sera fourni à une date ultérieure.</i>
<br clear="all"/>
</p><p><span id="Design_data"></span>
</p>
<h2><span id="Les_Donn.C3.A9es_de_Conception"></span><span class="mw-headline" id="Les_Données_de_Conception">Les Données de Conception</span></h2>
<p>Le support doit être en mesure de tenir un Roulement d'un diamètre de 90mm avec une largeur allant jusqu'à 33mm (par exemple DIN 630 Type 2308, qui a un diamètre intérieur de 40 mm). Le roulement nécessite une hauteur d'épaulement d'au moins 4,5 mm dans le support (et sur l'arbre). La partie supérieure du support sera boulonné sur l'autre partie avec deux boulons de 12mm. Pour la tête d'un tel boulon, il faudra au moins 20 mm de diamètre d'espace libre. Il devrait y avoir une rainure sur les deux côtés du roulement capables de tenir un arbre standard bague d'étanchéité DIN 3760: 38x55x7 40x55x7 ou sur un côté, 50x68x8 de l'autre côté.
</p><p>Le support sera réalisé dans un moule en sable avec une épaisseur minimale de paroi de 5 mm, un angle de dépouille de 2 degrés, et un rayon de congé minimum de 3mm.
</p>
<h2><span id="Mise_en_place_de_la_g.C3.A9om.C3.A9trie_de_l.27ossature"></span><span class="mw-headline" id="Mise_en_place_de_la_géométrie_de_l'ossature">Mise en place de la géométrie de l'ossature</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-2.jpg"><img decoding="async" height="284" src="../File/HolderTop1-2.jpg" width="400"/></a><figcaption>support de roulement avec les deux plans les plus importants de l'ossature</figcaption></figure>
<p>L'idée de la géométrie de l'ossature est de capturer les dimensions de base de la conception en une caractéristique unique de référence (par exemple, un plan ou un axe). Lorsque la dimension de conception change, tout ce qui doit être fait est de changer la fonction de squelette. Si le modèle est bien construit, alors toute sa fonction sera de recalculer pour refléter le changement de conception. Cela réduit le risque que, dans un modèle complexe, où les dimensions de conception de base sont utilisées dans de multiples endroits, vous oubliez de changer des éléments quelque part.
</p><p>L'alternative à la géométrie de l'ossature est d'avoir une table des dimensions de conception de base qui attribuent un nom symbolique à chaque dimension, puis utilisez le nom symbolique là où les dimensions sont nécessaires pour construire le modèle. FreeCAD ne permet pas encore cette approche
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-3.jpg"><img decoding="async" height="277" src="../File/HolderTop1-3.jpg" width="400"/></a><figcaption>Plans de Base et tous les plans de référence</figcaption></figure>
<p>Dans le cas du support de palier, les deux dimensions de conception les plus importants sont la distance entre les boulons (ce qui limite la taille du roulement qui peut être utilisée) et la hauteur de la tête des boulons. Les dimensions sont choisies * Distance entre les boulons: rayon de roulement (45) + épaisseur de paroi (5) plus le rayon du trou pour boulon (7) = 57 mm, de sorte que le plan vertical de 57 mm est décalé par rapport au plan YZ. Pour créer ce plan de référence, sélectionnez le plan YZ et ensuite choisir de créer un nouveau plan de référence. Entrez le décalage dans la boîte de dialogue qui se ouvre * Hauteur de têtes de boulons: Cela a été choisi comme un décalage de 28mm du plan XZ
</p><p>Pour plus de commodité, deux autres plans de référence peuvent être créés pour refléter la quantité de matériau qui doit être coupée  des côtés du support déroulement. Ils sont décalés de +22 et -22 depuis le plan XY.
</p><p>Il est conseillé de donner des noms clairs à la géométrie du de l'ossature. La plupart du temps, vous voudrez désactiver la visibilité des plans de référence, car ils encombrent l'écran, et si les plans ont des noms explicites vous pouvez simplement choisir leur nom au lieu de les choisir depuis l'écran. <br clear="all"/>
</p><p><span id="The_solid_geometry"></span>
</p>
<h2><span id="Le_solide_g.C3.A9om.C3.A9trique"></span><span class="mw-headline" id="Le_solide_géométrique">Le solide géométrique</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-4.jpg"><img decoding="async" height="244" src="../File/HolderTop1-4.jpg" width="400"/></a><figcaption>Croquis du première protusion</figcaption></figure><p> Maintenant il est temps de commencer à créer une géométrie réelle. L'esquisse pour la première protusion est affichée sur la droite. Elle est placée sur le plan XY. Il y a juste trois dimensions: le rayon intérieur (de 22,5 mm), l'allocation d'usinage (3mm) à la base comme un décalage au pla-XZ et la distance entre le plan de référence représentant l'axe du boulon (7mm). Cela signifie que si vous vous déplacez plus tard, le plan de référence, la protusion ajustera automatiquement son rayon extérieur. N'oubliez pas qu'avant de pouvoir utiliser le plan de référence pour le dimensionnement, vous devez introduire la géométrie externe au sketcher
</p><p>Vous vous demandez probablement pourquoi il y a ce petit segment de droite au bas de chaque arc. Ce segment indique qu'il y aura un angle de deux degrés sur les arcs. Cela pourrait ressembler à beaucoup de travail pour un très petit avantage, mais de nombreux programmes de CAO (et peut-être un jour FreeCAD) disposent d'outils qui mettent en évidence un modèle solide en différentes couleurs immédiatement et vous présentent toutes les faces où l'angle de dépouille n'est pas correct. Vous ne voulez pas que cela arrive à votre modèle, en particulier après la mise en place d'un grand nombre de congés! <br clear="all"/>
</p><p>Lorsque vous avez fait le croquis (qui est un peu difficile à cause des deux degrés des lignes tangentielles), ajuster la protusion symétriquement au plan d'esquisse d'une longueur de 62mm: 34mm pour le palier, 2x 9mm pour les bagues d'étanchéité, 2x 5mm pour l'épaisseur de paroi. <br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-5.jpg"><img decoding="async" height="229" src="../File/HolderTop1-5.jpg" width="400"/></a><figcaption>Croquis de la coupe sur le coté de la Protusion</figcaption></figure><p> Ensuite, nous voulons  retrancher certains matériaux où sont les bagues d'étanchéité, parce que leur diamètre extérieur est beaucoup moins que le roulement . La meilleure façon de créer les croquis est de sélectionner l'esquisse de la protusion et puis choisissez "sélection Dupliquer" dans le menu d'édition. Vous pouvez ensuite redéfinir le croquis sur le côté de la protusion, et le modifier comme indiqué dans l'image.
</p><p>Les deux seules dimensions importantes dans l'esquisse sont 3 mm de surépaisseur d'usinage au fond, et un diamètre intérieur de 78mm : 68mm pour le diamètre extérieur de l'épaisseur de paroi + 2x5mm de bague d'étanchéité. Puisque la bague d'étanchéité de l'autre côté aura un diamètre de 55mm, la découpe peut être de 65mm ici.
</p><p>Après avoir créé l'esquisse, creusez jusqu'au plan de référence marquant le coté du roulement plus l'épaisseur de paroi 5 mm . Si jamais vous voulez modifier le support pour qu'il soit  capable de porter des roulements plus larges, tout ce que vous avez à faire est de changer la dimension de ces plans de référence, et la profondeur de découpe devra suivre. <br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-6.jpg"><img decoding="async" height="254" src="../File/HolderTop1-6.jpg" width="400"/></a><figcaption>Croquis de découpe à l'intérieur de la protusion</figcaption></figure><p> Pour réduire la quantité d'usinage nécessaire, nous voulons aussi découper certains matériaux à l'intérieur du support . Encore une fois, la duplication de l'esquisse de la première Protusion est pratique. Elle n'a même pas besoin d'être reconfigurée. Encore une fois, les seules dimensions importantes sont la surépaisseur d'usinage (3mm) et les diamètres extérieurs: 84mm pour le l'emplacement du roulement  (90mm - 2x allocation d'usinage), 49mm pour le petit anneau d'étanchéité (55mm - 2x 3mm) et 62mm pour la bague d'étanchéité plus grande.
</p><p>Après avoir créé les esquisses, les creuser: Symétriquement 28mm pour la découpe du roulement (34mm - 2x surépaisseur d'usinage ) et 23mm sur un coté pour les découpes des bagues d'étanchéité: 34mm / 2 pour la moitié de la largeur du roulement + 9mm pour la bagues d'étanchéité - surépaisseur d'usinage de 3mm. <br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-7.jpg"><img decoding="async" height="273" src="../File/HolderTop1-7.jpg" width="400"/></a><figcaption>Géométrie principale du haut du support</figcaption></figure><p> La pièce doit maintenant ressembler à l'image sur la droite. Notez comment les différentes découpes se combinent pour créer une épaisseur de paroi presque uniforme, ce qui rendra la coulée plus facile et moins susceptibles d'avoir des pores. <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-8.jpg"><img decoding="async" height="276" src="../File/HolderTop1-8.jpg" width="400"/></a><figcaption>Croquis avec l'emplacement des boulons</figcaption></figure><p> Maintenant tout ce qui reste a faire est de créer de la matière pour le passage des boulons. Vous pourriez être tenté d'esquisser ceci comme un cercle puis le protuser, mais cela vous dirigera vers des problèmes lorsque vous essaierez de le mettre plus tard sur le projet (je suppose que c'est une faiblesse d'OpenCascade). Donc, pour éviter les problèmes, il est préférable de créer une esquisse de l'angle projeté  inclus, puis la tourner de 360 degrés.
</p><p>Là encore, les plans de l'ossature deviennent utile. Vous aurez besoin du plan de l'axe du boulon et du plan de la tête du boulon comme géométrie externe. Ensuite, créez une ligne droite pour l'axe de rotation et assurez-vous qu'il est contraint à l'axe du boulon du plan de référence. Le basculer pour devenir une géométrie de construction. Puis, esquisser le reste du contour. Les dimensions importantes sont la surépaisseur d'usinage en haut et en bas et le rayon de 12 mm : 7 mm pour le rayon du trou + épaisseur de paroi de 5 mm. <br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-9.jpg"><img decoding="async" height="273" src="../File/HolderTop1-9.jpg" width="400"/></a><figcaption>géométrie finie de la partie supérieure du support (sans projet et  congés)</figcaption></figure><p> Créer une fonction de révolution de l'esquisse, puis la symétriser sur le plan YZ . C'est toute la géométrie solide nous devons modéliser. Le reste est brouillon et congés. <br clear="all"/>
</p><p><span id="Applying_draft_to_the_side_faces"></span>
</p>
<h2><span id="Application_de_d.C3.A9pouille_sur_les_faces_lat.C3.A9rales"></span><span class="mw-headline" id="Application_de_dépouille_sur_les_faces_latérales">Application de dépouille sur les faces latérales</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-10.jpg"><img decoding="async" height="254" src="../File/HolderTop1-10.jpg" width="400"/></a><figcaption>Le plan neutre pour la création de dépouille</figcaption></figure><p> L'étape suivante consiste à appliquer des dépouilles sur toutes les faces . Il est important de bien choisir l'emplacement du plan neutre, c'est le plan autour duquel on tourne. Si nous choisissons comme plan neutre, le bas du support, alors nous aurons un problème avec l'épaisseur de paroi dans la partie supérieure du support. Par conséquent, nous créons un plan de référence avec un décalage de 40 mm par rapport au plan XZ comme un compromis entre le haut de la porte devant mince et le bas de devenant large . <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-11.jpg"><img decoding="async" height="170" src="../File/HolderTop1-11.jpg" width="400"/></a><figcaption>Application de dépouille sur les faces latérales du support</figcaption></figure><p> Pour mettre une dépouille sur une face , sélectionner cette face et  créer la caractéristique de la dépouille . Vous pouvez ensuite sélectionner plusieurs faces et appliquer la dépouille dessus . Si vous avez une grande pièce, il est conseillé de dépouiller une seule face à la fois. Cela signifie que si vous modifiez la géométrie et qu'une dépouille échoue, seul cette  caractéristique va échouer, alors que si vous mettez sur tous les faces une fonction de dépouille, alors l'ensemble  des fonction ensemble pourrait échouer à cause d'une faute d'une face. Pour une petite pièce comme le support de roulement, c'est suffisant de créer deux fonctions de dépouille : Une pour les quatre faces extérieures, et une pour les faces internes.
</p><p>La boîte de dialogue va vous forcer à choisir un plan neutre avant de remplir. Vous pouvez laisser la direction d'étirement vide, dans ce cas, il sera perpendiculaire au plan neutre. Ne oubliez pas de régler l'angle de dépouille à 2 degrés. <br clear="all"/>
</p><p><span id="Filleting_the_holder"></span>
</p>
<h2><span id="Cong.C3.A9s_sur_le_support"></span><span class="mw-headline" id="Congés_sur_le_support">Congés sur le support</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-13.jpg"><img decoding="async" height="275" src="../File/HolderTop1-13.jpg" width="400"/></a><figcaption>Congés où seront les boulons</figcaption></figure><p> Nous pouvons maintenant arrondir la pièce. La photo montre le premier jeu de congés. Commencez par les petits congés circulaires et leurs donner un rayon 4mm. Même si 3 mm suffiraient selon les spécifications de la pièce, un rayon de 4 mm signifie qu'après l'usinage du congé  1 mm est laissé, réduisant l'arête vive produite par l'usinage. Les grands congés ont un rayon de 6mm pour aider à répandre la force des boulons sur le reste de la pièce. Ce serait bien de faire ce rayon encore plus grand, mais malheureusement OpenCascade ne peut pas gérer encore les congés qui se chevauchent .
</p><p>Comme avec les dépouilles, dans un cadre complexe, vous devez arrondir un seul bord à la fois pour éviter les échecs inutiles si la géométrie de base change. <br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-12.jpg"><img decoding="async" height="259" src="../File/HolderTop1-12.jpg" width="400"/></a><figcaption>Congé à l'extérieur du support</figcaption></figure><p> Le reste des congés ont tout simplement un rayon de 3 mm. En regardant l'image sur la droite, les deux congés mis en évidence pourraient effectivement être des congés avec un rayon de 5 mm pour atteindre une épaisseur de paroi plus uniforme pour la coulée. Après usinage, l'épaisseur de paroi minimale de 5 mm serait toujours maintenue. Mais encore une fois le fait que OpenCascade ne peut pas gérer le chevauchement des congés nous empêche de le faire pour les deux congés intérieurs mis en évidence. <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-14.jpg"><img decoding="async" height="331" src="../File/HolderTop1-14.jpg" width="400"/></a><figcaption>Congé à l'intérieur du support - bord problématique</figcaption></figure><p> Faire des congés l'intérieur de la pièce nous présente une difficulté qui ne peut être résolue avec les outils actuels dans l'atelier PartDesign. Le bord du congé ne peut pas du tout être mis en évidence , encore une fois parce que les congés se chevaucheraient. Cela pourrait être contourné par la création d'une courbe à la place d'un congé, sauf que les courbes ne sont pas encore mises en œuvre dans PartDesign. Pour le moment, nous sommes forcés de quitter le bord comme il est. <br clear="all"/>
</p><figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-15.jpg"><img decoding="async" height="279" src="../File/HolderTop1-15.jpg" width="400"/></a><figcaption>La pièce en congé (sauf pour le bord impossible)</figcaption></figure><p> L'image de droite montre la pièce finie dans l'état où elle sera avant l'usinage (à l'exception de l'un des bords où il est impossible de créer un congé). Vous remarquerez qu'un bord qui tourne autour de toute la pièce a été laissé sans congé dans ce but. Il s'agit du bord où la partie inférieure et la partie supérieure du moule se rencontrent. Ici, pas de congé possible (et aucun n' est requis de toute façon). <br clear="all"/>
</p><p><span id="Machining"></span>
</p>
<h2><span class="mw-headline" id="Usinage">Usinage</span></h2>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-16.jpg"><img decoding="async" height="201" src="../File/HolderTop1-16.jpg" width="400"/></a><figcaption>Usinage haut et bas du support</figcaption></figure> <figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-17.jpg"><img decoding="async" height="295" src="../File/HolderTop1-17.jpg" width="400"/></a><figcaption>Usinage intérieur du support de Roulement</figcaption></figure><p> maintenant, nous pouvons couper le matériel qui sera usiné à partir de la pièce brute en fonte. C'est très facile avec la géométrie du squelette défini. L'idée est de créer toutes les caractéristiques d'usinage (Cavités et  rainures) en utilisant uniquement  donnée caractéristiques. Cela signifie qu'ils vont être totalement indépendant de la géométrie solide du support de roulement, ce qui nous donne quelques grands avantages: * Peu importe comment vous modifiez la géométrie solide, les caractéristiques pour l'usinage ne pourront pas échouer. * Vous pouvez créer la géométrie d'usinage avant de finaliser le solide, ce qui vous donne une rétroaction visuelle utile. * Si vous déplacez les plans squelettes de repère, alors la géométrie du solide et l'usinage s'adapteront automatiquement en même temps . * Si vous faites une erreur dans votre géométrie solide, l'usinage sera toujours dans la position correcte, et très probablement l'erreur deviendra flagrante (par exemple, une épaisseur de paroi de 2 mm au lieu 5mm). Alors que si vous faites référence à l'usinage de la géométrie solide, il va s'adapter à l'erreur dans le solide et, par exemple maintenir l'épaisseur de paroi de 5 mm, juste au mauvais endroit où se trouve le solide.
</p><p>Avant de commencer la géométrie d'usinage, j'aime placer un point de référence dans l'arbre et le nommer comme "Usinage_démarrera_ici". C'est utile si vous souhaitez basculer entre l'état brut et l'état usiné de la pièce parce que vous pouvez voir en un coup d'œil où déplacer le point d'insertion pour obtenir l'état brut.
</p><p>Pour usiner la partie inférieure du support, il suffit de tracer un grand rectangle dans le plan XZ et le creuser. Pour le haut, esquisser un cercle sur le plan de référence définissant l'emplacement de la tête de vis, puis symétriser la cavité sur le plan YZ. De la même manière, créer une cavité pour le trou où passe le boulon et le symétriser. Pour usiner l'intérieur du support, créer une esquisse sur le plan YZ et le rainurer. <br clear="all"/>
</p>
<figure class="mw-halign-right" typeof="mw:File/Thumb"><a class="mw-file-description" href="../File/HolderTop1-1.jpg"><img decoding="async" height="277" src="../File/HolderTop1-1.jpg" width="400"/></a><figcaption>Pièce finie</figcaption></figure><p> Une fois que vous avez réaliser l'usinage, vous pouvez avoir un bon effet visuel en colorant toutes les surfaces usinées de sorte que vous pouvez voir d'un coup d'œil les parties qui sont brut de fonderie et celles qui sont usinées après la coulée.
</p><p><br clear="all"/>
</p><p><span id="Final_notes"></span>
</p>
<h2><span class="mw-headline" id="Notes_Finales">Notes Finales</span></h2>
<p>Nous avons modélisé le haut du support de roulement avec les dimensions qu'il aura après la coulée. Pour créer le moule, vous devez appliquer un retrait à votre pièce parce que après la coulée, lorsque le métal chaud se refroidit, il va diminuer de quelques pour cent (selon le matériau). Habituellement, il est préférable de laisser l'application de retrait à la fonderie faisant la pièce parce qu'ils ont les connaissances particulières requises. Ils devraient également vous dire si votre pièce comporte des zones problématiques, par exemple parois très épaisse rejoignant brusquement des sections très minces sans transition correcte entre elles.
</p>
<h2><span class="mw-headline" id="Partie_Deux">Partie Deux</span></h2>
<p><a href="../fr\PartDesign_Bearingholder_Tutorial_II.html" title="PartDesign Bearingholder Tutorial II/fr">Tutoriel de Conception Support de Roulement II</a>
</p>
<div style="clear:both"></div>
<!-- 
NewPP limit report
Cached time: 20241214204335
Cache expiry: 86400
Reduced expiry: false
Complications: [show‐toc, no‐toc‐conversion]
CPU time usage: 0.162 seconds
Real time usage: 0.686 seconds
Preprocessor visited node count: 113/1000000
Post‐expand include size: 1513/2097152 bytes
Template argument size: 272/2097152 bytes
Highest expansion depth: 3/100
Expensive parser function count: 0/100
Unstrip recursion depth: 0/20
Unstrip post‐expand size: 2193/5000000 bytes
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%   33.352      1 -total
  4.04%    1.348      1 Template:TutorialInfo
  2.26%    0.755      1 Template:Page_in_progress
  1.79%    0.597      1 Template:VeryImportantMessage
  1.46%    0.486      1 Template:Clear
-->
<!-- Saved in parser cache with key freecadweb_db01-wiki_:pcache:idhash:55225-0!canonical and timestamp 20241214204335 and revision id 1471509. Rendering was triggered because: api-parse
 -->
</div></div><script src="../script.js"></script>
